import type { MatrixSourceTag } from "../types/matrix.types";

const EXTRA_PLAYER_TAGS: readonly MatrixSourceTag[] = [
  "R. Wilson #2",
  "C. Adams #5",
  "N. Price #10",
  "B. Foster #18",
  "E. Gray #23",
  "S. Young #26",
  "P. Ward #33",
  "G. Ross #40",
  "H. King #50",
  "V. Cole #55",
  "O. Bell #64",
  "I. Morgan #70",
  "F. Diaz #75",
  "Q. Lane #83",
  "W. Clark #88",
  "Z. Moore #94",
].map((player, index) => ({
  action: index % 4 === 0 ? "Pass Incomplete" : index % 4 === 1 ? "First Down" : index % 4 === 2 ? "Penalty" : "Rush",
  groupValue: `Quarter ${(index % 4) + 1}`,
  id: `mock-af-extra-${index + 1}`,
  player,
  playlistFallbackTimestamp: `00:${String(12 + index * 2).padStart(2, "0")}:00`,
  playlistTimestamp: `00:${String(12 + index * 2).padStart(2, "0")}:00`,
  sourceTagId: `mock-tag-af-extra-${index + 1}`,
  team: index % 3 === 0 ? "Offense" : index % 3 === 1 ? "Defense" : "Special Teams",
}));

export const AMERICAN_FOOTBALL_SAMPLE_TAGS: readonly MatrixSourceTag[] = [
  {
    action: "Pass Complete",
    groupValue: "Quarter 1",
    id: "mock-af-1",
    player: "D. Carter #7",
    playlistFallbackTimestamp: "00:03:18",
    playlistTimestamp: "00:03:18",
    sourceTagId: "mock-tag-af-1",
    team: "Offense",
  },
  {
    action: "Pass Complete",
    groupValue: "Quarter 1",
    id: "mock-af-2",
    player: "L. Turner #81",
    playlistFallbackTimestamp: "00:05:42",
    playlistTimestamp: "00:05:42",
    sourceTagId: "mock-tag-af-2",
    team: "Offense",
  },
  {
    action: "Sack",
    groupValue: "Quarter 2",
    id: "mock-af-3",
    player: "A. Stone #52",
    playlistFallbackTimestamp: "00:17:06",
    playlistTimestamp: "00:17:06",
    sourceTagId: "mock-tag-af-3",
    team: "Defense",
  },
  {
    action: "Touchdown",
    groupValue: "Quarter 2",
    id: "mock-af-4",
    player: "J. Miller #21",
    playlistFallbackTimestamp: "00:23:11",
    playlistTimestamp: "00:23:11",
    sourceTagId: "mock-tag-af-4",
    team: "Offense",
  },
  {
    action: "Interception",
    groupValue: "Quarter 3",
    id: "mock-af-5",
    player: "K. Hayes #44",
    playlistFallbackTimestamp: "00:34:48",
    playlistTimestamp: "00:34:48",
    sourceTagId: "mock-tag-af-5",
    team: "Defense",
  },
  {
    action: "Rush",
    groupValue: "Quarter 3",
    id: "mock-af-6",
    player: "T. Reed #32",
    playlistFallbackTimestamp: "00:39:20",
    playlistTimestamp: "00:39:20",
    sourceTagId: "mock-tag-af-6",
    team: "Offense",
  },
  {
    action: "Penalty",
    groupValue: "Quarter 4",
    id: "mock-af-7",
    player: "M. Brooks #12",
    playlistFallbackTimestamp: "00:47:02",
    playlistTimestamp: "00:47:02",
    sourceTagId: "mock-tag-af-7",
    team: "Special Teams",
  },
  {
    action: "Fumble",
    groupValue: "Quarter 4",
    id: "mock-af-8",
    player: "D. Carter #7",
    playlistFallbackTimestamp: "00:51:36",
    playlistTimestamp: "00:51:36",
    sourceTagId: "mock-tag-af-8",
    team: "Offense",
  },
  {
    action: "Tackle",
    groupValue: "Quarter 4",
    id: "mock-af-9",
    player: "K. Hayes #44",
    playlistFallbackTimestamp: "00:54:14",
    playlistTimestamp: "00:54:14",
    sourceTagId: "mock-tag-af-9",
    team: "Defense",
  },
  ...EXTRA_PLAYER_TAGS,
];
