FROM node:22-alpine
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

COPY . .

RUN corepack enable pnpm && pnpm add -g turbo
RUN pnpm install

EXPOSE 4000

ENV NEXT_PUBLIC_SPACE_BASE_PATH="/spaces"

VOLUME [ "/app/node_modules", "/app/space/node_modules"]
CMD ["pnpm","dev", "--filter=space"]
