from django.urls import path

from plane.ee.views.app.oauth import (
    OAuthApplicationEndpoint,
    OAuthApplicationRegenerateSecretEndpoint,
    OAuthApplicationCheckSlugEndpoint,
    OAuthApplicationInstallEndpoint,
    OAuthApplicationPublishEndpoint,
    OAuthApplicationClientIdEndpoint,
    OAuthApplicationCategoryEndpoint,
    OAuthAppInstallationDetailEndpoint,
    OAuthPublishedApplicationBySlugEndpoint,
    OAuthUserAppInstallationDetailEndpoint,
    OAuthWorkspacesCheckAppInstallationAllowedEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/applications/",
        OAuthApplicationEndpoint.as_view(),
        name="application",
    ),
    path(
        "workspaces/<str:slug>/applications/<str:app_slug>/",
        OAuthApplicationEndpoint.as_view(),
        name="app-installation-detail",
    ),
    path(
        "workspaces/<str:slug>/applications/<uuid:pk>/regenerate-secret/",
        OAuthApplicationRegenerateSecretEndpoint.as_view(),
        name="application-regenerate-secret",
    ),
    path(
        "workspaces/<str:slug>/applications/check-slug/",
        OAuthApplicationCheckSlugEndpoint.as_view(),
        name="application-check-slug",
    ),
    path(
        "workspaces/<str:slug>/applications/<uuid:pk>/install/",
        OAuthApplicationInstallEndpoint.as_view(),
        name="application-install",
    ),
    path(
        "workspaces/<str:slug>/app-installations/<uuid:pk>/",
        OAuthAppInstallationDetailEndpoint.as_view(),
        name="app-installation-detail",
    ),
    path(
        "workspaces/<str:slug>/my-app-installations/<uuid:pk>/",
        OAuthUserAppInstallationDetailEndpoint.as_view(),
        name="my-app-installation-detail",
    ),
    path(
        "workspaces/<str:slug>/applications/<uuid:pk>/publish/",
        OAuthApplicationPublishEndpoint.as_view(),
        name="application-publish",
    ),
    path(
        "applications/<str:client_id>/",
        OAuthApplicationClientIdEndpoint.as_view(),
        name="application-client-id",
    ),
    path(
        "application-categories/",
        OAuthApplicationCategoryEndpoint.as_view(),
        name="application-categories",
    ),
    path(
        "workspaces/<str:slug>/published-applications/<str:app_slug>/",
        OAuthPublishedApplicationBySlugEndpoint.as_view(),
        name="published-application-by-slug",
    ),
    path(
        "workspaces-check-app-installation-allowed/<uuid:application_id>/",
        OAuthWorkspacesCheckAppInstallationAllowedEndpoint.as_view(),
        name="workspaces-check-app-installation-allowed",
    ),
]
