# Django imports
from django.urls import path

# Module imports
from plane.ee.views.app.teamspace import (
    TeamspaceEndpoint,
    TeamspaceEntitiesEndpoint,
    TeamspaceMembersEndpoint,
    TeamspaceViewEndpoint,
    TeamspaceCycleEndpoint,
    TeamspacePageEndpoint,
    TeamspacePageArchiveEndpoint,
    TeamspacePageUnarchiveEndpoint,
    TeamspacePagesDescriptionEndpoint,
    TeamspacePageLockEndpoint,
    TeamspacePageFavoriteEndpoint,
    TeamspacePageVersionEndpoint,
    TeamspaceIssueEndpoint,
    TeamspaceUserPropertiesEndpoint,
    TeamspaceActivityEndpoint,
    TeamspaceCommentEndpoint,
    TeamspaceCommentReactionEndpoint,
    TeamspaceProgressChartEndpoint,
    TeamspaceRelationEndpoint,
    TeamspaceStatisticsEndpoint,
    TeamspacePageDuplicateEndpoint,
    TeamspaceProgressSummaryEndpoint,
    AddTeamspaceProjectEndpoint,
    TeamspaceSubPageEndpoint,
    TeamspaceParentPageEndpoint,
    TeamspacePageSummaryEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/teamspaces/", TeamspaceEndpoint.as_view(), name="teams"
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/",
        TeamspaceEndpoint.as_view(),
        name="teams",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/entities/",
        TeamspaceEntitiesEndpoint.as_view(),
        name="teamspace-entities",
    ),
    path(
        "workspaces/<str:slug>/teamspace-members/",
        TeamspaceMembersEndpoint.as_view(),
        name="workspace-teamspace-members",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/members/",
        TeamspaceMembersEndpoint.as_view(),
        name="teamspace-members",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/members/<uuid:pk>/",
        TeamspaceMembersEndpoint.as_view(),
        name="teamspace-members",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/views/",
        TeamspaceViewEndpoint.as_view(),
        name="teamspace-views",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/views/<uuid:pk>/",
        TeamspaceViewEndpoint.as_view(),
        name="teamspace-views",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/cycles/",
        TeamspaceCycleEndpoint.as_view(),
        name="teamspace-cycle",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/",
        TeamspacePageEndpoint.as_view(),
        name="teamspace-pages",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages-summary/",
        TeamspacePageSummaryEndpoint.as_view(),
        name="teamspace-pages-summary",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/",
        TeamspacePageEndpoint.as_view(),
        name="teamspace-pages",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:page_id>/sub-pages/",
        TeamspaceSubPageEndpoint.as_view(),
        name="project-sub-pages",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:page_id>/parent-pages/",
        TeamspaceParentPageEndpoint.as_view(),
        name="project-parent-pages",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/duplicate/",
        TeamspacePageDuplicateEndpoint.as_view(),
        name="teamspace-page-duplicate",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/archive/",
        TeamspacePageArchiveEndpoint.as_view(),
        name="teamspace-pages-archive",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/unarchive/",
        TeamspacePageUnarchiveEndpoint.as_view(),
        name="teamspace-pages-unarchive",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/description/",
        TeamspacePagesDescriptionEndpoint.as_view(),
        name="teamspace-pages-description",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/lock/",
        TeamspacePageLockEndpoint.as_view(),
        name="teamspace-pages-lock",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:pk>/favorite/",
        TeamspacePageFavoriteEndpoint.as_view(),
        name="teamspace-pages-favorite",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:page_id>/versions/",
        TeamspacePageVersionEndpoint.as_view(),
        name="teamspace-pages-versions",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/pages/<uuid:page_id>/versions/<uuid:pk>/",
        TeamspacePageVersionEndpoint.as_view(),
        name="teamspace-pages-versions",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/issues/",
        TeamspaceIssueEndpoint.as_view(),
        name="teamspace-issues",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/user-properties/",
        TeamspaceUserPropertiesEndpoint.as_view(),
        name="teamspace-issues-user-properties",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/history/",
        TeamspaceActivityEndpoint.as_view(),
        name="teamspace-activities",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/comments/",
        TeamspaceCommentEndpoint.as_view(),
        name="teamspace-space-comments",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/comments/<uuid:pk>/",
        TeamspaceCommentEndpoint.as_view(),
        name="teamspace-space-comments",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/comments/<uuid:comment_id>/reactions/",
        TeamspaceCommentReactionEndpoint.as_view(),
        name="teamspace-space-comments-reactions",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/comments/<uuid:comment_id>/reactions/<str:reaction_code>/",
        TeamspaceCommentReactionEndpoint.as_view(),
        name="teamspace-space-comments-reactions",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/progress-chart/",
        TeamspaceProgressChartEndpoint.as_view(),
        name="teamspace-progress-chart",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/relations/",
        TeamspaceRelationEndpoint.as_view(),
        name="teamspace-dependencies",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/progress-summary/",
        TeamspaceProgressSummaryEndpoint.as_view(),
        name="teamspace-progress-summary",
    ),
    path(
        "workspaces/<str:slug>/teamspaces/<uuid:team_space_id>/statistics/",
        TeamspaceStatisticsEndpoint.as_view(),
        name="teamspace-statistics",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/teamspaces/",
        AddTeamspaceProjectEndpoint.as_view(),
        name="teamspace-projects",
    ),
]
