from django.urls import path

from plane.app.views.looper import (
    LooperConnectionCollectionEndpoint,
    LooperConnectionCompleteEndpoint,
    LooperConnectionDetailEndpoint,
    LooperConnectionExchangeEndpoint,
    LooperConnectionLinkEndpoint,
    IssueLooperDispatchEndpoint,
    LooperDispatchClaimEndpoint,
    LooperDispatchHandoffEndpoint,
    LooperDispatchInboxEndpoint,
    LooperDispatchOwnerActionEndpoint,
    LooperDispatchTransitionEndpoint,
    LooperNodeSessionEndpoint,
    LooperRoleRequestAnswerEndpoint,
    LooperRoleRequestCreateEndpoint,
    LooperRoleRequestLooperReplyEndpoint,
    LooperRoleRequestMessageEndpoint,
    LooperRoleRequestPendingMessagesEndpoint,
    LooperNodeBindingApprovalEndpoint,
    LooperNodeBindingLinkEndpoint,
    LooperProjectIntegrationEndpoint,
    LooperProjectRolePolicyEndpoint,
    LooperTargetsEndpoint,
)


urlpatterns = [
    path(
        "looper/connections/exchange/",
        LooperConnectionExchangeEndpoint.as_view(),
        name="looper-connection-exchange",
    ),
    path(
        "looper/connections/link/",
        LooperConnectionLinkEndpoint.as_view(),
        name="looper-connection-link",
    ),
    path(
        "looper/connections/complete/",
        LooperConnectionCompleteEndpoint.as_view(),
        name="looper-connection-complete",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/connections/",
        LooperConnectionCollectionEndpoint.as_view(),
        name="looper-connection-create",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/connections/<uuid:connection_id>/",
        LooperConnectionDetailEndpoint.as_view(),
        name="looper-connection-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/nodes/session/",
        LooperNodeSessionEndpoint.as_view(),
        name="looper-node-session",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/work-items/<uuid:issue_id>/looper/dispatch/",
        IssueLooperDispatchEndpoint.as_view(),
        name="looper-dispatch-create",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/inbox/",
        LooperDispatchInboxEndpoint.as_view(),
        name="looper-dispatch-inbox",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/claim/",
        LooperDispatchClaimEndpoint.as_view(),
        name="looper-dispatch-claim",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/transition/",
        LooperDispatchTransitionEndpoint.as_view(),
        name="looper-dispatch-transition",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/handoff/",
        LooperDispatchHandoffEndpoint.as_view(),
        name="looper-dispatch-handoff",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/role-requests/",
        LooperRoleRequestCreateEndpoint.as_view(),
        name="looper-role-request-create",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/role-requests/<uuid:role_request_id>/answer/",
        LooperRoleRequestAnswerEndpoint.as_view(),
        name="looper-role-request-answer",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/role-requests/<uuid:role_request_id>/messages/",
        LooperRoleRequestMessageEndpoint.as_view(),
        name="looper-role-request-message-create",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/role-requests/messages/pending/",
        LooperRoleRequestPendingMessagesEndpoint.as_view(),
        name="looper-role-request-pending-messages",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/role-requests/<uuid:role_request_id>/messages/",
        LooperRoleRequestLooperReplyEndpoint.as_view(),
        name="looper-role-request-looper-reply",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/dispatch/<uuid:dispatch_id>/<str:action>/",
        LooperDispatchOwnerActionEndpoint.as_view(),
        name="looper-dispatch-owner-action",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/bindings/link/",
        LooperNodeBindingLinkEndpoint.as_view(),
        name="looper-binding-link",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/bindings/<uuid:binding_id>/approve/",
        LooperNodeBindingApprovalEndpoint.as_view(),
        name="looper-binding-approve",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/targets/",
        LooperTargetsEndpoint.as_view(),
        name="looper-targets",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/role-policy/",
        LooperProjectRolePolicyEndpoint.as_view(),
        name="looper-role-policy",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/looper/integration/",
        LooperProjectIntegrationEndpoint.as_view(),
        name="looper-project-integration",
    ),
]
