# Generated by Django 4.2.14 on 2024-08-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0002_projectattribute_projectstate_workspacefeature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceLicense",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "recurring_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "current_period_end_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("purchased_seats", models.IntegerField(default=0)),
                ("free_seats", models.IntegerField(default=12)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("PRO", "Pro"),
                            ("ONE", "One"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_offline_payment", models.BooleanField(default=False)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace License",
                "verbose_name_plural": "Workspace Licenses",
                "db_table": "workspace_licenses",
                "ordering": ("-created_at",),
            },
        ),
    ]
