# Generated by Django 4.2.14 on 2024-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0005_workspacelicense_has_activated_free_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacelicense',
            name='subscription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
