# Generated by Django 4.2.16 on 2024-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0009_alter_updatereaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproperty',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyoption',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyoption',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
