# Generated by Django 4.2.18 on 2025-03-12 08:39

from django.db import migrations, models

import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0026_projecttemplate_pagetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='cover_asset',
            field=models.TextField(default=dict),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='intake_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='members',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspaceconnection',
            name='disconnect_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workspacecredential',
            name='source',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='workspaceentityconnection',
            name='type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="entityupdates",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="epic_updates",
                to="db.issue",
            ),
        ),
    ]
