# Generated by Django 4.2.20 on 2025-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0029_workspacecredential_source_authorization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityissuestateactivity',
            name='entity_type',
            field=models.CharField(choices=[('CYCLE', 'Cycle'), ('MODULE', 'Module'), ('PROJECT', 'Project'), ('TEAM', 'Team'), ('EPIC', 'Epic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entityprogress',
            name='entity_type',
            field=models.CharField(choices=[('CYCLE', 'Cycle'), ('MODULE', 'Module'), ('PROJECT', 'Project'), ('TEAM', 'Team'), ('EPIC', 'Epic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entityupdates',
            name='entity_type',
            field=models.CharField(choices=[('CYCLE', 'Cycle'), ('MODULE', 'Module'), ('PROJECT', 'Project'), ('TEAM', 'Team'), ('EPIC', 'Epic')], max_length=30),
        ),
    ]
