# Generated by Django 4.2.20 on 2025-05-07 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_auto_20250425_0902'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0030_alter_entityissuestateactivity_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='template',
            name='categories',
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'db_table': 'template_categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_attachments', to='db.fileasset')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_attachments', to='ee.template')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Template Attachment',
                'verbose_name_plural': 'Template Attachments',
                'db_table': 'template_attachments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='template',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='templates', through='ee.TemplateAttachment', to='db.fileasset'),
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='templates', to='ee.templatecategory'),
        ),
    ]
