# Generated by Django 4.2.21 on 2025-05-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0035_template_contact_email_template_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='website',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
