name: plane
services:
  admin:
    depends_on:
      api:
        condition: service_started
        required: true
      web:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    image: ${PLANE_IMAGE_ADMIN}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  api:
    command:
      - ./bin/docker-entrypoint-api-ee.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      FRONTEND_OTEL_ENABLED: ${FRONTEND_OTEL_ENABLED}
      FRONTEND_OTLP_ENDPOINT: ${FRONTEND_OTLP_ENDPOINT:-}
      FRONTEND_OTLP_HEADERS: ${FRONTEND_OTLP_HEADERS:-}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INSTANCE_ID: ${INSTANCE_ID}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import urllib.request; urllib.request.urlopen('http://localhost:8000/api/ready/', timeout=5)
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/api
        target: /code/plane/logs
        bind:
          create_host_path: true
  automation-consumer:
    command:
      - ./bin/docker-entrypoint-automation-consumer.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AUTOMATION_EVENT_STREAM_PREFETCH: ${AUTOMATION_EVENT_STREAM_PREFETCH}
      AUTOMATION_EVENT_STREAM_QUEUE_NAME: ${AUTOMATION_EVENT_STREAM_QUEUE_NAME}
      AUTOMATION_EXCHANGE_NAME: ${AUTOMATION_EXCHANGE_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  beat-worker:
    command:
      - ./bin/docker-entrypoint-beat.sh
    depends_on:
      api:
        condition: service_started
        required: true
      plane-db:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INSTANCE_ID: ${INSTANCE_ID}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/beat-worker
        target: /code/plane/logs
        bind:
          create_host_path: true
  email:
    deploy:
      replicas: 0
    environment:
      EMAIL_SAVE_ENDPOINT: ${EMAIL_SAVE_ENDPOINT}
      MAX_ATTACHMENT_SIZE: ${MAX_ATTACHMENT_SIZE}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      TLS_CERT_PATH: ${TLS_CERT_PATH:-}
      TLS_PRIV_KEY_PATH: ${TLS_PRIV_KEY_PATH:-}
    healthcheck:
      test:
        - CMD
        - nc
        - -zv
        - localhost
        - "10025"
      timeout: 30s
      interval: 1m30s
      retries: 5
      start_period: 30s
    image: ${PLANE_IMAGE_EMAIL}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/email/tls
        target: /opt/email/tls
        bind:
          create_host_path: true
  iframely:
    deploy:
      replicas: 1
    image: ${PLANE_IMAGE_IFRAMELY}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  importer-worker:
    command:
      - ./bin/docker-entrypoint-worker.sh
      - celery.importer
    depends_on:
      api:
        condition: service_started
        required: true
      plane-db:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/importer-worker
        target: /code/plane/logs
        bind:
          create_host_path: true
  live:
    depends_on:
      api:
        condition: service_started
        required: true
      web:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      API_BASE_URL: ${API_BASE_URL}
      IFRAMELY_URL: ${IFRAMELY_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
    image: ${PLANE_IMAGE_LIVE}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  migrator:
    command:
      - ./bin/docker-entrypoint-migrator.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: "no"
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/migrator
        target: /code/plane/logs
        bind:
          create_host_path: true
  monitor:
    deploy:
      replicas: 1
    environment:
      API_HOSTNAME: ${API_HOSTNAME}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      INSTANCE_ID: ${INSTANCE_ID}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      PRIME_HOST: ${PRIME_HOST}
      SERVICE_HTTP_API: ${SERVICE_HTTP_API}
      SERVICE_HTTP_LIVE: ${SERVICE_HTTP_LIVE}
      SERVICE_HTTP_MINIO: ${SERVICE_HTTP_MINIO}
      SERVICE_HTTP_PROXY: ${SERVICE_HTTP_PROXY}
      SERVICE_HTTP_WEB: ${SERVICE_HTTP_WEB}
      SERVICE_TCP_POSTGRES: ${SERVICE_TCP_POSTGRES}
      SERVICE_TCP_REDIS: ${SERVICE_TCP_REDIS}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
    image: ${PLANE_IMAGE_MONITOR}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/monitor
        target: /app
        bind:
          create_host_path: true
  outbox-poller:
    command:
      - ./bin/docker-entrypoint-outbox-poller.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      OUTBOX_POLLER_BATCH_SIZE: ${OUTBOX_POLLER_BATCH_SIZE}
      OUTBOX_POLLER_INTERVAL_MAX: ${OUTBOX_POLLER_INTERVAL_MAX}
      OUTBOX_POLLER_INTERVAL_MIN: ${OUTBOX_POLLER_INTERVAL_MIN}
      OUTBOX_POLLER_MEMORY_CHECK_INTERVAL: ${OUTBOX_POLLER_MEMORY_CHECK_INTERVAL}
      OUTBOX_POLLER_MEMORY_LIMIT_MB: ${OUTBOX_POLLER_MEMORY_LIMIT_MB}
      OUTBOX_POLLER_POOL_HEALTH_CHECK_INTERVAL: ${OUTBOX_POLLER_POOL_HEALTH_CHECK_INTERVAL}
      OUTBOX_POLLER_POOL_MAX_IDLE: ${OUTBOX_POLLER_POOL_MAX_IDLE}
      OUTBOX_POLLER_POOL_MAX_LIFETIME: ${OUTBOX_POLLER_POOL_MAX_LIFETIME}
      OUTBOX_POLLER_POOL_MAX_SIZE: ${OUTBOX_POLLER_POOL_MAX_SIZE}
      OUTBOX_POLLER_POOL_MIN_SIZE: ${OUTBOX_POLLER_POOL_MIN_SIZE}
      OUTBOX_POLLER_POOL_RECONNECT_TIMEOUT: ${OUTBOX_POLLER_POOL_RECONNECT_TIMEOUT}
      OUTBOX_POLLER_POOL_SIZE: ${OUTBOX_POLLER_POOL_SIZE}
      OUTBOX_POLLER_POOL_TIMEOUT: ${OUTBOX_POLLER_POOL_TIMEOUT}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  pi-api:
    depends_on:
      monitor:
        condition: service_started
        required: true
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BR_AWS_ACCESS_KEY_ID: ${BR_AWS_ACCESS_KEY_ID:-}
      BR_AWS_SECRET_ACCESS_KEY: ${BR_AWS_SECRET_ACCESS_KEY:-}
      BR_AWS_SESSION_TOKEN: ${BR_AWS_SESSION_TOKEN:-}
      BUCKET_NAME: ${BUCKET_NAME}
      CELERY_DOCS_SYNC_ENABLED: ${CELERY_DOCS_SYNC_ENABLED}
      CELERY_DOCS_SYNC_INTERVAL: ${CELERY_DOCS_SYNC_INTERVAL}
      CELERY_VECTOR_SYNC_ENABLED: ${CELERY_VECTOR_SYNC_ENABLED}
      CELERY_VECTOR_SYNC_INTERVAL: ${CELERY_VECTOR_SYNC_INTERVAL}
      CELERY_WORKSPACE_PLAN_SYNC_ENABLED: ${CELERY_WORKSPACE_PLAN_SYNC_ENABLED}
      CELERY_WORKSPACE_PLAN_SYNC_INTERVAL: ${CELERY_WORKSPACE_PLAN_SYNC_INTERVAL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY:-}
      CLAUDE_BASE_URL: ${CLAUDE_BASE_URL:-}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      COHERE_BASE_URL: ${COHERE_BASE_URL:-}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CUSTOM_LLM_API_KEY: ${CUSTOM_LLM_API_KEY:-}
      CUSTOM_LLM_BASE_URL: ${CUSTOM_LLM_BASE_URL:-}
      CUSTOM_LLM_DESCRIPTION: ${CUSTOM_LLM_DESCRIPTION}
      CUSTOM_LLM_ENABLED: ${CUSTOM_LLM_ENABLED}
      CUSTOM_LLM_MAX_TOKENS: ${CUSTOM_LLM_MAX_TOKENS}
      CUSTOM_LLM_MODEL_KEY: ${CUSTOM_LLM_MODEL_KEY}
      CUSTOM_LLM_NAME: ${CUSTOM_LLM_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FASTAPI_APP_HOST: ${FASTAPI_APP_HOST}
      FASTAPI_APP_WORKERS: ${FASTAPI_APP_WORKERS}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GROQ_BASE_URL: ${GROQ_BASE_URL:-}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_API_HOST: ${PLANE_API_HOST}
      PLANE_FRONTEND_URL: ${PLANE_FRONTEND_URL}
      PLANE_OAUTH_REDIRECT_URI: ${PLANE_OAUTH_REDIRECT_URI}
      PLANE_OAUTH_STATE_EXPIRY_SECONDS: ${PLANE_OAUTH_STATE_EXPIRY_SECONDS}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import os,urllib.request; urllib.request.urlopen(f"http://localhost:8000{os.environ.get('PI_BASE_PATH','')}/ready/", timeout=5)
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    image: ${PLANE_IMAGE_PI}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  pi-beat:
    command:
      - ./bin/entrypoint-celery-beat.sh
    depends_on:
      pi-api:
        condition: service_started
        required: true
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BR_AWS_ACCESS_KEY_ID: ${BR_AWS_ACCESS_KEY_ID:-}
      BR_AWS_SECRET_ACCESS_KEY: ${BR_AWS_SECRET_ACCESS_KEY:-}
      BR_AWS_SESSION_TOKEN: ${BR_AWS_SESSION_TOKEN:-}
      BUCKET_NAME: ${BUCKET_NAME}
      CELERY_DOCS_SYNC_ENABLED: ${CELERY_DOCS_SYNC_ENABLED}
      CELERY_DOCS_SYNC_INTERVAL: ${CELERY_DOCS_SYNC_INTERVAL}
      CELERY_VECTOR_SYNC_ENABLED: ${CELERY_VECTOR_SYNC_ENABLED}
      CELERY_VECTOR_SYNC_INTERVAL: ${CELERY_VECTOR_SYNC_INTERVAL}
      CELERY_WORKSPACE_PLAN_SYNC_ENABLED: ${CELERY_WORKSPACE_PLAN_SYNC_ENABLED}
      CELERY_WORKSPACE_PLAN_SYNC_INTERVAL: ${CELERY_WORKSPACE_PLAN_SYNC_INTERVAL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY:-}
      CLAUDE_BASE_URL: ${CLAUDE_BASE_URL:-}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      COHERE_BASE_URL: ${COHERE_BASE_URL:-}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CUSTOM_LLM_API_KEY: ${CUSTOM_LLM_API_KEY:-}
      CUSTOM_LLM_BASE_URL: ${CUSTOM_LLM_BASE_URL:-}
      CUSTOM_LLM_DESCRIPTION: ${CUSTOM_LLM_DESCRIPTION}
      CUSTOM_LLM_ENABLED: ${CUSTOM_LLM_ENABLED}
      CUSTOM_LLM_MAX_TOKENS: ${CUSTOM_LLM_MAX_TOKENS}
      CUSTOM_LLM_MODEL_KEY: ${CUSTOM_LLM_MODEL_KEY}
      CUSTOM_LLM_NAME: ${CUSTOM_LLM_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FASTAPI_APP_HOST: ${FASTAPI_APP_HOST}
      FASTAPI_APP_WORKERS: ${FASTAPI_APP_WORKERS}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GROQ_BASE_URL: ${GROQ_BASE_URL:-}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_API_HOST: ${PLANE_API_HOST}
      PLANE_FRONTEND_URL: ${PLANE_FRONTEND_URL}
      PLANE_OAUTH_REDIRECT_URI: ${PLANE_OAUTH_REDIRECT_URI}
      PLANE_OAUTH_STATE_EXPIRY_SECONDS: ${PLANE_OAUTH_STATE_EXPIRY_SECONDS}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_PI}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  pi-db-init:
    command:
      - /bin/sh
      - -c
      - ' echo "Waiting for plane-db to be ready..."; until pg_isready -h plane-db -U ${POSTGRES_USER}; do sleep 2; done; export PGPASSWORD=${POSTGRES_PASSWORD}; psql -h plane-db -U ${POSTGRES_USER} -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = plane_pi" | grep -q 1 || psql -h plane-db -U ${POSTGRES_USER} -d postgres -c "CREATE DATABASE plane_pi"; echo "Database plane_pi is ready"; exit 0; '
    depends_on:
      plane-db:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      PGDATA: ${PGDATA}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:15.7-alpine
    networks:
      default: null
    restart: "no"
  pi-migrator:
    command:
      - ./bin/entrypoint-migrator.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BR_AWS_ACCESS_KEY_ID: ${BR_AWS_ACCESS_KEY_ID:-}
      BR_AWS_SECRET_ACCESS_KEY: ${BR_AWS_SECRET_ACCESS_KEY:-}
      BR_AWS_SESSION_TOKEN: ${BR_AWS_SESSION_TOKEN:-}
      BUCKET_NAME: ${BUCKET_NAME}
      CELERY_DOCS_SYNC_ENABLED: ${CELERY_DOCS_SYNC_ENABLED}
      CELERY_DOCS_SYNC_INTERVAL: ${CELERY_DOCS_SYNC_INTERVAL}
      CELERY_VECTOR_SYNC_ENABLED: ${CELERY_VECTOR_SYNC_ENABLED}
      CELERY_VECTOR_SYNC_INTERVAL: ${CELERY_VECTOR_SYNC_INTERVAL}
      CELERY_WORKSPACE_PLAN_SYNC_ENABLED: ${CELERY_WORKSPACE_PLAN_SYNC_ENABLED}
      CELERY_WORKSPACE_PLAN_SYNC_INTERVAL: ${CELERY_WORKSPACE_PLAN_SYNC_INTERVAL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY:-}
      CLAUDE_BASE_URL: ${CLAUDE_BASE_URL:-}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      COHERE_BASE_URL: ${COHERE_BASE_URL:-}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CUSTOM_LLM_API_KEY: ${CUSTOM_LLM_API_KEY:-}
      CUSTOM_LLM_BASE_URL: ${CUSTOM_LLM_BASE_URL:-}
      CUSTOM_LLM_DESCRIPTION: ${CUSTOM_LLM_DESCRIPTION}
      CUSTOM_LLM_ENABLED: ${CUSTOM_LLM_ENABLED}
      CUSTOM_LLM_MAX_TOKENS: ${CUSTOM_LLM_MAX_TOKENS}
      CUSTOM_LLM_MODEL_KEY: ${CUSTOM_LLM_MODEL_KEY}
      CUSTOM_LLM_NAME: ${CUSTOM_LLM_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FASTAPI_APP_HOST: ${FASTAPI_APP_HOST}
      FASTAPI_APP_WORKERS: ${FASTAPI_APP_WORKERS}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GROQ_BASE_URL: ${GROQ_BASE_URL:-}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_API_HOST: ${PLANE_API_HOST}
      PLANE_FRONTEND_URL: ${PLANE_FRONTEND_URL}
      PLANE_OAUTH_REDIRECT_URI: ${PLANE_OAUTH_REDIRECT_URI}
      PLANE_OAUTH_STATE_EXPIRY_SECONDS: ${PLANE_OAUTH_STATE_EXPIRY_SECONDS}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_PI}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: "no"
  pi-worker:
    command:
      - ./bin/entrypoint-celery-worker.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 0
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BR_AWS_ACCESS_KEY_ID: ${BR_AWS_ACCESS_KEY_ID:-}
      BR_AWS_SECRET_ACCESS_KEY: ${BR_AWS_SECRET_ACCESS_KEY:-}
      BR_AWS_SESSION_TOKEN: ${BR_AWS_SESSION_TOKEN:-}
      BUCKET_NAME: ${BUCKET_NAME}
      CELERY_DOCS_SYNC_ENABLED: ${CELERY_DOCS_SYNC_ENABLED}
      CELERY_DOCS_SYNC_INTERVAL: ${CELERY_DOCS_SYNC_INTERVAL}
      CELERY_VECTOR_SYNC_ENABLED: ${CELERY_VECTOR_SYNC_ENABLED}
      CELERY_VECTOR_SYNC_INTERVAL: ${CELERY_VECTOR_SYNC_INTERVAL}
      CELERY_WORKSPACE_PLAN_SYNC_ENABLED: ${CELERY_WORKSPACE_PLAN_SYNC_ENABLED}
      CELERY_WORKSPACE_PLAN_SYNC_INTERVAL: ${CELERY_WORKSPACE_PLAN_SYNC_INTERVAL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY:-}
      CLAUDE_BASE_URL: ${CLAUDE_BASE_URL:-}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      COHERE_BASE_URL: ${COHERE_BASE_URL:-}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CUSTOM_LLM_API_KEY: ${CUSTOM_LLM_API_KEY:-}
      CUSTOM_LLM_BASE_URL: ${CUSTOM_LLM_BASE_URL:-}
      CUSTOM_LLM_DESCRIPTION: ${CUSTOM_LLM_DESCRIPTION}
      CUSTOM_LLM_ENABLED: ${CUSTOM_LLM_ENABLED}
      CUSTOM_LLM_MAX_TOKENS: ${CUSTOM_LLM_MAX_TOKENS}
      CUSTOM_LLM_MODEL_KEY: ${CUSTOM_LLM_MODEL_KEY}
      CUSTOM_LLM_NAME: ${CUSTOM_LLM_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FASTAPI_APP_HOST: ${FASTAPI_APP_HOST}
      FASTAPI_APP_WORKERS: ${FASTAPI_APP_WORKERS}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GROQ_BASE_URL: ${GROQ_BASE_URL:-}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_API_HOST: ${PLANE_API_HOST}
      PLANE_FRONTEND_URL: ${PLANE_FRONTEND_URL}
      PLANE_OAUTH_REDIRECT_URI: ${PLANE_OAUTH_REDIRECT_URI}
      PLANE_OAUTH_STATE_EXPIRY_SECONDS: ${PLANE_OAUTH_STATE_EXPIRY_SECONDS}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_PI}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  plane-db:
    command:
      - postgres
      - -c
      - max_connections=1000
    deploy:
      replicas: 1
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      PGDATA: ${PGDATA}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:15.7-alpine
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/db
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
  plane-minio:
    command:
      - server
      - /export
      - --console-address
      - :9090
    deploy:
      replicas: 1
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
    image: minio/minio:latest
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/minio/uploads
        target: /export
        bind:
          create_host_path: true
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/minio/data
        target: /data
        bind:
          create_host_path: true
  plane-mq:
    deploy:
      replicas: 1
    environment:
      AMQP_URL: ${AMQP_URL}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    image: rabbitmq:3.13.6-management-alpine
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/mq
        target: /var/lib/rabbitmq
        bind:
          create_host_path: true
  plane-redis:
    deploy:
      replicas: 1
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
    image: valkey/valkey:7.2.11-alpine
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/data/redis
        target: /data
        bind:
          create_host_path: true
  proxy:
    depends_on:
      admin:
        condition: service_started
        required: true
      api:
        condition: service_started
        required: true
      live:
        condition: service_started
        required: true
      space:
        condition: service_started
        required: true
      web:
        condition: service_started
        required: true
    environment:
      BUCKET_NAME: ${BUCKET_NAME}
      CERT_ACME_CA: ${CERT_ACME_CA}
      CERT_ACME_DNS: ${CERT_ACME_DNS:-}
      CERT_EMAIL: ${CERT_EMAIL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      LISTEN_HTTP_PORT: ${LISTEN_HTTP_PORT}
      LISTEN_HTTPS_PORT: ${LISTEN_HTTPS_PORT}
      LISTEN_SMTP_PORT_25: ${LISTEN_SMTP_PORT_25}
      LISTEN_SMTP_PORT_465: ${LISTEN_SMTP_PORT_465}
      LISTEN_SMTP_PORT_587: ${LISTEN_SMTP_PORT_587}
      SITE_ADDRESS: ${SITE_ADDRESS}
    image: ${PLANE_IMAGE_PROXY}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    ports:
      - mode: host
        target: 80
        published: "8080"
        host_ip: 127.0.0.1
        protocol: tcp

      - mode: host
        target: 443
        published: "8443"
        host_ip: 127.0.0.1
        protocol: tcp

      - mode: host
        target: 10025
        published: "10025"
        protocol: tcp

      - mode: host
        target: 10465
        published: "10465"
        protocol: tcp

      - mode: host
        target: 10587
        published: "10587"
        protocol: tcp

    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/caddy/config
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/caddy/data
        target: /data
        bind:
          create_host_path: true
  silo:
    depends_on:
      plane-mq:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      APP_BASE_URL: ${APP_BASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BATCH_SIZE: ${BATCH_SIZE}
      BUCKET_NAME: ${BUCKET_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DEDUP_INTERVAL: ${DEDUP_INTERVAL}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GITHUB_APP_ID: ${GITHUB_APP_ID:-}
      GITHUB_APP_NAME: ${GITHUB_APP_NAME:-}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY:-}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID:-}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET:-}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MQ_PREFETCH_COUNT: ${MQ_PREFETCH_COUNT}
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
      PGDATA: ${PGDATA}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SILO_API_BASE_URL: ${SILO_API_BASE_URL}
      SILO_BASE_PATH: ${SILO_BASE_PATH}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SLACK_BASE_URL: ${SLACK_BASE_URL}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID:-}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET:-}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    image: ${PLANE_IMAGE_SILO}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  space:
    depends_on:
      api:
        condition: service_started
        required: true
      web:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      OTEL_ENABLED: ${OTEL_ENABLED}
      OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
    image: ${PLANE_IMAGE_SPACE}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  web:
    depends_on:
      api:
        condition: service_started
        required: true
      worker:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    image: ${PLANE_IMAGE_FRONTEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
  webhook-consumer:
    command:
      - ./bin/docker-entrypoint-webhook-consumer.sh
    depends_on:
      plane-db:
        condition: service_started
        required: true
      plane-mq:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
      WEBHOOK_PREFETCH_COUNT: ${WEBHOOK_PREFETCH_COUNT}
      WEBHOOK_QUEUE_NAME: ${WEBHOOK_QUEUE_NAME}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/webhook-consumer
        target: /code/plane/logs
        bind:
          create_host_path: true
  worker:
    command:
      - ./bin/docker-entrypoint-worker.sh
    depends_on:
      api:
        condition: service_started
        required: true
      plane-db:
        condition: service_started
        required: true
      plane-redis:
        condition: service_started
        required: true
    deploy:
      replicas: 1
    environment:
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      AMQP_URL: ${AMQP_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_VERSION: ${APP_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
      ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
      FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      INSTANCE_ID: ${INSTANCE_ID}
      INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
      IS_AIRGAPPED: ${IS_AIRGAPPED}
      IS_SELF_MANAGED: ${IS_SELF_MANAGED}
      LIVE_BASE_PATH: ${LIVE_BASE_PATH}
      LIVE_BASE_URL: ${LIVE_BASE_URL}
      LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
      MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
      MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
      OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
      OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
      PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
      PGDATA: ${PGDATA}
      PI_BASE_PATH: ${PI_BASE_PATH}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
      PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRIME_HOST: ${PRIME_HOST}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
      SSL_VERIFY: ${SSL_VERIFY}
      USE_MINIO: ${USE_MINIO}
      USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
      WEB_URL: ${WEB_URL}
      WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
      WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
    image: ${PLANE_IMAGE_BACKEND}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PLANE_DATA_DIR:-/opt/plane}/logs/worker
        target: /code/plane/logs
        bind:
          create_host_path: true
  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REPO_USER: ${DOCKERHUB_USERNAME}
      REPO_PASS: ${DOCKERHUB_TOKEN}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: ${WATCHTOWER_POLL_INTERVAL:-300}
    networks:
      default: null
networks:
  default:
    name: plane_default
x-app-env:
  AES_SECRET_KEY: ${AES_SECRET_KEY}
  API_BASE_URL: ${API_BASE_URL}
  API_KEY_RATE_LIMIT: ${API_KEY_RATE_LIMIT}
  CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
  DEBUG: ${DEBUG}
  ENABLE_DRF_SPECTACULAR: ${ENABLE_DRF_SPECTACULAR}
  FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
  FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
  GUNICORN_WORKERS: ${GUNICORN_WORKERS}
  INTAKE_EMAIL_DOMAIN: ${INTAKE_EMAIL_DOMAIN}
  IS_SELF_MANAGED: ${IS_SELF_MANAGED}
  LIVE_BASE_PATH: ${LIVE_BASE_PATH}
  LIVE_BASE_URL: ${LIVE_BASE_URL}
  LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
  MINIO_ENDPOINT_SSL: ${MINIO_ENDPOINT_SSL}
  PAYMENT_SERVER_BASE_URL: ${PAYMENT_SERVER_BASE_URL}
  PI_BASE_PATH: ${PI_BASE_PATH}
  PI_BASE_URL: ${PI_BASE_URL}
  PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
  SECRET_KEY: ${SECRET_KEY}
  SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
  SSL_VERIFY: ${SSL_VERIFY}
  WEB_URL: ${WEB_URL}
  WEBHOOK_ALLOWED_HOSTS: ${WEBHOOK_ALLOWED_HOSTS:-}
  WEBHOOK_ALLOWED_IPS: ${WEBHOOK_ALLOWED_IPS:-}
x-automation-consumer-env:
  AUTOMATION_EVENT_STREAM_PREFETCH: ${AUTOMATION_EVENT_STREAM_PREFETCH}
  AUTOMATION_EVENT_STREAM_QUEUE_NAME: ${AUTOMATION_EVENT_STREAM_QUEUE_NAME}
  AUTOMATION_EXCHANGE_NAME: ${AUTOMATION_EXCHANGE_NAME}
x-docstore-env:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_REGION: ${AWS_REGION}
  AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
  AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  BUCKET_NAME: ${BUCKET_NAME}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  USE_MINIO: ${USE_MINIO}
  USE_STORAGE_PROXY: ${USE_STORAGE_PROXY}
x-email-env:
  EMAIL_SAVE_ENDPOINT: ${EMAIL_SAVE_ENDPOINT}
  MAX_ATTACHMENT_SIZE: ${MAX_ATTACHMENT_SIZE}
  SMTP_DOMAIN: ${SMTP_DOMAIN}
  TLS_CERT_PATH: ${TLS_CERT_PATH:-}
  TLS_PRIV_KEY_PATH: ${TLS_PRIV_KEY_PATH:-}
x-live-env:
  API_BASE_URL: ${API_BASE_URL}
  IFRAMELY_URL: ${IFRAMELY_URL}
  LIVE_SERVER_SECRET_KEY: ${LIVE_SERVER_SECRET_KEY}
x-monitor-env:
  API_HOSTNAME: ${API_HOSTNAME}
  SERVICE_HTTP_API: ${SERVICE_HTTP_API}
  SERVICE_HTTP_LIVE: ${SERVICE_HTTP_LIVE}
  SERVICE_HTTP_MINIO: ${SERVICE_HTTP_MINIO}
  SERVICE_HTTP_PROXY: ${SERVICE_HTTP_PROXY}
  SERVICE_HTTP_WEB: ${SERVICE_HTTP_WEB}
  SERVICE_TCP_POSTGRES: ${SERVICE_TCP_POSTGRES}
  SERVICE_TCP_REDIS: ${SERVICE_TCP_REDIS}
  TRUSTED_PROXIES: ${TRUSTED_PROXIES}
x-opensearch-env:
  OPENSEARCH_ENABLED: ${OPENSEARCH_ENABLED}
  OPENSEARCH_INDEX_PREFIX: ${OPENSEARCH_INDEX_PREFIX:-}
  OPENSEARCH_ML_MODEL_ID: ${OPENSEARCH_ML_MODEL_ID:-}
  OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD:-}
  OPENSEARCH_URL: ${OPENSEARCH_URL:-}
  OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME:-}
x-otel-env:
  OTEL_ENABLED: ${OTEL_ENABLED}
  OTEL_ENVIRONMENT: ${OTEL_ENVIRONMENT:-}
  OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
  OTLP_ENDPOINT: ${OTLP_ENDPOINT:-}
x-outbox-poller-env:
  OUTBOX_POLLER_BATCH_SIZE: ${OUTBOX_POLLER_BATCH_SIZE}
  OUTBOX_POLLER_INTERVAL_MAX: ${OUTBOX_POLLER_INTERVAL_MAX}
  OUTBOX_POLLER_INTERVAL_MIN: ${OUTBOX_POLLER_INTERVAL_MIN}
  OUTBOX_POLLER_MEMORY_CHECK_INTERVAL: ${OUTBOX_POLLER_MEMORY_CHECK_INTERVAL}
  OUTBOX_POLLER_MEMORY_LIMIT_MB: ${OUTBOX_POLLER_MEMORY_LIMIT_MB}
  OUTBOX_POLLER_POOL_HEALTH_CHECK_INTERVAL: ${OUTBOX_POLLER_POOL_HEALTH_CHECK_INTERVAL}
  OUTBOX_POLLER_POOL_MAX_IDLE: ${OUTBOX_POLLER_POOL_MAX_IDLE}
  OUTBOX_POLLER_POOL_MAX_LIFETIME: ${OUTBOX_POLLER_POOL_MAX_LIFETIME}
  OUTBOX_POLLER_POOL_MAX_SIZE: ${OUTBOX_POLLER_POOL_MAX_SIZE}
  OUTBOX_POLLER_POOL_MIN_SIZE: ${OUTBOX_POLLER_POOL_MIN_SIZE}
  OUTBOX_POLLER_POOL_RECONNECT_TIMEOUT: ${OUTBOX_POLLER_POOL_RECONNECT_TIMEOUT}
  OUTBOX_POLLER_POOL_SIZE: ${OUTBOX_POLLER_POOL_SIZE}
  OUTBOX_POLLER_POOL_TIMEOUT: ${OUTBOX_POLLER_POOL_TIMEOUT}
x-pg-env:
  DATABASE_URL: ${DATABASE_URL}
  FOLLOWER_POSTGRES_URI: ${FOLLOWER_POSTGRES_URI}
  PGDATA: ${PGDATA}
  PLANE_PI_DATABASE_URL: ${PLANE_PI_DATABASE_URL}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
x-pi-env:
  BR_AWS_ACCESS_KEY_ID: ${BR_AWS_ACCESS_KEY_ID:-}
  BR_AWS_SECRET_ACCESS_KEY: ${BR_AWS_SECRET_ACCESS_KEY:-}
  BR_AWS_SESSION_TOKEN: ${BR_AWS_SESSION_TOKEN:-}
  CELERY_DOCS_SYNC_ENABLED: ${CELERY_DOCS_SYNC_ENABLED}
  CELERY_DOCS_SYNC_INTERVAL: ${CELERY_DOCS_SYNC_INTERVAL}
  CELERY_VECTOR_SYNC_ENABLED: ${CELERY_VECTOR_SYNC_ENABLED}
  CELERY_VECTOR_SYNC_INTERVAL: ${CELERY_VECTOR_SYNC_INTERVAL}
  CELERY_WORKSPACE_PLAN_SYNC_ENABLED: ${CELERY_WORKSPACE_PLAN_SYNC_ENABLED}
  CELERY_WORKSPACE_PLAN_SYNC_INTERVAL: ${CELERY_WORKSPACE_PLAN_SYNC_INTERVAL}
  CLAUDE_API_KEY: ${CLAUDE_API_KEY:-}
  CLAUDE_BASE_URL: ${CLAUDE_BASE_URL:-}
  COHERE_API_KEY: ${COHERE_API_KEY:-}
  COHERE_BASE_URL: ${COHERE_BASE_URL:-}
  CUSTOM_LLM_API_KEY: ${CUSTOM_LLM_API_KEY:-}
  CUSTOM_LLM_BASE_URL: ${CUSTOM_LLM_BASE_URL:-}
  CUSTOM_LLM_DESCRIPTION: ${CUSTOM_LLM_DESCRIPTION}
  CUSTOM_LLM_ENABLED: ${CUSTOM_LLM_ENABLED}
  CUSTOM_LLM_MAX_TOKENS: ${CUSTOM_LLM_MAX_TOKENS}
  CUSTOM_LLM_MODEL_KEY: ${CUSTOM_LLM_MODEL_KEY}
  CUSTOM_LLM_NAME: ${CUSTOM_LLM_NAME}
  EMBEDDING_MODEL: ${EMBEDDING_MODEL:-}
  FASTAPI_APP_HOST: ${FASTAPI_APP_HOST}
  FASTAPI_APP_WORKERS: ${FASTAPI_APP_WORKERS}
  GROQ_API_KEY: ${GROQ_API_KEY:-}
  GROQ_BASE_URL: ${GROQ_BASE_URL:-}
  OPENAI_API_KEY: ${OPENAI_API_KEY:-}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
  PI_BASE_PATH: ${PI_BASE_PATH}
  PI_INTERNAL_SECRET: ${PI_INTERNAL_SECRET}
  PLANE_API_HOST: ${PLANE_API_HOST}
  PLANE_FRONTEND_URL: ${PLANE_FRONTEND_URL}
  PLANE_OAUTH_REDIRECT_URI: ${PLANE_OAUTH_REDIRECT_URI}
  PLANE_OAUTH_STATE_EXPIRY_SECONDS: ${PLANE_OAUTH_STATE_EXPIRY_SECONDS}
x-plane:
  APP_DOMAIN: ${APP_DOMAIN}
  APP_VERSION: ${APP_VERSION}
  DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
  IS_AIRGAPPED: ${IS_AIRGAPPED}
  MACHINE_SIGNATURE: ${MACHINE_SIGNATURE}
  PRIME_HOST: ${PRIME_HOST}
x-proxy-env:
  BUCKET_NAME: ${BUCKET_NAME}
  CERT_ACME_CA: ${CERT_ACME_CA}
  CERT_ACME_DNS: ${CERT_ACME_DNS:-}
  CERT_EMAIL: ${CERT_EMAIL}
  FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
  LISTEN_HTTP_PORT: ${LISTEN_HTTP_PORT}
  LISTEN_HTTPS_PORT: ${LISTEN_HTTPS_PORT}
  LISTEN_SMTP_PORT_25: ${LISTEN_SMTP_PORT_25}
  LISTEN_SMTP_PORT_465: ${LISTEN_SMTP_PORT_465}
  LISTEN_SMTP_PORT_587: ${LISTEN_SMTP_PORT_587}
  SITE_ADDRESS: ${SITE_ADDRESS}
x-rabbitmq-env:
  AMQP_URL: ${AMQP_URL}
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
  RABBITMQ_HOST: ${RABBITMQ_HOST}
  RABBITMQ_PORT: ${RABBITMQ_PORT}
  RABBITMQ_VHOST: ${RABBITMQ_VHOST}
x-redis-env:
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  REDIS_URL: ${REDIS_URL}
x-silo-env:
  AES_SECRET_KEY: ${AES_SECRET_KEY}
  API_BASE_URL: ${API_BASE_URL}
  APP_BASE_URL: ${APP_BASE_URL}
  BATCH_SIZE: ${BATCH_SIZE}
  DEDUP_INTERVAL: ${DEDUP_INTERVAL}
  FEATURE_FLAG_SERVER_BASE_URL: ${FEATURE_FLAG_SERVER_BASE_URL}
  GITHUB_APP_ID: ${GITHUB_APP_ID:-}
  GITHUB_APP_NAME: ${GITHUB_APP_NAME:-}
  GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
  GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
  GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY:-}
  GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID:-}
  GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET:-}
  IS_SELF_MANAGED: ${IS_SELF_MANAGED}
  MQ_PREFETCH_COUNT: ${MQ_PREFETCH_COUNT}
  PORT: ${PORT}
  SILO_API_BASE_URL: ${SILO_API_BASE_URL}
  SILO_BASE_PATH: ${SILO_BASE_PATH}
  SILO_HMAC_SECRET_KEY: ${SILO_HMAC_SECRET_KEY}
  SLACK_BASE_URL: ${SLACK_BASE_URL}
  SLACK_CLIENT_ID: ${SLACK_CLIENT_ID:-}
  SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET:-}
  WEBHOOK_SECRET: ${WEBHOOK_SECRET}
x-webhook-consumer-env:
  WEBHOOK_PREFETCH_COUNT: ${WEBHOOK_PREFETCH_COUNT}
  WEBHOOK_QUEUE_NAME: ${WEBHOOK_QUEUE_NAME}