# pnpm workspace configuration for the Plane monorepo
# After adding this file, run `pnpm install` at the repo root to generate pnpm-lock.yaml

packages:
  - "apps/*"
  - "packages/*"
  # Exclude non-Node subprojects
  - "!apps/api"
  - "!apps/proxy"

catalog:
  sharp: "0.33.5"
  turbo: "^2.5.6"
  typescript: "5.6.3"

# Allow selected dependency build scripts during install (pnpm v10)
onlyBuiltDependencies:
  - turbo
  - sharp

# Pin runtime Node.js version for workspace
useNodeVersion: 22.18.0
