packages:
- apps/*
- packages/*
- "!apps/api"
- "!apps/proxy"

catalog:
  "@atlaskit/pragmatic-drag-and-drop-auto-scroll": 1.4.0
  "@atlaskit/pragmatic-drag-and-drop-hitbox": 1.1.0
  "@atlaskit/pragmatic-drag-and-drop": 1.7.4
  "@bprogress/core": ^1.3.4
  "@dotenvx/dotenvx": 1.51.1
  "@react-router/dev": 7.9.5
  "@react-router/node": 7.9.5
  "@react-router/serve": 7.9.5
  "@sentry/node": 10.27.0
  "@sentry/profiling-node": 10.27.0
  "@sentry/react-router": 10.27.0
  "@tiptap/core": ^2.22.3
  "@tiptap/html": ^2.22.3
  "@types/lodash-es": 4.17.12
  "@types/node": 22.12.0
  "@types/react-dom": 18.3.1
  "@types/react": 18.3.11
  axios: 1.12.0
  express: 4.22.0
  lodash-es: 4.17.23
  lucide-react: 0.469.0
  mobx-react: 9.1.1
  mobx-utils: 6.0.8
  mobx: 6.12.0
  react-dom: 18.3.1
  react-router: 7.12.0
  react: 18.3.1
  swr: 2.2.4
  tsdown: 0.16.0
  typescript: 5.8.3
  uuid: 13.0.0
  vite: 7.1.11

onlyBuiltDependencies:
- turbo
