packages:
  - apps/*
  - packages/*
  - "!apps/api"
  - "!apps/proxy"

catalog:
  "@types/compression": 1.8.1
  "@types/cors": 2.8.19
  "@types/express-ws": 3.0.5
  "@types/express": 4.17.21
  "@types/lodash": 4.17.20
  "@types/node": 24.3.0
  "@types/nprogress": 0.2.3
  "@types/pino-http": 5.8.4
  "@types/react-color": 3.0.13
  "@types/react-dom": 19.1.8
  "@types/react": 19.1.12
  "@types/ws": 8.18.1
  axios: 1.11.0
  lodash: 4.17.21
  lucide-react: 0.469.0
  mobx-react: 9.1.1
  mobx-utils: 6.0.8
  mobx: 6.12.0
  next: 14.2.32
  react-dom: 18.3.1
  react: 18.3.1
  sharp: 0.33.5
  swr: 2.2.4
  tsdown: 0.14.2
  typescript: 5.8.3
  uuid: 11.1.0

onlyBuiltDependencies:
  - turbo
  - sharp
