packages:
- apps/*
- packages/*
- "!apps/api"
- "!apps/proxy"

catalog:
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.11
  "@types/react-dom": 18.3.1
  typescript: 5.8.3
  tsup: 8.4.0

onlyBuiltDependencies:
- turbo
- sharp
