# Generated by Django 3.2.14 on 2022-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20221216_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_issues_prop',
            field=models.JSONField(null=True),
        ),
    ]
