# Generated by Django 3.2.14 on 2022-12-20 11:29

from django.db import migrations, models
import plane.db.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_user_my_issues_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='default_props',
            field=models.JSONField(default=plane.db.models.project.get_default_props),
        ),
    ]
