# Generated by Django 4.2.3 on 2023-07-23 16:33

from django.db import migrations

def rename_field(apps, schema_editor):
    Model = apps.get_model("db", "IssueActivity")
    updated_activity = []
    for obj in Model.objects.filter(field="assignee"):
        obj.field = "assignees"
        updated_activity.append(obj)

    Model.objects.bulk_update(
        updated_activity, ["field"], batch_size=100
    )
 


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20230720_1505'),
    ]

    operations = [
        migrations.RunPython(rename_field)
    ]
