# Generated by Django 4.2.3 on 2023-08-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_cycle_sort_order_issuecomment_access_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuevote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='issuevote',
            name='vote',
            field=models.IntegerField(choices=[(-1, 'DOWNVOTE'), (1, 'UPVOTE')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='issuevote',
            unique_together={('issue', 'actor', 'vote')},
        ),
    ]
