# Generated by Django 4.2.3 on 2023-08-09 12:15
import random
from django.db import migrations

def random_cycle_order(apps, schema_editor):
    CycleModel = apps.get_model("db", "Cycle")
    updated_cycles = []
    for obj in CycleModel.objects.all():
        obj.sort_order = random.randint(1, 65536)
        updated_cycles.append(obj)
    CycleModel.objects.bulk_update(updated_cycles, ["sort_order"], batch_size=100)

def random_module_order(apps, schema_editor):
    ModuleModel = apps.get_model("db", "Module")
    updated_modules = []
    for obj in ModuleModel.objects.all():
        obj.sort_order = random.randint(1, 65536)
        updated_modules.append(obj)
    ModuleModel.objects.bulk_update(updated_modules, ["sort_order"], batch_size=100)

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_user_display_name_alter_analyticview_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(random_cycle_order),
        migrations.RunPython(random_module_order),
    ]
