# Generated by Django 4.2.3 on 2023-08-09 11:15

from django.db import migrations


def update_user_issue_properties(apps, schema_editor):
    IssuePropertyModel = apps.get_model("db", "IssueProperty")
    updated_issue_properties = []
    for obj in IssuePropertyModel.objects.all():
        obj.properties["start_date"] = True
        updated_issue_properties.append(obj)
    IssuePropertyModel.objects.bulk_update(
        updated_issue_properties, ["properties"], batch_size=100
    )


def workspace_member_properties(apps, schema_editor):
    WorkspaceMemberModel = apps.get_model("db", "WorkspaceMember")
    updated_workspace_members = []
    for obj in WorkspaceMemberModel.objects.all():
        obj.view_props["properties"]["start_date"] = True
        obj.default_props["properties"]["start_date"] = True
        updated_workspace_members.append(obj)

    WorkspaceMemberModel.objects.bulk_update(
        updated_workspace_members, ["view_props", "default_props"], batch_size=100
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0042_alter_analyticview_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(update_user_issue_properties),
        migrations.RunPython(workspace_member_properties),
    ]
