# Generated by Django 4.2.3 on 2023-09-05 10:41
import uuid
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0042_alter_analyticview_created_by_and_more"),
    ]

    operations = [
        migrations.RenameModel("IssueProperty", "IssueDisplayProperty"),
        migrations.AlterModelOptions(
            name="issuedisplayproperty",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Issue Display Property",
                "verbose_name_plural": "Issue Display Properties",
            },
        ),
        migrations.AlterModelTable(
            name="issuedisplayproperty",
            table="issue_display_properties",
        ),
    ]
