# Generated by Django 4.2.3 on 2023-09-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_auto_20230905_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('entity', 'entity'), ('text', 'text'), ('paragraph', 'paragraph'), ('number', 'number'), ('checkbox', 'checkbox'), ('select', 'select'), ('multi_select', 'multi_select'), ('date', 'date'), ('relation', 'relation'), ('files', 'files'), ('email', 'email'), ('url', 'url'), ('datetime', 'datetime'), ('option', 'option')])),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('default_value', models.TextField(blank=True, default='')),
                ('is_shared', models.BooleanField(default=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multi', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.property')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_value', models.TextField(blank=True)),
                ('to_value', models.TextField(blank=True)),
                ('from_value_hash', models.CharField(max_length=255)),
                ('to_value_hash', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('entity_uuid', models.UUIDField()),
                ('s_epoch', models.FloatField()),
                ('a_epoch', models.FloatField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'PropertyTransaction',
                'verbose_name_plural': 'PropertyTransactions',
                'db_table': 'property_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='properties',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_object_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, db_index=True, null=True)),
                ('value_hash', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'text'), (1, 'uuid')])),
                ('entity', models.CharField()),
                ('entity_uuid', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='db.property')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.propertytransaction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'PropertyValue',
                'verbose_name_plural': 'PropertyValues',
                'db_table': 'property_values',
            },
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_transactions', to='db.project'),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='db.property'),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='propertytransaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_transactions', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.project'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='property',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='issue',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='db.property'),
        ),
    ]
