# Generated by Django 4.2.5 on 2023-09-29 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_issueactivity_epoch_workspacemember_issue_props_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueactivity',
            name='epoch',
            field=models.FloatField(null=True),
        ),
    ]
