# Generated by Django 4.2.5 on 2023-10-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.issue


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_issueactivity_epoch_workspacemember_issue_props_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproperty',
            name='properties',
            field=models.JSONField(default=plane.db.models.issue.get_default_properties),
        ),
    ]
