# Generated by Django 4.2.5 on 2023-09-26 10:15

from django.db import migrations


def update_issue_activity(apps, schema_editor):
    IssueActivity = apps.get_model("db", "IssueActivity")
    updated_issue_activity = []
    for obj in IssueActivity.objects.all():
        obj.epoch = int(obj.created_at.timestamp())

        # Set the old and new value to none if it is empty for Priority
        if obj.field == "priority":
            obj.new_value = obj.new_value or "none"
            obj.old_value = obj.old_value or "none"

        #   Change the field name from blocks to blocked_by
        if obj.field == "blocks":
            obj.field = "blocked_by"

        updated_issue_activity.append(obj)
    IssueActivity.objects.bulk_update(
        updated_issue_activity,
        ["epoch", "field", "new_value", "old_value"],
        batch_size=2000,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_auto_20230915_0655'),
    ]

    operations = [
         migrations.RunPython(update_issue_activity),
    ]
