# Generated by Django 4.2.3 on 2023-10-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.api


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_webhook_apitoken_description_apitoken_expired_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='retry_count',
        ),
    ]
