# Generated by Django 4.2.5 on 2023-11-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import random


def random_sort_ordering(apps, schema_editor):
    Label = apps.get_model("db", "Label")

    bulk_labels = []
    for label in Label.objects.all():
        label.sort_order = random.randint(0,65535)
        bulk_labels.append(label)

    Label.objects.bulk_update(bulk_labels, ["sort_order"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0046_alter_analyticview_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="sort_order",
            field=models.FloatField(default=65535),
        ),
        migrations.RunPython(random_sort_ordering)
    ]
