# Generated by Django 4.2.3 on 2023-10-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_apitoken_description_apitoken_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
