# Generated by Django 4.2.3 on 2023-09-21 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_auto_20230919_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuelabel',
            unique_together={('issue', 'label')},
        ),
    ]
