# Generated by Django 4.2.5 on 2023-11-10 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_issuemention_projectmember_is_deactivated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
