# Generated by Django 4.2.3 on 2023-09-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0001_initial'),
        ('db', '0047_alter_analyticview_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='ee.property'),
        ),
        migrations.AddField(
            model_name='issue',
            name='properties',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_object_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
