# Generated by Django 4.2.3 on 2023-09-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.issue


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_auto_20230921_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproperty',
            name='properties',
            field=models.JSONField(default=plane.db.models.issue.get_default_properties),
        ),
    ]
