# Generated by Django 4.2.3 on 2023-10-31 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.api
import plane.db.models.webhook


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_auto_20231030_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(default=plane.db.models.webhook.generate_token, max_length=255),
        ),
    ]
