# Generated by Django 4.2.3 on 2023-09-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_alter_analyticview_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('entity', 'entity'), ('text', 'text'), ('paragraph', 'paragraph'), ('number', 'number'), ('checkbox', 'checkbox'), ('select', 'select'), ('multi_select', 'multi_select'), ('relation', 'relation'), ('file', 'file'), ('email', 'email'), ('url', 'url'), ('datetime', 'datetime'), ('option', 'option')]),
        ),
    ]
