# Generated by Django 4.2.3 on 2023-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_propertytransaction_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='extra_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
