# Generated by Django 4.2.5 on 2023-11-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_issuemention_remove_projectmember_is_deactivated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='is_deactivated',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='is_deactivated',
        ),
    ]
