# Generated by Django 4.2.5 on 2023-11-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_auto_20231116_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='organization_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
