# Generated by Django 4.2.3 on 2023-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_alter_property_color_alter_property_extra_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='default_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
