# Generated by Django 4.2.3 on 2023-10-19 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.webhook


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_webhook_alter_analyticview_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(validators=[plane.db.models.webhook.validate_schema, plane.db.models.webhook.validate_domain]),
        ),
    ]
