# Generated by Django 4.2.7 on 2023-12-28 13:08

from django.db import migrations


def project_emoji(apps, schema_editor):
    Project = apps.get_model("db", "Project")

    bulk_project_emoji = []
    for project in Project.objects.all():
        if project.emoji:
            emoji_hex = hex(int(project.emoji))[2:]
            project.emoji = emoji_hex
            bulk_project_emoji.append(project)

    Project.objects.bulk_update(bulk_project_emoji, ["emoji"], batch_size=1000)


def issue_reaction(apps, schema_editor):
    IssueReaction = apps.get_model("db", "IssueReaction")

    bulk_issue_reaction = []
    for issue in IssueReaction.objects.all():
        if issue.reaction:
            emoji_hex = hex(int(issue.reaction))[2:]
            issue.reaction = emoji_hex
            bulk_issue_reaction.append(issue)

    IssueReaction.objects.bulk_update(
        bulk_issue_reaction, ["reaction"], batch_size=1000
    )


def comment_reaction(apps, schema_editor):
    CommentReaction = apps.get_model("db", "CommentReaction")

    bulk_comment_reaction = []
    for comment in CommentReaction.objects.all():
        if comment.reaction:
            emoji_hex = hex(int(comment.reaction))[2:]
            comment.reaction = emoji_hex
            bulk_comment_reaction.append(comment)

    CommentReaction.objects.bulk_update(
        bulk_comment_reaction, ["reaction"], batch_size=1000
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0050_user_use_case_alter_workspace_organization_size"),
    ]

    operations = [
        migrations.RunPython(project_emoji),
        migrations.RunPython(issue_reaction),
        migrations.RunPython(comment_reaction),
    ]
