# Generated by Django 4.2.7 on 2023-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_user_use_case_alter_workspace_organization_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelog',
            name='entity_name',
            field=models.CharField(choices=[('to_do', 'To Do'), ('issue', 'issue'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('link', 'Link'), ('cycle', 'Cycle'), ('project', 'Project'), ('module', 'Module'), ('back_link', 'Back Link'), ('forward_link', 'Forward Link'), ('page_mention', 'Page Mention'), ('user_mention', 'User Mention')], max_length=30, verbose_name='Transaction Type'),
        ),
    ]
