# Generated by Django 4.2.7 on 2023-12-20 14:33

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_user_use_case_alter_workspace_organization_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='estimatepoint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
    ]
