# Generated by Django 4.2.7 on 2023-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_user_use_case_alter_workspace_organization_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
