# Generated by Django 4.2.7 on 2023-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0051_cycle_external_id_cycle_external_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='imported_data',
            field=models.JSONField(default=dict),
        ),
    ]
