# Generated by Django 4.2.7 on 2023-11-27 15:17

from django.db import migrations


def user_password_autoset(apps, schema_editor):
    User = apps.get_model("db", "User")
    User.objects.update(is_password_autoset=True)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_alter_workspace_slug'),
    ]

    operations = [
         migrations.RunPython(user_password_autoset),
    ]
