# Generated by Django 4.2.7 on 2024-01-11 07:57

from django.db import migrations


def add_creators_assignee_subscribers(apps, schema_editor):
    bulk_issue_subscribers = []
    IssueAssignee = apps.get_model("db", "IssueAssignee")
    IssueSubscriber = apps.get_model("db", "IssueSubscriber")
    Issue = apps.get_model("db", "Issue")

    for assignee in IssueAssignee.objects.values(
        "issue_id", "assignee_id", "project_id", "workspace_id"
    ):
        bulk_issue_subscribers.append(
            IssueSubscriber(
                subscriber_id=assignee.get("assignee_id"),
                issue_id=assignee.get("issue_id"),
                project_id=assignee.get("project_id"),
                workspace_id=assignee.get("workspace_id"),
                created_by_id=assignee.get("assignee_id"),
            )
        )

    for issue in Issue.objects.values("id", "created_by_id", "project_id", "workspace_id"):
        if issue.get("created_by_id"):
            bulk_issue_subscribers.append(
                IssueSubscriber(
                    subscriber_id=issue.get("created_by_id"),
                    issue_id=issue.get("id"),
                    project_id=issue.get("project_id"),
                    workspace_id=issue.get("workspace_id"),
                    created_by_id=issue.get("created_by_id"),
                )
            )

    IssueSubscriber.objects.bulk_create(bulk_issue_subscribers, batch_size=5000, ignore_conflicts=True)



class Migration(migrations.Migration):
    dependencies = [
        ("db", "0053_auto_20240102_1315"),
    ]

    operations = [
        migrations.RunPython(add_creators_assignee_subscribers)
    ]
