# Generated by Django 4.2.7 on 2024-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20240122_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='transferred_cycle',
            field=models.JSONField(default=dict),
        ),
    ]
