# Generated by Django 4.2.7 on 2024-01-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_project_preferences(apps, schema_editor):
    ProjectFeature = apps.get_model("db", "ProjectFeature")
    Project = apps.get_model("db", "Project")

    ProjectFeature.objects.bulk_create(
        [
            ProjectFeature(
                project_id=project.get("id"),
                workspace_id=project.get("workspace_id"),
                cycles=project.get("cycle_view"),
                modules=project.get("module_view"),
                views=project.get("issue_views_view"),
                pages=project.get("page_view"),
                inbox=project.get("inbox_view"),
            )
            for project in Project.objects.values(
                "id",
                "workspace_id",
                "cycle_view",
                "inbox_view",
                "issue_views_view",
                "page_view",
                "module_view",
            )
        ],
        batch_size=100,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0057_auto_20240122_0901"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("modules", models.BooleanField(default=True)),
                ("cycles", models.BooleanField(default=True)),
                ("views", models.BooleanField(default=True)),
                ("pages", models.BooleanField(default=True)),
                ("inbox", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_features",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Feature",
                "verbose_name_plural": "Project Features",
                "db_table": "project_features",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RunPython(create_project_preferences),
    ]
