# Generated by Django 4.2.7 on 2024-01-31 13:34
import uuid
from django.db import migrations, models
from django.conf import settings
import django.db.models
import plane.db.models.asset


def update_urls(apps, schema_editor):
    # Check if the app is using minio or s3
    if settings.USE_MINIO:
        prefix = (
            f"{settings.AWS_S3_URL_PROTOCOL}//{settings.AWS_S3_CUSTOM_DOMAIN}/"
        )
        prefix2 = prefix
    else:
        prefix = f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_REGION}.amazonaws.com/"
        prefix2 = (
            f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
        )

    User = apps.get_model("db", "User")
    UserAsset = apps.get_model("db", "UserAsset")
    bulk_users = []
    bulk_user_assets = []
    for user in User.objects.all():
        if user.avatar and (
            user.avatar.startswith(prefix) or user.avatar.startswith(prefix2)
        ):
            avatar = user.avatar[len(prefix) :]
            user.avatar = avatar
            bulk_user_assets.append(
                UserAsset(
                    user=user,
                    asset=avatar,
                )
            )

        if user.cover_image and (
            user.cover_image.startswith(prefix)
            or user.cover_image.startswith(prefix2)
        ):
            cover_image = user.cover_image[len(prefix) :]
            user.cover_image = cover_image
            bulk_user_assets.append(
                UserAsset(
                    user=user,
                    asset=cover_image,
                )
            )
    User.objects.bulk_update(
        bulk_users, ["avatar", "cover_image"], batch_size=100
    )
    UserAsset.objects.bulk_create(bulk_user_assets, batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0058_alter_moduleissue_issue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "asset",
                    models.FileField(
                        max_length=500,
                        storage=plane.settings.storage.S3PrivateBucketStorage(),
                        upload_to=plane.db.models.user.get_upload_path,
                        validators=[plane.db.models.user.file_size],
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("size", models.PositiveBigIntegerField(null=True)),
                ("attributes", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Asset",
                "verbose_name_plural": "User Assets",
                "db_table": "user_assets",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="fileasset",
            name="asset",
            field=models.FileField(
                storage=plane.settings.storage.S3PrivateBucketStorage(),
                upload_to=plane.db.models.asset.get_upload_path,
                validators=[plane.db.models.asset.file_size],
            ),
        ),
        migrations.RemoveField(
            model_name="issueactivity",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="issuecomment",
            name="attachments",
        ),
        migrations.AlterField(
            model_name="integration",
            name="avatar_url",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.CharField(blank=True, null=True, verbose_name="Logo"),
        ),
        migrations.RunPython(update_urls),
    ]
