# Generated by Django 4.2.7 on 2024-02-02 07:23

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

# Third party imports
from bs4 import BeautifulSoup


def convert_image_sources(apps, schema_editor):

    if settings.USE_MINIO:
        prefix1 = (
            f"{settings.AWS_S3_URL_PROTOCOL}//{settings.AWS_S3_CUSTOM_DOMAIN}/"
        )
        prefix2 = prefix1
    else:
        prefix1 = f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.{settings.AWS_REGION}.amazonaws.com/"
        prefix2 = (
            f"https://{settings.AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
        )

    Issue = apps.get_model("db", "Issue")

    bulk_issues = []

    for issue in Issue.objects.all():
        # Parse the html
        soup = BeautifulSoup(issue.description_html, "lxml")
        img_tags = soup.find_all("img")
        for img in img_tags:
            src = img.get("src", "")
            if src and (src.startswith(prefix1)):
                img["src"] = (
                    f"/api/workspaces/{issue.workspace.slug}/projects/{issue.project_id}/issues/{issue.id}/attachments/{src[len(prefix1): ]}"
                )
                issue.description_html = str(soup)
                bulk_issues.append(issue)

            # prefix 2
            if (
                not settings.USE_MINIO
                and src
                and src.startswith(prefix2)
            ):
                img["src"] = (
                    f"/api/workspaces/{issue.workspace.slug}/projects/{issue.project_id}/issues/{issue.id}/attachments/{src[len(prefix2): ]}"
                )
                issue.description_html = str(soup)
                bulk_issues.append(issue)

    Issue.objects.bulk_update(bulk_issues, ["description_html"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0059_auto_20240131_1334"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="fileasset",
        #     name="entity_identifier",
        #     field=models.UUIDField(null=True),
        # ),
        # migrations.AddField(
        #     model_name="fileasset",
        #     name="entity_type",
        #     field=models.CharField(
        #         choices=[
        #             ("issue", "Issue"),
        #             ("comment", "Comment"),
        #             ("page", "Page"),
        #         ],
        #         null=True,
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="fileasset",
        #     name="project_id",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="assets",
        #         to="db.project",
        #     ),
        # ),
        migrations.RunPython(convert_image_sources),
    ]
