# Generated by Django 4.2.7 on 2024-02-05 06:42

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ("db", "0060_fileasset_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueattachment",
            name="asset_key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_assets",
                to="db.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="issueattachment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Attachment"), (1, "Description")], default=0
            ),
        ),
    ]
