# Generated by Django 4.2.7 on 2024-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0060_cycle_progress_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialloginconnection",
            name="medium",
            field=models.CharField(
                choices=[
                    ("Google", "google"),
                    ("Github", "github"),
                    ("Jira", "jira"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
