# Generated by Django 4.2.7 on 2024-01-30 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F

def views_owned_by(apps, schema_editor):
    View = apps.get_model("db", "View")
    View.objects.update(owned_by=F('created_by'))

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_cycle_progress_snapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueView',
            new_name='View',
        ),
        migrations.AlterModelTable(
            name='view',
            table='views',
        ),
        migrations.RenameModel(
            old_name='IssueViewFavorite',
            new_name='ViewFavorite',
        ),
        migrations.AlterField(
            model_name='viewfavorite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterModelTable(
            name='workspaceuserproperties',
            table='workspace_user_properties',
        ),
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('-created_at',), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AddField(
            model_name='view',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='view',
            name='access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Shared')], default=1),
        ),
        migrations.AlterField(
            model_name='viewfavorite',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_favorites', to='db.view'),
        ),
        migrations.RunPython(views_owned_by)
    ]
