# Generated by Django 4.2.10 on 2024-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0061_remove_user_billing_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_data",
                    models.TextField(verbose_name="session data"),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        db_index=True, verbose_name="expire date"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "db_table": "sessions",
                "abstract": False,
            },
        ),
    ]
