# Generated by Django 4.2.10 on 2024-04-02 11:44

from django.db import migrations, models
import plane.db.models.page


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0062_cycle_archived_at_module_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="view_props",
            field=models.JSONField(
                default=plane.db.models.page.get_view_props
            ),
        ),
    ]
