# Generated by Django 4.2.11 on 2024-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_auto_20240415_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description_binary',
            field=models.BinaryField(null=True),
        ),
    ]
