# Generated by Django 4.2.11 on 2024-04-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_auto_20240415_0937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuelabel',
            unique_together={('issue', 'label')},
        ),
    ]
