# Generated by Django 4.2.7 on 2024-05-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_account_id_token_cycle_logo_props_module_logo_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_estimate', to='db.estimate'),
        ),
    ]
