# Generated by Django 4.2.7 on 2024-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_issue_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='last_used',
            field=models.BooleanField(default=False),
        ),
    ]
