# Generated by Django 4.2.11 on 2024-06-30 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_issue_types(apps, schema_editor):
    Project = apps.get_model("db", "Project")
    Issue = apps.get_model("db", "Issue")
    IssueType = apps.get_model("db", "IssueType")
    # Create the issue types for all projects
    IssueType.objects.bulk_create(
        [
            IssueType(
                name="Task",
                description="A task that needs to be completed.",
                project_id=project["id"],
                workspace_id=project["workspace_id"],
            )
            for project in Project.objects.values("id", "workspace_id")
        ]
    )
    # Update the issue type for all existing issues
    issue_types = {
        str(issue_type["project_id"]): str(issue_type["id"])
        for issue_type in IssueType.objects.values("id", "project_id")
    }
    # Update the issue type for all existing issues
    bulk_issues = []
    for issue in Issue.objects.all():
        issue.type_id = issue_types[str(issue.project_id)]
        bulk_issues.append(issue)

    # Update the issue type for all existing issues
    Issue.objects.bulk_update(bulk_issues, ["type_id"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0069_alter_account_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("logo_props", models.JSONField(default=dict)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
                "db_table": "issue_types",
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_type",
                to="db.issuetype",
            ),
        ),
        migrations.RunPython(create_issue_types),
    ]
