# Generated by Django 4.2.11 on 2024-06-21 12:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0069_alter_account_provider_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inbox",
            new_name="Intake",
        ),
        migrations.RenameModel(
            old_name="InboxIssue",
            new_name="IntakeIssue",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="inbox_view",
            new_name="intake_view",
        ),
        migrations.RenameField(
            model_name="deployboard",
            old_name="inbox",
            new_name="intake",
        ),
        migrations.RenameField(
            model_name="projectdeployboard",
            old_name="inbox",
            new_name="intake",
        ),
    ]
