# Generated by Django 4.2.11 on 2024-06-25 07:32

from django.db import migrations, models
import django.db.models.deletion


def migrate_current_active(apps, schema_editor):
    ProjectIdentifier = apps.get_model("db", "ProjectIdentifier")

    # Update current_active field with name field
    ProjectIdentifier.objects.update(current_active=models.F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0069_alter_account_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectidentifier",
            name="current_active",
            field=models.CharField(db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="projectidentifier",
            name="name",
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="projectidentifier",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_identifier",
                to="db.project",
            ),
        ),
        migrations.RunPython(migrate_current_active),
    ]
