# Generated by Django 4.2.11 on 2024-08-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0072_issueattachment_external_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="cycleuserproperties",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardwidget",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="deployboard",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="estimate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="inbox",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issueassignee",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuemention",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuereaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuerelation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuesubscriber",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuetype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issueuserproperty",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="issuevote",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="moduleissue",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="modulemember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="moduleuserproperties",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectidentifier",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectpage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectpublicmember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teampage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userfavorite",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workspacememberinvite",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workspacetheme",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuserproperties",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="analyticview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="apiactivitylog",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="cycle",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="cyclefavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="cycleissue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="cycleuserproperties",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="deployboard",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="emailnotificationlog",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="estimatepoint",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="exporterhistory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="githubcommentsync",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="githubissuesync",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="githubrepositorysync",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="globalview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="importer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="inboxissue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueactivity",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueassignee",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueattachment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueblocker",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuelabel",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuemention",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuereaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuerelation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuesequence",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuesubscriber",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuetype",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueuserproperty",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issueviewfavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="issuevote",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="modulefavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="moduleissue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="modulelink",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="modulemember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="moduleuserproperties",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="pagefavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="pagelabel",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="pagelog",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectdeployboard",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectfavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectidentifier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectmemberinvite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="projectpublicmember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="slackprojectsync",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="socialloginconnection",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="teampage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="userrecentvisit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspaceintegration",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspacememberinvite",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspacetheme",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="workspaceuserproperties",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together={("comment", "actor", "reaction", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="cycleuserproperties",
            unique_together={("cycle", "user", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="dashboardwidget",
            unique_together={("widget", "dashboard", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="deployboard",
            unique_together={
                ("entity_name", "entity_identifier", "deleted_at")
            },
        ),
        migrations.AlterUniqueTogether(
            name="estimate",
            unique_together={("name", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="inbox",
            unique_together={("name", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issueassignee",
            unique_together={("issue", "assignee", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuemention",
            unique_together={("issue", "mention", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuereaction",
            unique_together={("issue", "actor", "reaction", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuerelation",
            unique_together={("issue", "related_issue", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuesubscriber",
            unique_together={("issue", "subscriber", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuetype",
            unique_together={("project", "name", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issueuserproperty",
            unique_together={("user", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="issuevote",
            unique_together={("issue", "actor", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("name", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("name", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="moduleissue",
            unique_together={("issue", "module", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="modulemember",
            unique_together={("module", "member", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="moduleuserproperties",
            unique_together={("module", "user", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={
                ("identifier", "workspace", "deleted_at"),
                ("name", "workspace", "deleted_at"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="projectidentifier",
            unique_together={("name", "workspace", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "member", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="projectpage",
            unique_together={("project", "page", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="projectpublicmember",
            unique_together={("project", "member", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("name", "project", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name", "workspace", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "member", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="teampage",
            unique_together={("team", "page", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="userfavorite",
            unique_together={
                ("entity_type", "user", "entity_identifier", "deleted_at")
            },
        ),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together={("workspace", "member", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="workspacememberinvite",
            unique_together={("email", "workspace", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="workspacetheme",
            unique_together={("workspace", "name", "deleted_at")},
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuserproperties",
            unique_together={("workspace", "user", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="commentreaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("comment", "actor", "reaction"),
                name="comment_reaction_unique_comment_actor_reaction_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="cycleuserproperties",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("cycle", "user"),
                name="cycle_user_properties_unique_cycle_user_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("widget", "dashboard"),
                name="dashboard_widget_unique_widget_dashboard_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="deployboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("entity_name", "entity_identifier"),
                name="deploy_board_unique_entity_name_entity_identifier_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="estimate_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="inbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="inbox_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issueassignee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "assignee"),
                name="issue_assignee_unique_issue_assignee_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuemention",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "mention"),
                name="issue_mention_unique_issue_mention_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "actor", "reaction"),
                name="issue_reaction_unique_issue_actor_reaction_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuerelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "related_issue"),
                name="issue_relation_unique_issue_related_issue_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuesubscriber",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "subscriber"),
                name="issue_subscriber_unique_issue_subscriber_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="issue_type_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issueuserproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "project"),
                name="issue_user_property_unique_user_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuevote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "actor"),
                name="issue_vote_unique_issue_actor_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="label_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="module_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "module"),
                name="module_issue_unique_issue_module_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="modulemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("module", "member"),
                name="module_member_unique_module_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleuserproperties",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("module", "user"),
                name="module_user_properties_unique_module_user_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("identifier", "workspace"),
                name="project_unique_identifier_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "workspace"),
                name="project_unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "workspace"),
                name="unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "member"),
                name="project_member_unique_project_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "page"),
                name="project_page_unique_project_page_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectpublicmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "member"),
                name="project_public_member_unique_project_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="state_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "workspace"),
                name="team_unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("team", "member"),
                name="team_member_unique_team_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="teampage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("team", "page"),
                name="team_page_unique_team_page_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfavorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("entity_type", "entity_identifier", "user"),
                name="user_favorite_unique_entity_type_entity_identifier_user_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "member"),
                name="workspace_member_unique_workspace_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacememberinvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("email", "workspace"),
                name="workspace_member_invite_unique_email_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacetheme",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "name"),
                name="workspace_theme_unique_workspace_name_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspaceuserproperties",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "user"),
                name="workspace_user_properties_unique_workspace_user_when_deleted_at_null",
            ),
        ),
    ]
