# Generated by Django 4.2.11 on 2024-09-23 11:45

from django.db import migrations


def move_attachment_to_fileasset(apps, schema_editor):
    FileAsset = apps.get_model("db", "FileAsset")
    IssueAttachment = apps.get_model("db", "IssueAttachment")

    bulk_issue_attachment = []
    for issue_attachment in IssueAttachment.objects.values(
        "issue_id",
        "project_id",
        "workspace_id",
        "asset",
        "attributes",
        "external_source",
        "external_id",
        "deleted_at",
    ):
        bulk_issue_attachment.append(
            FileAsset(
                entity_identifier=issue_attachment["issue_id"],
                entity_type="ISSUE_ATTACHMENT",
                project_id=issue_attachment["project_id"],
                workspace_id=issue_attachment["workspace_id"],
                attributes=issue_attachment["attributes"],
                asset=issue_attachment["asset"],
                external_source=issue_attachment["external_source"],
                external_id=issue_attachment["external_id"],
                deleted_at=issue_attachment["deleted_at"],
            )
        )

    FileAsset.objects.bulk_create(bulk_issue_attachment, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0077_auto_20240902_1540"),
    ]

    operations = [  # This migration is to move all existing IssueAttachment to FileAsset
        migrations.RunPython(
            move_attachment_to_fileasset,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
