# Generated by Django 4.2.11 on 2024-09-27 08:48

from django.db import migrations, models
import plane.db.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0078_auto_20240923_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="asset",
            field=models.FileField(
                max_length=800, upload_to=plane.db.models.asset.get_upload_path
            ),
        ),
    ]
