# Generated by Django 4.2.15 on 2024-10-16 10:56

from django.db import migrations, models


def create_in_app_user_notification_preference(apps, schema_editor):

    UserNotificationPreferences = apps.get_model(
        "db", "UserNotificationPreference"
    )

    UserNotificationPreferences.objects.bulk_create(
        [
            UserNotificationPreferences(
                user_id=user_notification_preference,
                type="IN_APP",
                property_change=True,
                state_change=True,
                comment=True,
                mention=True,
                issue_completed=True,
                priority_change=True,
                assignee_change=True,
                start_target_date_change=True,
                module_change=True,
                cycle_change=True,
                reactions=True,
            )
            for user_notification_preference in UserNotificationPreferences.objects.values_list(
                "user_id", flat=True
            )
        ],
        batch_size=2000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0081_remove_globalview_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployboard",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="assignee_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="cycle_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="module_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="priority_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="reactions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="start_target_date_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("IN_APP", "In App")],
                default="EMAIL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="deployboard",
            name="entity_name",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("issue", "Issue"),
                    ("module", "Module"),
                    ("cycle", "Task"),
                    ("page", "Page"),
                    ("view", "View"),
                    ("inbox", "Inbox"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="issue_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="mention",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="property_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="state_change",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_in_app_user_notification_preference),
    ]
