# Generated by Django 4.2.15 on 2024-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0082_alter_issue_managers_alter_cycleissue_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('ISSUE_ATTACHMENT', 'Issue Attachment'), ('ISSUE_DESCRIPTION', 'Issue Description'), ('COMMENT_DESCRIPTION', 'Comment Description'), ('PAGE_DESCRIPTION', 'Page Description'), ('USER_COVER', 'User Cover'), ('USER_AVATAR', 'User Avatar'), ('WORKSPACE_LOGO', 'Workspace Logo'), ('PROJECT_COVER', 'Project Cover'), ('DRAFT_ISSUE_ATTACHMENT', 'Draft Issue Attachment'), ('DRAFT_ISSUE_DESCRIPTION', 'Draft Issue Description'), ('PROJECT_LOGO', 'Project Logo')], max_length=255, null=True),
        ),
    ]
