# Generated by Django 4.2.15 on 2024-11-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_remove_label_label_unique_name_project_when_deleted_at_null_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='workspace',
        ),
        migrations.AlterUniqueTogether(
            name='teampage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='page',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
