# Generated by Django 4.2.16 on 2024-11-14 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0085_remove_issuecustomproperty_project_custom_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypeCustomProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_propery_issue_type', to='db.issuetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Issue Type Custom Property',
                'verbose_name_plural': 'Issue Type Custom Properties',
                'db_table': 'isssue_type_custom_properties',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='ProjectCustomProperty',
        ),
        migrations.AddConstraint(
            model_name='issuetypecustomproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_type', 'name'), name='issue_type_custom_property_unique_type_name_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuetypecustomproperty',
            unique_together={('issue_type', 'name', 'deleted_at')},
        ),
    ]
