# Generated by Django 4.2.16 on 2024-11-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_issuetypecustomproperty_delete_projectcustomproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecustomproperty',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_issue_type', to='db.issuetype'),
        ),
        migrations.AlterField(
            model_name='issuecustomproperty',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
