# Generated by Django 4.2.15 on 2024-12-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0087_remove_issueversion_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelog",
            name="entity_name",
            field=models.CharField(max_length=30, verbose_name="Transaction Type"),
        ),
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together={("workspace", "url", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "url"),
                name="webhook_url_unique_url_when_deleted_at_null",
            ),
        ),
    ]
