# Generated by Django 4.2.17 on 2025-01-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_workspacehomepreference_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard',
            new_name='DeprecatedDashboard',
        ),
        migrations.RenameModel(
            old_name='DashboardWidget',
            new_name='DeprecatedDashboardWidget',
        ),
        migrations.RenameModel(
            old_name='Widget',
            new_name='DeprecatedWidget',
        ),
        migrations.AlterModelOptions(
            name='deprecateddashboard',
            options={'ordering': ('-created_at',), 'verbose_name': 'DeprecatedDashboard', 'verbose_name_plural': 'DeprecatedDashboards'},
        ),
        migrations.AlterModelOptions(
            name='deprecateddashboardwidget',
            options={'ordering': ('-created_at',), 'verbose_name': 'Deprecated Dashboard Widget', 'verbose_name_plural': 'Deprecated Dashboard Widgets'},
        ),
        migrations.AlterModelOptions(
            name='deprecatedwidget',
            options={'ordering': ('-created_at',), 'verbose_name': 'DeprecatedWidget', 'verbose_name_plural': 'DeprecatedWidgets'},
        ),
        migrations.AlterField(
            model_name='workspacehomepreference',
            name='sort_order',
            field=models.FloatField(default=65535),
        ),
        migrations.AlterModelTable(
            name='deprecateddashboard',
            table='deprecated_dashboards',
        ),
        migrations.AlterModelTable(
            name='deprecateddashboardwidget',
            table='deprecated_dashboard_widgets',
        ),
        migrations.AlterModelTable(
            name='deprecatedwidget',
            table='deprecated_widgets',
        ),
    ]
