# Generated by Django 4.2.16 on 2024-11-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_rename_issue_type_issuecustomproperty_issue_type_custom_proerty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuecustomproperty',
            old_name='issue_type_custom_proerty',
            new_name='issue_type_custom_property',
        ),
    ]
