# Generated by Django 4.2.17 on 2025-02-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_issuecomment_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deprecateddashboardwidget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deprecateddashboardwidget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deprecateddashboardwidget',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='deprecateddashboardwidget',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='deprecateddashboardwidget',
            name='widget',
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DeprecatedDashboard',
        ),
        migrations.DeleteModel(
            name='DeprecatedDashboardWidget',
        ),
        migrations.DeleteModel(
            name='DeprecatedWidget',
        ),
    ]
