# Generated by Django 4.2.14 on 2025-04-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_issue_customer_code_issue_hub_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='hub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='worker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
