# Generated by Django 4.2.17 on 2025-03-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0092_alter_deprecateddashboardwidget_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="moved_to_page",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="moved_to_project",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="sub_pages_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="EntityDescriptionVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(max_length=255, verbose_name="Entity Name"),
                ),
                ("entity_identifier", models.UUIDField(null=True)),
                (
                    "last_saved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description_binary", models.BinaryField(null=True)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                ("description_stripped", models.TextField(blank=True, null=True)),
                ("description_json", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_description_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Description Version",
                "verbose_name_plural": "Entity Description Versions",
                "db_table": "entity_description_versions",
                "ordering": ("-created_at",),
            },
        ),
    ]
