# Generated by Django 4.2.17 on 2025-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0092_alter_deprecateddashboardwidget_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="moved_to_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moved_page",
                to="db.page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="moved_to_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moved_project",
                to="db.project",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="sub_pages_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
