# Generated by Django 4.2.20 on 2025-04-07 07:44

from django.db import migrations

from plane.db.models import Issue, IssueLabel

def clear_label_project(apps, schema_editor):
    Label = apps.get_model('db', 'Label')
    for label in Label.objects.all():
        existing = Label.objects.filter(name=label.name, project_id=None).first()
        if existing is None:
            label.project = None
            label.save()
        else:
            ### Need to move all the current's label issues to existing one.
            for issue_to_move in Issue.objects.filter(labels__id=label.id).all():
                issue_to_move.labels.remove(label.id)
                l_connection = IssueLabel.objects.create(
                    issue=issue_to_move,
                    label_id=existing.id,
                    workspace=issue_to_move.workspace,
                    project=issue_to_move.project,
                )
                issue_to_move.save()
                l_connection.save()
            
            #label.project = None
            label.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0092_alter_deprecateddashboardwidget_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_label_project, reverse_code=migrations.RunPython.noop),
    ]
