# Generated by Django 4.2.17 on 2025-03-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0092_alter_deprecateddashboardwidget_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="moved_to_page",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="moved_to_project",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="sub_pages_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
