# Generated by Django 4.2.14 on 2025-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_issuecustomproperty_bool_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetypecustomproperty',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]