# Generated by Django 4.2.20 on 2025-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_page_moved_to_page_page_moved_to_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_name_when_project_null_and_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_project_name_when_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='unique_project_name_when_not_deleted'),
        ),
    ]
