# Generated by Django 4.2.20 on 2025-04-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_manage_label_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_name_when_project_null_and_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_project_name_when_not_deleted',
        ),
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
    ]
