# Generated by Django 4.2.17 on 2025-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_auto_20250425_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_of_the_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
    ]
