# Generated by Django 4.2.14 on 2025-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_issuetypecustomproperty_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecustomproperty',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
    ]