# Generated by Django 4.2.14 on 2025-04-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0095_issuecustomproperty_date_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetypecustomproperty',
            name='data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
