# Generated by Django 4.2.20 on 2025-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0095_page_external_id_page_external_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="masked_at",
            field=models.DateTimeField(null=True),
        ),
    ]
