# Generated by Django 4.2.14 on 2025-04-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_issuetypecustomproperty_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
