# Generated by Django 4.2.14 on 2025-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_issue_source_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecustomproperty',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecustomproperty',
            name='data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuecustomproperty',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecustomproperty',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuetypecustomproperty',
            name='data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
