# Generated by Django 4.2.14 on 2025-06-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_issuecustomproperty_bool_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
