# Generated by Django 4.2.14 on 2025-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0099_issue_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hub_codes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]

