# Generated by Django 4.2.14 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0100_add_user_hub_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hub_names",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_super_admin",
            field=models.BooleanField(default=False),
        ),
    ]
