# Generated by Django 4.2.14 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0102_add_user_employee_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="scoped_issue_access",
            field=models.BooleanField(default=True),
        ),
    ]
