# Generated by Django 4.2.14 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False  # Required for CREATE INDEX CONCURRENTLY

    dependencies = [
        ("db", "0103_add_workspace_scoped_issue_access"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY idx_issues_workspace_hub 
                ON issues(workspace_id, hub_code, hub_name) 
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_issues_workspace_hub;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY idx_issues_project_hub 
                ON issues(project_id, hub_code, hub_name) 
                WHERE deleted_at IS NULL;
            """,
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_issues_project_hub;",
        ),
    ]
