# Generated by Django 4.2.14 on 2025-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0104_add_issue_hub_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
