# Generated by Django migration for protected states feature

from django.db import migrations


def protect_critical_states(apps, _schema_editor):
    State = apps.get_model("db", "State")

    # Mark all default states as protected: Backlog, Todo, In Progress, Done, and Cancelled
    State.objects.filter(
        name__in=["Backlog", "Todo", "In Progress", "Done", "Cancelled"],
        deleted_at__isnull=True,
    ).update(is_protected=True)


def reverse_protect_critical_states(apps, _schema_editor):
    State = apps.get_model("db", "State")

    # Unmark protected states (reverse operation)
    State.objects.filter(
        name__in=["Backlog", "Todo", "In Progress", "Done", "Cancelled"],
        deleted_at__isnull=True,
    ).update(is_protected=False)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0106_add_is_protected_to_state"),
    ]

    operations = [
        migrations.RunPython(
            protect_critical_states,
            reverse_code=reverse_protect_critical_states,
        ),
    ]
