export enum E_FEATURE_FLAGS {
  BULK_OPS = "BULK_OPS",
  BULK_OPS_ADVANCED = "BULK_OPS_ADVANCED",
  COLLABORATION_CURSOR = "COLLABORATION_CURSOR",
  EDITOR_AI_OPS = "EDITOR_AI_OPS",
  ESTIMATE_WITH_TIME = "ESTIMATE_WITH_TIME",
  ISSUE_TYPE_DISPLAY = "ISSUE_TYPE_DISPLAY",
  ISSUE_TYPE_SETTINGS = "ISSUE_TYPE_SETTINGS",
  OIDC_SAML_AUTH = "OIDC_SAML_AUTH",
  PAGE_ISSUE_EMBEDS = "PAGE_ISSUE_EMBEDS",
  PAGE_PUBLISH = "PAGE_PUBLISH",
  VIEW_ACCESS_PRIVATE = "VIEW_ACCESS_PRIVATE",
  VIEW_LOCK = "VIEW_LOCK",
  VIEW_PUBLISH = "VIEW_PUBLISH",
  WORKSPACE_ACTIVE_CYCLES = "WORKSPACE_ACTIVE_CYCLES",
  WORKSPACE_PAGES = "WORKSPACE_PAGES",
  ISSUE_WORKLOG = "ISSUE_WORKLOG",
  PROJECT_GROUPING = "PROJECT_GROUPING",
  ACTIVE_CYCLE_PRO = "ACTIVE_CYCLE_PRO",
  NO_LOAD = "NO_LOAD",
  FILE_SIZE_LIMIT_PRO = "FILE_SIZE_LIMIT_PRO",
  TIMELINE_DEPENDENCY = "TIMELINE_DEPENDENCY",

  // ====== silo importers ======
  SILO_IMPORTERS = "SILO_IMPORTERS",

  JIRA_IMPORTER = "JIRA_IMPORTER",
  JIRA_ISSUE_TYPES_IMPORTER = "JIRA_ISSUE_TYPES_IMPORTER",

  JIRA_SERVER_IMPORTER = "JIRA_SERVER_IMPORTER",
  JIRA_SERVER_ISSUE_TYPES_IMPORTER = "JIRA_SERVER_ISSUE_TYPES_IMPORTER",

  LINEAR_IMPORTER = "LINEAR_IMPORTER",
  LINEAR_TEAMS_IMPORTER = "LINEAR_TEAMS_IMPORTER",

  ASANA_IMPORTER = "ASANA_IMPORTER",
  ASANA_ISSUE_PROPERTIES_IMPORTER = "ASANA_ISSUE_PROPERTIES_IMPORTER",

  // ====== silo integrations ======
  SILO_INTEGRATIONS = "SILO_INTEGRATIONS",
  GITHUB_INTEGRATION = "GITHUB_INTEGRATION",

  GITLAB_INTEGRATION = "GITLAB_INTEGRATION",
  SLACK_INTEGRATION = "SLACK_INTEGRATION",

  // ====== silo deprecated ======
  SILO_JIRA_INTEGRATION = "SILO_JIRA_INTEGRATION", // DEPRECATED
  SILO_LINEAR_INTEGRATION = "SILO_LINEAR_INTEGRATION", // DEPRECATED
  SILO_INTEGRATION = "SILO_INTEGRATION", // DEPRECATED

  // intake
  INTAKE_SETTINGS = "INTAKE_SETTINGS",
  // PI
  PI_CHAT = "PI_CHAT",
  PI_DEDUPE = "PI_DEDUPE",
}

export type TFeatureFlags = keyof typeof E_FEATURE_FLAGS;
