# Generated by Django 3.2.14 on 2022-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_auto_20221114_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Cycle Status",
            ),
        ),
    ]
