# Generated by Django 4.2.7 on 2024-01-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0057_auto_20240122_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleissue",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_module",
                to="db.issue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moduleissue",
            unique_together={("issue", "module")},
        ),
    ]
