# Generated by Django 4.2.11 on 2024-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0065_auto_20240415_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="id_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cycle",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="module",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="issueview",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="inbox",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="widget",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_binary",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
    ]
