# Generated by Django 4.2.11 on 2024-08-29 09:40

import django.core.validators
from django.db import migrations, models
import plane.db.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0074_deploy_board_and_project_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="asset",
            field=models.FileField(
                upload_to=plane.db.models.asset.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    plane.db.models.asset.file_size,
                ],
            ),
        ),
    ]
