# Generated by Django 4.2.15 on 2024-10-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0079_auto_20241009_0619"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileasset",
            name="draft_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="db.draftissue",
            ),
        ),
        migrations.AlterField(
            model_name="fileasset",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ISSUE_ATTACHMENT", "Issue Attachment"),
                    ("ISSUE_DESCRIPTION", "Issue Description"),
                    ("COMMENT_DESCRIPTION", "Comment Description"),
                    ("PAGE_DESCRIPTION", "Page Description"),
                    ("USER_COVER", "User Cover"),
                    ("USER_AVATAR", "User Avatar"),
                    ("WORKSPACE_LOGO", "Workspace Logo"),
                    ("PROJECT_COVER", "Project Cover"),
                    ("DRAFT_ISSUE_ATTACHMENT", "Draft Issue Attachment"),
                    ("DRAFT_ISSUE_DESCRIPTION", "Draft Issue Description"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
