# Generated by Django 4.2.17 on 2025-04-25 09:02

from django.db import migrations, models
from plane.db.models.intake import SourceType

def set_default_source_type(apps, schema_editor):
    IntakeIssue = apps.get_model("db", "IntakeIssue")
    IntakeIssue.objects.filter(source__iexact="in-app").update(source=SourceType.IN_APP)

class Migration(migrations.Migration):
    dependencies = [
        ('db', '0093_page_moved_to_page_page_moved_to_project_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_default_source_type,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='profile',
            name='start_of_the_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
    ]
