# Generated by Django 4.2.14 on 2025-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_auto_20250425_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
