# Generated by Django 4.2.21 on 2025-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_project_external_id_project_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_app_rail_docked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issuereaction',
            name='reaction',
            field=models.TextField(),
        ),
    ]
