# Generated by Django 4.2.22 on 2025-07-27 16:01


from django.db import migrations, models
import plane.utils.color


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0098_profile_is_app_rail_docked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_color",
            field=models.CharField(
                default=plane.utils.color.get_random_color, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="goals",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="workspace",
            name="background_color",
            field=models.CharField(
                default=plane.utils.color.get_random_color, max_length=255
            ),
        ),
    ]
