# Generated by Django 4.2.22 on 2025-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_page_sort_order_pagelog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='entity_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='entity_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_identifier',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='entity_identifier',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='entity_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='entity_type',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='entity_identifier',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='entity_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='file_asset_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'read_at'], name='notification_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelog',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='page_log_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelog',
            index=models.Index(fields=['entity_name', 'entity_identifier'], name='page_log_entity_identifier_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='user_favorite_entity_idx'),
        ),
    ]
