# Generated by Django 4.2.22 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_page_sort_order_pagelog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_identifier',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace'], name='receiver_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'read_at'], name='receiver_read_at_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'read_at'], name='receiver_workspace_read_at_idx'),
        ),
    ]
