# Generated by Django 4.2.22 on 2025-09-01 14:33

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('db', '0102_page_sort_order_pagelog_entity_type_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='fileasset',
            index=models.Index(fields=['entity_type'], name='asset_entity_type_idx'),
        ),
        AddIndexConcurrently(
            model_name='fileasset',
            index=models.Index(fields=['entity_identifier'], name='asset_entity_identifier_idx'),
        ),
        AddIndexConcurrently(
            model_name='fileasset',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='asset_entity_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['entity_identifier'], name='notif_entity_identifier_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['entity_name'], name='notif_entity_name_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['read_at'], name='notif_read_at_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['receiver', 'read_at'], name='notif_entity_idx'),
        ),
        AddIndexConcurrently(
            model_name='pagelog',
            index=models.Index(fields=['entity_type'], name='pagelog_entity_type_idx'),
        ),
        AddIndexConcurrently(
            model_name='pagelog',
            index=models.Index(fields=['entity_identifier'], name='pagelog_entity_id_idx'),
        ),
        AddIndexConcurrently(
            model_name='pagelog',
            index=models.Index(fields=['entity_name'], name='pagelog_entity_name_idx'),
        ),
        AddIndexConcurrently(
            model_name='pagelog',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='pagelog_type_id_idx'),
        ),
        AddIndexConcurrently(
            model_name='pagelog',
            index=models.Index(fields=['entity_name', 'entity_identifier'], name='pagelog_name_id_idx'),
        ),
        AddIndexConcurrently(
            model_name='userfavorite',
            index=models.Index(fields=['entity_type'], name='fav_entity_type_idx'),
        ),
        AddIndexConcurrently(
            model_name='userfavorite',
            index=models.Index(fields=['entity_identifier'], name='fav_entity_identifier_idx'),
        ),
        AddIndexConcurrently(
            model_name='userfavorite',
            index=models.Index(fields=['entity_type', 'entity_identifier'], name='fav_entity_idx'),
        ),
    ]
