# Generated by Django 4.2.22 on 2025-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0104_cycleuserproperties_rich_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cycle_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="issue_views_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="module_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="session",
            name="user_id",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
