# Generated by Django 4.2.25 on 2025-11-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactivity',
            name='issue_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_comment', to='db.issuecomment'),
        ),        
        migrations.AlterField(
            model_name='issueactivity',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_activity', to='db.issue'),
        ),
    ]
