# Generated by Django 4.2.22 on 2025-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'read_at', 'created_at'], name='notif_receiver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'entity_name', 'read_at'], name='notif_receiver_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'snoozed_till', 'archived_at'], name='notif_receiver_state_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'sender'], name='notif_receiver_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['workspace', 'entity_identifier', 'entity_name'], name='notif_entity_lookup_idx'),
        ),
    ]
