# Generated by Django 4.2.25 on 2025-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
