# Generated by Django 4.2.22 on 2025-11-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0108_alter_issueactivity_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment_description', to='db.description'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_issue_comment', to='db.issuecomment'),
        ),
    ]
