# Generated by Django 4.2.25 on 2025-12-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0108_issue_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
