# Generated by Django 4.2.25 on 2025-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0108_alter_issueactivity_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
