# Generated by Django 4.2.26 on 2025-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_issuecomment_description_and_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceuserproperties',
            name='navigation_control_preference',
            field=models.CharField(choices=[('ACCORDION', 'Accordion'), ('TABBED', 'Tabbed')], default='ACCORDION', max_length=25),
        ),
        migrations.AddField(
            model_name='workspaceuserproperties',
            name='navigation_project_limit',
            field=models.IntegerField(default=10),
        ),
    ]
