# Generated by Django 4.2.22 on 2025-09-29 15:36

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('db', '0110_workspaceuserproperties_navigation_control_preference_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'read_at', 'created_at'], name='notif_receiver_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'entity_name', 'read_at'], name='notif_receiver_entity_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'snoozed_till', 'archived_at'], name='notif_receiver_state_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['receiver', 'workspace', 'sender'], name='notif_receiver_sender_idx'),
        ),
        AddIndexConcurrently(
            model_name='notification',
            index=models.Index(fields=['workspace', 'entity_identifier', 'entity_name'], name='notif_entity_lookup_idx'),
        ),
        AddIndexConcurrently(
            model_name='fileasset',
            index=models.Index(fields=['asset'], name='asset_asset_idx'),
        ),
    ]
