# Generated by Django 4.2.25 on 2025-11-24 06:03

from django.db import migrations, transaction
from django.db.models import OuterRef, Subquery, Value, CharField
from django.db.models.functions import Concat, Substr, Cast

BATCH_SIZE = 4000


def create_triage_state(apps, _schema_editor):
    Project = apps.get_model("db", "Project")
    State = apps.get_model("db", "State")
    Issue = apps.get_model("db", "Issue")

    projects = list(Project.objects.all().values("id", "workspace_id"))

    # check any state with name "Intake Triage" exists
    for state in State.objects.filter(name="Intake Triage"):
        project_id = str(state.project_id)[:5]
        state.name = f"Intake-Triage-{project_id}"
        state.save()

    # update the group of existing triage states to backlog
    State.objects.filter(group="triage").update(group="backlog")

    states_to_create = []
    for proj in projects:
        states_to_create.append(
            State(
                name="Intake Triage",
                group="triage",
                project_id=proj["id"],
                workspace_id=proj["workspace_id"],
                color="#9AA4BC",
                sequence=65000,
                default=False,
            )
    )

    print(f"Creating {len(states_to_create)} triage states...")

    # Bulk-create states
    State.objects.bulk_create(states_to_create, batch_size=BATCH_SIZE)

    print("Updating issues...")
    
    # Single query using Django ORM with Subquery
    with transaction.atomic():
        # Subquery to get the triage state_id for each issue's project
        triage_state_subquery = State.objects.filter(
            group="triage",
            project_id=OuterRef('project_id'),
            workspace_id=OuterRef('workspace_id'),
        ).values('id')[:1]
        
        # Single UPDATE with subquery - Django generates optimized SQL
        updated_count = Issue._default_manager.filter(
            issue_intake__status__in=[-2, 0]
        ).update(state_id=Subquery(triage_state_subquery))
        
        print(f"Updated {updated_count} issues.")

    print("Done.")



class Migration(migrations.Migration):

    dependencies = [
        ('db', '0111_notification_notif_receiver_status_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_triage_state),
    ]
