# Generated by Django 4.2.27 for FamilyFlow

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0112_auto_20251124_0603"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Household identifier or family name",
                        max_length=200,
                        verbose_name="Family Name",
                    ),
                ),
                (
                    "sprint_duration",
                    models.IntegerField(
                        default=7,
                        help_text="Sprint duration in days (default: 7 for weekly, 14 for bi-weekly)",
                    ),
                ),
                (
                    "default_swim_lanes",
                    models.JSONField(
                        default=["Chores", "School/Activities", "Home Projects", "Family Time", "Individual Goals"],
                        help_text="Default category list for backlog items and sprints",
                    ),
                ),
                (
                    "custom_swim_lanes",
                    models.JSONField(blank=True, default=list, help_text="Custom categories families can add beyond defaults", null=True),
                ),
                (
                    "gamification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable gamification features for children",
                    ),
                ),
                (
                    "baseline_capacity",
                    models.IntegerField(
                        blank=True,
                        default=20,
                        help_text="Baseline sprint capacity in story points (manually configured per family)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
                "db_table": "families",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name in family context (may differ from user's display name)",
                        max_length=200,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        help_text="Age for age-appropriate UI (required for children, optional for adults)",
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("parent", "Parent"), ("child", "Child")],
                        default="parent",
                        help_text="Family role: parent or child",
                        max_length=20,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="Profile picture URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the member joined the family",
                        verbose_name="Joined At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the member is currently active in the family",
                    ),
                ),
                (
                    "use_kid_interface",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Override automatic kid interface assignment (null = auto based on age < 13)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="familymember_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="familymember_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Family this member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="db.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User account linked to this family member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Member",
                "verbose_name_plural": "Family Members",
                "db_table": "family_members",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(fields=["family", "is_active"], name="family_memb_family__idx"),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(fields=["user", "is_active"], name="family_memb_user_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="family",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="family_unique_name_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "family"),
                name="family_member_unique_user_family_when_deleted_at_null",
            ),
        ),
    ]

