# Generated by Django 4.2.26 on 2025-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='version',
            field=models.CharField(default='v1'),
        ),
    ]
