# Generated by Django 4.2.25 on 2025-12-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='description_json',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='description_json',
        ),
    ]
