
# Generated by Django 4.2.22 on 2025-12-15 09:34
from typing import Any


from django.db import migrations, models
from django.db.models import Count, Max


def set_page_sort_order(apps, schema_editor):
    Page = apps.get_model("db", "Page")

    DEFAULT = 65535
    BATCH_SIZE = 3000
    INCREMENT_VALUE = 10000

    ProjectPage = apps.get_model("db", "ProjectPage")

    # move all the parent id sort order to their project page model.
    project_pages = ProjectPage.objects.filter(page__parent_id__isnull=False).select_related("page")
    project_pages_to_update = []
    for project_page in project_pages.iterator(chunk_size=BATCH_SIZE):
        project_page.sort_order = project_page.page.sort_order
        project_pages_to_update.append(project_page)
        if len(project_pages_to_update) >= BATCH_SIZE:
            ProjectPage.objects.bulk_update(project_pages_to_update, ["sort_order"], batch_size=BATCH_SIZE)
            project_pages_to_update = []
    
    # Update remaining items
    if project_pages_to_update:
        ProjectPage.objects.bulk_update(project_pages_to_update, ["sort_order"], batch_size=BATCH_SIZE)

    # Step 1: Find workspaces with duplicate DEFAULT_SORT_ORDER pages
    workspace_ids = (
        Page.objects
        .filter(sort_order=DEFAULT)
        .values("workspace_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
        .values_list("workspace_id", flat=True)
    )

    for workspace_id in workspace_ids.iterator(chunk_size=500):
        # Step 2: get max sort_order in the workspace
        max_sort = (
            Page.objects
            .filter(workspace_id=workspace_id)
            .aggregate(m=Max("sort_order"))["m"] or 0
        )

        # Step 3: fetch duplicate pages
        pages = list[Any](
            Page.objects
            .filter(workspace_id=workspace_id, sort_order=DEFAULT)
            .only("id", "sort_order")
        )


        # Step 4: assign unique increasing sort orders
        next_sort = max_sort + INCREMENT_VALUE
        for page in pages:
            page.sort_order = next_sort
            next_sort += INCREMENT_VALUE

        Page.objects.bulk_update(pages, ["sort_order"], batch_size=BATCH_SIZE)


def reverse_set_page_sort_order(apps, schema_editor):
    ProjectPage = apps.get_model("db", "ProjectPage")
    DEFAULT_SORT_ORDER = 65535
    ProjectPage.objects.update(sort_order=DEFAULT_SORT_ORDER)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='sort_order',
            field=models.FloatField(default=65535),
        ),
        migrations.RunPython(
            set_page_sort_order, reverse_code=reverse_set_page_sort_order
        ),
    ]
