# Generated by Django 4.2.24 on 2025-10-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_alter_caselabel_parent_alter_casemodule_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemodule',
            options={'ordering': ('sort_order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='testcaserepository',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='caselabel',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='caselabel',
            name='external_source',
        ),
        migrations.AlterModelTable(
            name='caselabel',
            table='test_labels',
        ),
        migrations.AlterModelTable(
            name='plancase',
            table='test_plan_cases',
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_case',
        ),
        migrations.AlterModelTable(
            name='testcaserepository',
            table='test_repository',
        ),
    ]
