# Generated by Django 4.2.25 on 2025-12-02 14:16

from django.db import migrations, models
import plane.db.models.workspace


def get_default_feature_tours():
    return {
        "work_items": True,
        "cycles": True,
        "modules": True,
        "intake": True,
        "pages": True,
    }

def populate_feature_tours(apps, _schema_editor):
    WorkspaceUserProperties = apps.get_model('db', 'WorkspaceUserProperties')
    default_value = get_default_feature_tours()
    # Use bulk update for better performance
    WorkspaceUserProperties.objects.all().update(feature_tours=default_value)



class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_navigation_tour_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceuserproperties',
            name='feature_tours',
            field=models.JSONField(default=plane.db.models.workspace.get_default_feature_tours),
        ),
        migrations.RunPython(populate_feature_tours, reverse_code=migrations.RunPython.noop),
    ]