# Generated by Django 4.2.27 on 2026-01-06 07:29

from django.db import migrations, models
import plane.db.models.workspace


def get_default_checklist():
    return {
        "project_created": True,
        "project_joined": True,
        "work_item_created": True,
        "team_members_invited": True,
        "page_created": True,
        "ai_chat_tried": True,
        "integration_linked": True,
        "view_created": True,
        "sticky_created": True,
    }

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_webhook_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=get_default_checklist),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=plane.db.models.workspace.get_default_checklist),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='tips',
            field=models.JSONField(default=plane.db.models.workspace.get_default_tips),
        ),
    ]
