# Generated by Django 4.2.27 for FamilyFlow

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0113_family_familymember"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the backlog item",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Rich text description of the backlog item",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Swim lane category (must exist in family's swim lanes)",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority order (higher number = higher priority, for ordering)",
                    ),
                ),
                (
                    "story_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Effort estimate (1-5 scale, optional in backlog)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("sprint", "Sprint"),
                            ("archived", "Archived"),
                        ],
                        default="backlog",
                        help_text="Current status of the backlog item",
                        max_length=20,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a template for recurring tasks",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlogitem_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlogitem_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Family this backlog item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlog_items",
                        to="db.family",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Family member who created this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_backlog_items",
                        to="db.familymember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backlog Item",
                "verbose_name_plural": "Backlog Items",
                "db_table": "backlog_items",
                "ordering": ("-priority", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="backlogitem",
            index=models.Index(fields=["family", "category"], name="backlog_ite_family__idx"),
        ),
        migrations.AddIndex(
            model_name="backlogitem",
            index=models.Index(fields=["family", "status"], name="backlog_ite_family__status_idx"),
        ),
        migrations.AddIndex(
            model_name="backlogitem",
            index=models.Index(fields=["family", "priority"], name="backlog_ite_family__priority_idx"),
        ),
        migrations.AddIndex(
            model_name="backlogitem",
            index=models.Index(fields=["family", "status", "priority"], name="backlog_ite_family__status_priority_idx"),
        ),
    ]

