# Generated by Django 4.2.27 on 2026-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_webhook_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='explored_features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='tips',
            field=models.JSONField(default=dict),
        ),
    ]
