# Generated by Django 4.2.24 on 2025-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_alter_casemodule_options_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caselabel',
            name='unique_repository_name_when_not_deleted',
        ),
        migrations.RemoveField(
            model_name='caselabel',
            name='parent',
        ),
        migrations.AddConstraint(
            model_name='caselabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('repository__isnull', False)), fields=('repository', 'name'), name='unique_test_label_name_when_not_deleted'),
        ),
    ]
