# Generated by Django 4.2.22 on 2026-01-05 13:28

from django.db import migrations, models

def update_projectpage_sort_order(apps, schema_editor):
    ProjectPage = apps.get_model("db", "ProjectPage")
    Project = apps.get_model("db", "Project")

    for project in Project.objects.all():
        pages = list(
            ProjectPage.objects.filter(project=project).order_by("created_at")
        )

        for index, page in enumerate(pages):
            page.sort_order = index * 10000

        ProjectPage.objects.bulk_update(pages, ["sort_order"], batch_size=3000)

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_webhook_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='sort_order',
            field=models.FloatField(default=65535),
        ),
        migrations.RunPython(update_projectpage_sort_order, reverse_code=migrations.RunPython.noop),
    ]
