# Generated by Django 4.2.25 on 2026-07-17

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0114_project_sport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPlaylist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("clip", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customplaylist_created_by",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customplaylist_updated_by",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Playlist",
                "verbose_name_plural": "Custom Playlists",
                "db_table": "custom_playlists",
                "ordering": ("-created_at",),
            },
        ),
    ]
