# Generated by Django 4.2.27 on 2025-12-13 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.family


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_backlog_item'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backlogitem',
            new_name='backlog_ite_family__9f4406_idx',
            old_name='backlog_ite_family__idx',
        ),
        migrations.RenameIndex(
            model_name='backlogitem',
            new_name='backlog_ite_family__59158d_idx',
            old_name='backlog_ite_family__status_idx',
        ),
        migrations.RenameIndex(
            model_name='backlogitem',
            new_name='backlog_ite_family__6a41a1_idx',
            old_name='backlog_ite_family__priority_idx',
        ),
        migrations.RenameIndex(
            model_name='backlogitem',
            new_name='backlog_ite_family__72f4d7_idx',
            old_name='backlog_ite_family__status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='familymember',
            new_name='family_memb_family__9cfc12_idx',
            old_name='family_memb_family__idx',
        ),
        migrations.RenameIndex(
            model_name='familymember',
            new_name='family_memb_user_id_66e60f_idx',
            old_name='family_memb_user_id_idx',
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority order (higher number = higher priority, for ordering)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='story_points',
            field=models.IntegerField(blank=True, help_text='Effort estimate (1-5 scale, optional in backlog)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='family',
            name='baseline_capacity',
            field=models.IntegerField(blank=True, default=20, help_text='Baseline sprint capacity in story points (manually configured per family)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='family',
            name='default_swim_lanes',
            field=models.JSONField(default=plane.db.models.family.get_default_swim_lanes, help_text='Default category list for backlog items and sprints'),
        ),
        migrations.AlterField(
            model_name='family',
            name='sprint_duration',
            field=models.IntegerField(default=7, help_text='Sprint duration in days (default: 7 for weekly, 14 for bi-weekly)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age for age-appropriate UI (required for children, optional for adults)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
    ]
