# Generated by Django 4.2.25 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0115_customplaylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customplaylist",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="customplaylist",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
