# Generated by Django 4.2.22 on 2026-01-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_auto_20260105_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftissue',
            old_name='description',
            new_name='description_json',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='description_json',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='description_json',
        ),
    ]
