# Generated by Django 4.2.24 on 2025-11-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_remove_caselabel_color_remove_caselabel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='state',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='TestPlan State'),
        ),
    ]
