# Generated by Django 4.2.25 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0116_alter_customplaylist_url_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customplaylist",
            name="event_id",
        ),
        migrations.AddField(
            model_name="customplaylist",
            name="event_id",
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
