# Generated by Django 4.2.24 on 2025-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0117_remove_testplan_unique_plane_repository_name_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='cases', to='db.issue'),
        ),
    ]
