# Generated by Django 4.2.28 on 2026-02-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0119_alter_estimatepoint_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('config', models.JSONField(default=dict, help_text='Dashboard config: {project_ids: [], layout: {}, filters: {}}')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_analytics_dashboards', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboards',
                'db_table': 'analytics_dashboards',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('widget_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('donut', 'Donut Chart'), ('pie', 'Pie Chart'), ('number', 'Number Widget')], default='bar', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('chart_property', models.CharField(help_text='X-axis property: priority, state, assignee, labels, etc.', max_length=100)),
                ('chart_metric', models.CharField(default='count', help_text='Y-axis metric: count, estimate_points', max_length=100)),
                ('config', models.JSONField(default=dict, help_text='Widget config: {color_preset, fill_opacity, show_border, smoothing, show_legend, show_tooltip, center_value, show_markers, filters}')),
                ('position', models.JSONField(default=dict, help_text='Grid position: {row, col, width, height}')),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='db.analyticsdashboard')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Analytics Dashboard Widget',
                'verbose_name_plural': 'Analytics Dashboard Widgets',
                'db_table': 'analytics_dashboard_widgets',
                'ordering': ('sort_order', '-created_at'),
                'indexes': [models.Index(fields=['dashboard', 'deleted_at'], name='analytics_d_dashboa_8d1dc4_idx'), models.Index(fields=['widget_type'], name='analytics_d_widget__13737a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['workspace', 'deleted_at'], name='analytics_d_workspa_98db4e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['owner', 'deleted_at'], name='analytics_d_owner_i_f3c0f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='analytics_dashboard_unique_workspace_name_when_not_deleted'),
        ),
    ]
