# Generated by Django 4.2.29 on 2026-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_issueview_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='product',
            field=models.CharField(blank=True, choices=[('internal-properties', 'Internal Properties'), ('aruhi-id', 'ARUHI ID'), ('corp-site', 'Corp Site'), ('btc', 'BTC'), ('home-search', 'Home Search'), ('housing-loan', 'Housing Loan'), ('living-service', 'Living Service'), ('shared-service', 'Shared Service'), ('credit-guarantee', 'Credit Guarantee'), ('flat35', 'Flat35'), ('aruhi-magazine', 'ARUHI Magazine')], max_length=30, null=True, verbose_name='Product'),
        ),
    ]
