# Generated by Django 4.2.24 on 2025-11-18 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_casereviewmodule_casereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casereview',
            options={'ordering': ('-created_at',), 'verbose_name': 'CaseReview', 'verbose_name_plural': 'CaseReview'},
        ),
        migrations.AlterModelOptions(
            name='casereviewmodule',
            options={'ordering': ('-created_at',), 'verbose_name': 'CaseReviewModule', 'verbose_name_plural': 'CaseReviewModule'},
        ),
        migrations.AlterField(
            model_name='casereview',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='db.casereviewmodule', verbose_name='CaseReviewModule'),
        ),
        migrations.AlterModelTable(
            name='casereview',
            table='test_case_review',
        ),
        migrations.AlterModelTable(
            name='casereviewmodule',
            table='test_review_module',
        ),
        migrations.CreateModel(
            name='CaseReviewThrough',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='CaseReview State')),
                ('result', models.CharField(choices=[('未评审', 'Not Start'), ('通过', 'Pass'), ('不通过', 'Fail')], default='未评审', verbose_name='CaseReview Result')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cases', to='db.testcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cases', to='db.casereview')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'CaseReviewThrough',
                'verbose_name_plural': 'CaseReviewThrough',
                'db_table': 'test_review_through',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='casereview',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='reviews', through='db.CaseReviewThrough', to='db.testcase'),
        ),
    ]
