# Generated by Django 4.2.29 on 2026-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_issueview_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed')], max_length=20, null=True, verbose_name='Manual Status'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
    ]
