# Generated manually

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_user_messenger_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('bot', 'Bot')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('avatar_initials', models.CharField(blank=True, max_length=8, null=True)),
                ('avatar_color', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatmessenger_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_chats', to='db.workspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatmessenger_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Chat Messenger',
                'verbose_name_plural': 'Chats Messenger',
                'db_table': 'chats_messenger',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageMessenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('media', 'Media'), ('system', 'System')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='created', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='db.chatmessenger')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagemessenger_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('forwarded_from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to='db.messagemessenger')),
                ('forwarded_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_forwarded_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='db.messagemessenger')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_messages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagemessenger_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Message Messenger',
                'verbose_name_plural': 'Messages Messenger',
                'db_table': 'messages_messenger',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserRelationMessenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relation_type', models.CharField(choices=[('friend', 'Friend'), ('team', 'Team'), ('subordinate', 'Subordinate'), ('manager', 'Manager'), ('bot', 'Bot')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrelationmessenger_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_relations_owned', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_relations_targeted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrelationmessenger_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'User Relation Messenger',
                'verbose_name_plural': 'User Relations Messenger',
                'db_table': 'user_relations_messenger',
                'ordering': ('-created_at',),
                'unique_together': {('owner_user', 'target_user')},
            },
        ),
        migrations.CreateModel(
            name='UserChatStateMessenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count_cache', models.PositiveIntegerField(default=0)),
                ('draft_text', models.TextField(blank=True, null=True)),
                ('draft_updated_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='db.chatmessenger')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userchatstatemessenger_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('draft_reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.messagemessenger')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.messagemessenger')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userchatstatemessenger_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_chat_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat State Messenger',
                'verbose_name_plural': 'User Chat States Messenger',
                'db_table': 'user_chat_states_messenger',
                'unique_together': {('user', 'chat')},
            },
        ),
        migrations.CreateModel(
            name='PinnedMessageMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='db.chatmessenger')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='db.messagemessenger')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_pinned_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Message Messenger',
                'verbose_name_plural': 'Pinned Messages Messenger',
                'db_table': 'pinned_messages_messenger',
                'unique_together': {('chat', 'message')},
            },
        ),
        migrations.CreateModel(
            name='MessageReactionMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='db.messagemessenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reaction Messenger',
                'verbose_name_plural': 'Message Reactions Messenger',
                'db_table': 'message_reactions_messenger',
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='MessageReceiptMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='db.messagemessenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Receipt Messenger',
                'verbose_name_plural': 'Message Receipts Messenger',
                'db_table': 'message_receipts_messenger',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageDeletionMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope', models.CharField(choices=[('for_me', 'For Me'), ('for_everyone', 'For Everyone')], max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='db.messagemessenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_message_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Deletion Messenger',
                'verbose_name_plural': 'Message Deletions Messenger',
                'db_table': 'message_deletions_messenger',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachmentMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('minio', 'Minio')], default='local', max_length=10)),
                ('storage_key', models.TextField()),
                ('public_url', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.messagemessenger')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Attachment Messenger',
                'verbose_name_plural': 'Message Attachments Messenger',
                'db_table': 'message_attachments_messenger',
            },
        ),
        migrations.CreateModel(
            name='InviteLinkMessenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('user_direct_chat', 'User Direct Chat'), ('chat_invite', 'Chat Invite'), ('organization_invite', 'Organization Invite')], max_length=30)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='db.chatmessenger')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitelinkmessenger_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_invite_links', to='db.workspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitelinkmessenger_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Invite Link Messenger',
                'verbose_name_plural': 'Invite Links Messenger',
                'db_table': 'invite_links_messenger',
            },
        ),
        migrations.CreateModel(
            name='InviteLinkUseMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('limit_exceeded', 'Limit Exceeded'), ('already_member', 'Already Member'), ('blocked', 'Blocked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='db.invitelinkmessenger')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_invite_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Link Use Messenger',
                'verbose_name_plural': 'Invite Link Uses Messenger',
                'db_table': 'invite_link_uses_messenger',
            },
        ),
        migrations.CreateModel(
            name='ChatMemberMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('bot', 'Bot')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='db.chatmessenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Member Messenger',
                'verbose_name_plural': 'Chat Members Messenger',
                'db_table': 'chat_members_messenger',
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatDeletionMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='db.chatmessenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_chat_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Deletion Messenger',
                'verbose_name_plural': 'Chat Deletions Messenger',
                'db_table': 'chat_deletions_messenger',
            },
        ),
        migrations.CreateModel(
            name='BlockMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Block Messenger',
                'verbose_name_plural': 'Blocks Messenger',
                'db_table': 'blocks_messenger',
                'unique_together': {('blocker', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='AuditLogMessenger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_audit_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Audit Log Messenger',
                'verbose_name_plural': 'Audit Logs Messenger',
                'db_table': 'audit_logs_messenger',
                'ordering': ('-created_at',),
            },
        ),
    ]