# Generated by Django 4.2.28 on 2026-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeissue',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[('IN_APP', 'In App'), ('EMAIL', 'Email')],
                default='IN_APP',
                max_length=255,
                null=True,
            ),
        ),
    ]
