# Generated by Django 4.2.30 on 2026-06-30 03:01
# Modified to add seed Built-in project templates RunPython (01-01 plan).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_builtin_project_templates(apps, _schema_editor):
    """Idempotently insert/update the three built-in project templates.

    Per D-12 in CONTEXT.md, the seed is keyed on the stable ``system_key`` of
    each global record so re-running the migration refreshes the built-ins
    without touching any workspace custom copies.
    """
    ProjectTemplate = apps.get_model("db", "ProjectTemplate")

    # Importing here avoids executing the live serializer module against an
    # unmigrated state (e.g. when running against a fresh historical model).
    from plane.app.serializers.project_template import BUILT_IN_PROJECT_TEMPLATES

    for entry in BUILT_IN_PROJECT_TEMPLATES:
        defaults = {
            "name": entry["name"],
            "description": entry.get("description", ""),
            "template_type": entry["template_type"],
            "is_system": True,
            "is_active": True,
            "workspace": None,
            "payload": entry["payload"],
        }
        ProjectTemplate.objects.update_or_create(
            system_key=entry["system_key"],
            is_system=True,
            workspace__isnull=True,
            defaults=defaults,
        )


def reverse_seed_builtin_project_templates(apps, _schema_editor):
    """Remove only the seeded global built-ins; custom templates are untouched."""
    ProjectTemplate = apps.get_model("db", "ProjectTemplate")
    from plane.app.serializers.project_template import BUILT_IN_PROJECT_TEMPLATES

    keys = [entry["system_key"] for entry in BUILT_IN_PROJECT_TEMPLATES]
    ProjectTemplate.objects.filter(
        system_key__in=keys, is_system=True, workspace__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('template_type', models.CharField(choices=[('built_in', 'Built-in'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('system_key', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_offset_days', models.IntegerField(blank=True, null=True)),
                ('target_offset_days', models.IntegerField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Template',
                'verbose_name_plural': 'Project Templates',
                'db_table': 'project_templates',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True), ('workspace__isnull', True)), fields=('system_key',), name='project_template_unique_system_key_when_system_global'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False), ('is_active', True)), fields=('workspace', 'name'), name='project_template_unique_active_name_per_workspace'),
        ),
        migrations.RunPython(
            seed_builtin_project_templates,
            reverse_code=reverse_seed_builtin_project_templates,
        ),
    ]
