# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="page",
            field=models.BooleanField(default=False),
        ),
    ]
