# Generated by Django 4.2.30 on 2026-07-21 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooperArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_event_key', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_revision_id', models.CharField(max_length=255)),
                ('source_kind', models.CharField(choices=[('plane_page', 'Plane page'), ('plane_comment', 'Plane comment'), ('scm_pr', 'SCM pull request')], max_length=24)),
                ('source_object_id', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'db_table': 'looper_artifacts',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LooperDispatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('state_version', models.PositiveBigIntegerField(default=1)),
                ('requested_mode', models.CharField(choices=[('auto', 'Auto'), ('worker', 'Worker')], max_length=16)),
                ('active_role', models.CharField(choices=[('planner', 'Planner'), ('worker', 'Worker')], max_length=16)),
                ('active_role_revision', models.PositiveBigIntegerField(default=1)),
                ('node_id', models.CharField(max_length=128)),
                ('node_name_snapshot', models.CharField(max_length=255)),
                ('node_binding_revision', models.PositiveBigIntegerField(default=1)),
                ('role_policy_revision', models.PositiveBigIntegerField(default=1)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('awaiting_human', 'Awaiting Human'), ('stop_requested', 'Stop Requested'), ('confirmed_stopped', 'Confirmed Stopped'), ('released', 'Released'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('wait_kind', models.CharField(blank=True, choices=[('role_decision', 'Role decision'), ('technical_spec_approval', 'Technical spec approval'), ('qa', 'QA')], max_length=32, null=True)),
                ('health', models.CharField(choices=[('ok', 'OK'), ('projection_drift', 'Projection drift'), ('role_drift', 'Role drift'), ('binding_suspended', 'Binding suspended'), ('node_unreachable', 'Node unreachable')], default='ok', max_length=32)),
                ('execution_attempt_id', models.UUIDField(blank=True, null=True)),
                ('claim_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('fencing_token', models.PositiveBigIntegerField(default=0)),
                ('claim_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_node_ack_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField()),
                ('release_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('design_member_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_design_dispatches', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_looper_dispatches', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looper_dispatches', to='db.issue')),
                ('owner_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_looper_dispatches', to=settings.AUTH_USER_MODEL)),
                ('product_member_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_product_dispatches', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('qa_member_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_qa_dispatches', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_dispatches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LooperRoleRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_event_key', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('product', 'Product'), ('design', 'Design'), ('engineering', 'Engineering'), ('qa', 'QA')], max_length=24)),
                ('question_summary', models.CharField(max_length=500)),
                ('policy_revision', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='open', max_length=24)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_role_answers', to='db.issuecomment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to='db.looperdispatch')),
                ('eligible_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_role_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_role_requests',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LooperCollaborationSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phase', models.CharField(max_length=48)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_role', models.CharField(blank=True, default='', max_length=24)),
                ('role_counts', models.JSONField(default=dict)),
                ('snapshot_version', models.PositiveBigIntegerField(default=0)),
                ('events_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_snapshot', to='db.looperdispatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('waiting_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_waiting_snapshots', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_collaboration_snapshots',
            },
        ),
        migrations.CreateModel(
            name='LooperCollaborationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_version', models.PositiveBigIntegerField()),
                ('source_event_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=48)),
                ('phase', models.CharField(max_length=48)),
                ('role', models.CharField(blank=True, default='', max_length=24)),
                ('role_policy_revision', models.PositiveBigIntegerField()),
                ('payload_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looper_collaboration_events', to=settings.AUTH_USER_MODEL)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db.looperartifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_events', to='db.looperdispatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('role_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db.looperrolerequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_collaboration_events',
                'ordering': ('event_version',),
            },
        ),
        migrations.AddField(
            model_name='looperartifact',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='db.looperdispatch'),
        ),
        migrations.AddField(
            model_name='looperartifact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='looperartifact',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='looperartifact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='looperrolerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dispatch', 'source_event_key'), name='looper_role_request_source_unique'),
        ),
        migrations.AddIndex(
            model_name='looperdispatch',
            index=models.Index(fields=['node_id', 'state'], name='looper_node_state_idx'),
        ),
        migrations.AddIndex(
            model_name='looperdispatch',
            index=models.Index(fields=['issue', 'state'], name='looper_issue_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='looperdispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('state__in', ('queued', 'claimed', 'running', 'awaiting_human', 'stop_requested', 'confirmed_stopped'))), fields=('issue',), name='looper_dispatch_active_issue_unique'),
        ),
        migrations.AddConstraint(
            model_name='looperdispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'revision'), name='looper_dispatch_issue_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='looperdispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'idempotency_key'), name='looper_dispatch_issue_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopercollaborationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dispatch', 'event_version'), name='looper_event_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopercollaborationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dispatch', 'source_event_key'), name='looper_event_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='looperartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dispatch', 'source_event_key'), name='looper_artifact_source_unique'),
        ),
    ]
