# Generated by Django 4.2.28 on 2026-02-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_projectmember_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemCommentSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_type', models.CharField(choices=[('IN_APP', 'In App'), ('PUBLISHED_BOARD', 'Published Board'), ('TRACKABLE_LINK', 'Trackable Link'), ('EMAIL', 'Email')], default='IN_APP', max_length=255)),
                ('source_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extra', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Work Item Comment Source',
                'verbose_name_plural': 'Work Item Comment Sources',
                'db_table': 'work_item_comment_sources',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='issuerelation',
            name='issue_relation_unique_issue_related_issue_when_deleted_at_null',
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='trackable_anchor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='issuerelation',
            unique_together={('issue', 'related_issue', 'relation_type', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='issuerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'related_issue', 'relation_type'), name='issue_relation_unique_issue_related_issue_relation_type_when_deleted_at_null'),
        ),
        migrations.AddField(
            model_name='workitemcommentsource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workitemcommentsource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='workitemcommentsource',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workitemcommentsource',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment', to='db.workitemcommentsource'),
        ),
    ]
