# Generated by Django 4.2.24 on 2025-11-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_casereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='state',
            field=models.CharField(choices=[('未开始', 'Not Start'), ('进行中', 'Progress'), ('已完成', 'Completed')], default='未开始', verbose_name='CaseReview State'),
        ),
        migrations.AlterField(
            model_name='casereviewthrough',
            name='state',
            field=models.CharField(choices=[('未开始', 'Not Start'), ('进行中', 'Progress'), ('已完成', 'Completed')], default='未开始', verbose_name='CaseReview State'),
        ),
    ]
