# Generated by Django 4.2.30 on 2026-06-17 13:51

from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.workspace


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_issueworklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worklog_timer_state_groups',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='worklog_timer_state_groups',
            field=models.JSONField(default=plane.db.models.workspace.get_default_worklog_timer_state_groups),
        ),
        migrations.AlterField(
            model_name='issueworklog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='issueworklog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
    ]
