# Generated by Django 4.2.28 on 2026-02-18 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_staffprofile_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
