# Generated by Django 4.2.28 on 2026-02-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_workitemcommentsource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceuserlink',
            name='project',
        ),
    ]
