# Generated by Django 5.2.15 on 2026-09-15 10:35

# NOTE (research audit hardening, P0-AUD-02 / review item T-05)
# ``research_audit_events`` is append-only. Enforcement is layered:
#   1. model layer: ``ResearchAuditEvent.save()`` refuses updates and
#      ``delete()`` raises (see plane/db/models/research/audit.py);
#   2. deployment layer: production operators should revoke UPDATE/DELETE from
#      the application role, e.g.
#         REVOKE UPDATE, DELETE ON research_audit_events FROM <app_role>;
#      Development and test stacks share a single owner connection, so this step
#      is documented for deployment instead of being executed by a migration.

import django.db.models.deletion
import django.utils.timezone
import plane.db.models.research.org
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(db_index=True, default='', max_length=1024)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('ROOT', 'Root'), ('INSTITUTE', 'Institute'), ('LAB', 'Lab'), ('GROUP', 'Group'), ('TEAM', 'Team')], default='GROUP', max_length=20)),
                ('sort_order', models.FloatField(default=plane.db.models.research.org.get_default_org_unit_sort_order)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='db.orgunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_org_units', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research Org Unit',
                'verbose_name_plural': 'Research Org Units',
                'db_table': 'research_org_units',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MentorBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_mentor_bindings', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_mentee_bindings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_mentor_bindings', to='db.workspace')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_bindings', to='db.orgunit')),
            ],
            options={
                'verbose_name': 'Research Mentor Binding',
                'verbose_name_plural': 'Research Mentor Bindings',
                'db_table': 'research_mentor_bindings',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrgUnitMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('org_role', models.CharField(choices=[('OWNER', 'Owner'), ('PI', 'Principal Investigator'), ('ADVISOR', 'Advisor'), ('REVIEWER', 'Reviewer'), ('UNIT_ADMIN', 'Unit Admin')], default='PI', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='db.orgunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_org_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_org_members', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research Org Unit Member',
                'verbose_name_plural': 'Research Org Unit Members',
                'db_table': 'research_org_unit_members',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResearchAuditEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_audit_events', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_audit_events', to='db.orgunit')),
                # nullable: identity events (sign-in, provisioning) may occur before
                # the user belongs to any workspace (P0-AUD-04)
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_audit_events', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research Audit Event',
                'verbose_name_plural': 'Research Audit Events',
                'db_table': 'research_audit_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['workspace', 'path'], name='rsch_orgu_ws_path_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['workspace', 'parent', 'sort_order'], name='rsch_orgu_ws_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['workspace', 'unit_type'], name='rsch_orgu_ws_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'parent', 'name'), name='rsch_orgu_uq_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('workspace', 'name'), name='rsch_orgu_uq_root_name'),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True), ('unit_type', 'ROOT')), fields=('workspace',), name='rsch_orgu_uq_single_root'),
        ),
        migrations.AddIndex(
            model_name='mentorbinding',
            index=models.Index(fields=['workspace', 'mentee'], name='rsch_mtr_mentee_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorbinding',
            index=models.Index(fields=['workspace', 'mentor'], name='rsch_mtr_mentor_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'mentee', 'mentor'), name='rsch_mtr_uq_pair'),
        ),
        migrations.AddConstraint(
            model_name='mentorbinding',
            constraint=models.CheckConstraint(condition=models.Q(('mentee', models.F('mentor')), _negated=True), name='rsch_mtr_no_self'),
        ),
        migrations.AddIndex(
            model_name='orgunitmember',
            index=models.Index(fields=['user', 'org_role'], name='rsch_orgm_user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunitmember',
            index=models.Index(fields=['org_unit', 'org_role'], name='rsch_orgm_unit_role_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunitmember',
            index=models.Index(fields=['workspace', 'user'], name='rsch_orgm_ws_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgunitmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_unit', 'user', 'org_role'), name='rsch_orgm_uq_unit_user_role'),
        ),
        migrations.AddConstraint(
            model_name='orgunitmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('workspace', 'user'), name='rsch_orgm_uq_primary'),
        ),
        migrations.AddIndex(
            model_name='researchauditevent',
            index=models.Index(fields=['workspace', 'created_at'], name='research_audit_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='researchauditevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='research_audit_resource_idx'),
        ),
        migrations.AddIndex(
            model_name='researchauditevent',
            index=models.Index(fields=['actor', 'created_at'], name='research_audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='researchauditevent',
            index=models.Index(fields=['workspace', 'action'], name='research_audit_ws_action_idx'),
        ),
    ]
