# Generated by Django 4.2.30 on 2026-07-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_looperartifact_looperdispatch_looperrolerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooperLinkChallengeReplay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('challenge_id', models.UUIDField(unique=True)),
                ('nonce', models.BinaryField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'looper_link_challenge_replays',
            },
        ),
        migrations.CreateModel(
            name='LooperRequestNonce',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('binding_id', models.UUIDField()),
                ('key_revision', models.PositiveBigIntegerField()),
                ('nonce', models.BinaryField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'looper_request_nonces',
                'indexes': [models.Index(fields=['expires_at'], name='looper_nonce_expiry_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='looperrequestnonce',
            constraint=models.UniqueConstraint(fields=('binding_id', 'key_revision', 'nonce'), name='looper_request_nonce_unique'),
        ),
        migrations.AddIndex(
            model_name='looperlinkchallengereplay',
            index=models.Index(fields=['expires_at'], name='looper_link_expiry_idx'),
        ),
    ]
