# Generated by Django 4.2.24 on 2025-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_casereview_state_alter_casereviewthrough_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereview',
            name='description',
            field=models.TextField(blank=True, verbose_name='CaseReview Description'),
        ),
    ]
