# Generated by Django 4.2.30 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='email_message_id',
            field=models.CharField(
                blank=True,
                help_text='RFC 2822 Message-ID header for deduplication.',
                max_length=512,
                null=True,
                unique=True,
                verbose_name='Email Message-ID',
            ),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='email_date',
            field=models.DateTimeField(
                blank=True,
                help_text='Parsed Date header from the email for fallback deduplication.',
                null=True,
                verbose_name='Email Date',
            ),
        ),
    ]
