# Generated by Django 4.2.30 on 2026-07-06 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_importer_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total_time_spent',
            field=models.IntegerField(default=0, verbose_name='Total Time Spent (seconds)'),
        ),
        migrations.CreateModel(
            name='IssueTimeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Log Date')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Stopped At')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duration (seconds)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Time Log',
                'verbose_name_plural': 'Issue Time Logs',
                'db_table': 'issue_time_logs',
                'ordering': ('-date', '-started_at'),
            },
        ),
    ]
