# Generated by Django 4.2.28 on 2026-02-18 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0123_department_level_max_6"),
    ]

    operations = [
        # Add estimate_time field to Issue
        migrations.AddField(
            model_name="issue",
            name="estimate_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time estimate in minutes", null=True
            ),
        ),
        # Change is_time_tracking_enabled default to True
        migrations.AlterField(
            model_name="project",
            name="is_time_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        # Create IssueWorkLog model
        migrations.CreateModel(
            name="IssueWorkLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, default="")),
                ("logged_at", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_worklogs",
                        to="db.issue",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Work Log",
                "verbose_name_plural": "Issue Work Logs",
                "db_table": "issue_worklogs",
                "ordering": ("-logged_at", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="issueworklog",
            index=models.Index(
                fields=["issue", "logged_by"],
                name="issue_workl_issue_i_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issueworklog",
            index=models.Index(
                fields=["project", "logged_at"],
                name="issue_workl_project_idx",
            ),
        ),
    ]
