# Generated by Django 5.2.15 on 2026-08-09 19:25

import django.core.validators
import django.db.models.deletion
import plane.db.models.pomodoro
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pomodoro_settings',
            field=models.JSONField(default=plane.db.models.pomodoro.get_default_pomodoro_settings),
        ),
        migrations.CreateModel(
            name='PomodoroTimer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paused_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('discarded', 'Discarded')], default='running', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_timers', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_timers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Pomodoro Timer',
                'verbose_name_plural': 'Pomodoro Timers',
                'db_table': 'pomodoro_timers',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['started_by', 'status'], name='pomodoro_timer_user_status_idx'), models.Index(fields=['issue'], name='pomodoro_timer_issue_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['running', 'paused'])), fields=('started_by',), name='pomodoro_timer_unique_active_per_user')],
            },
        ),
    ]
