# Generated by Django 4.2.24 on 2025-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_casereview_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='CaseReview Ended Time'),
        ),
        migrations.AlterField(
            model_name='casereview',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='CaseReview Started Time'),
        ),
    ]
