# Generated by Django 4.2.30 on 2026-07-21 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_looperlinkchallengereplay_looperrequestnonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooperNodeBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('node_id', models.CharField(max_length=128)),
                ('node_name_snapshot', models.CharField(max_length=255)),
                ('allowed_roles', models.JSONField(default=list)),
                ('allow_offline_queue', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revocation_pending', 'Revocation pending'), ('revoked', 'Revoked')], default='pending', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_looper_node_bindings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looper_node_bindings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_node_bindings',
            },
        ),
        migrations.CreateModel(
            name='LooperWorkItemProtocol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('protocol', models.CharField(choices=[('legacy', 'Legacy'), ('strict_v1', 'Strict v1')], max_length=16)),
                ('classified_at', models.DateTimeField()),
                ('project_strict_epoch', models.DateTimeField(blank=True, null=True)),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_looper_work_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='looper_protocol', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_work_item_protocols',
            },
        ),
        migrations.CreateModel(
            name='LooperProjectRolePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('design_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looper_design_role_policies', to=settings.AUTH_USER_MODEL)),
                ('product_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looper_product_role_policies', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('qa_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looper_qa_role_policies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_project_role_policies',
            },
        ),
        migrations.CreateModel(
            name='LooperProjectIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('read_only', 'Read only'), ('active', 'Active'), ('paused', 'Paused')], default='read_only', max_length=16)),
                ('strict_epoch', models.DateTimeField(blank=True, null=True)),
                ('activation_checklist_revision', models.PositiveBigIntegerField(default=0)),
                ('effective_legacy_trigger_label_ids', models.JSONField(default=list)),
                ('node_capability_revisions', models.JSONField(default=dict)),
                ('paused_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_project_integrations',
            },
        ),
        migrations.CreateModel(
            name='LooperNodeSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.UUIDField()),
                ('instance_nonce', models.BinaryField(max_length=16)),
                ('lease_expires_at', models.DateTimeField()),
                ('last_renewed_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='db.loopernodebinding')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_node_sessions',
            },
        ),
        migrations.CreateModel(
            name='LooperNodeKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key_revision', models.PositiveBigIntegerField()),
                ('public_key', models.BinaryField(max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('recovery_only', 'Recovery only'), ('revoked', 'Revoked')], default='active', max_length=24)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('stop_ack_attempt_allowlist', models.JSONField(default=list)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='db.loopernodebinding')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'looper_node_keys',
            },
        ),
        migrations.AddField(
            model_name='looperdispatch',
            name='node_binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='db.loopernodebinding'),
        ),
        migrations.AddConstraint(
            model_name='looperprojectrolepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='looper_project_role_policy_unique'),
        ),
        migrations.AddConstraint(
            model_name='looperprojectintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='looper_project_integration_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopernodesession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session_id',), name='looper_node_session_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopernodesession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('state', 'active')), fields=('binding',), name='looper_node_session_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopernodekey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('binding', 'key_revision'), name='looper_node_key_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopernodekey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('state', 'active')), fields=('binding',), name='looper_node_key_active_unique'),
        ),
        migrations.AddIndex(
            model_name='loopernodebinding',
            index=models.Index(fields=['project', 'state'], name='looper_binding_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='loopernodebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('state__in', ('pending', 'active', 'revocation_pending'))), fields=('project', 'member'), name='looper_binding_active_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='loopernodebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('state__in', ('pending', 'active', 'revocation_pending'))), fields=('project', 'node_id'), name='looper_binding_active_node_unique'),
        ),
    ]
