# Generated by Django 5.2.15 on 2026-09-15 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_research_org_and_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(default='ai4ms-oidc', max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('email_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_identity_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Identity Mapping',
                'verbose_name_plural': 'Research Identity Mappings',
                'db_table': 'research_identity_mappings',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'employee_id'], name='rsch_idmap_provider_emp_idx'), models.Index(fields=['user', 'provider'], name='rsch_idmap_user_provider_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'subject'), name='rsch_identity_uq_provider_subject'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'user'), name='rsch_identity_uq_provider_user')],
            },
        ),
    ]
