# Generated by Django 4.2.30 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_supportticket_email_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacememberinvite',
            name='project_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
