# Generated by Django 4.2.24 on 2025-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_alter_casereview_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereview',
            name='mode',
            field=models.CharField(choices=[('单人评审', 'Single'), ('多人评审', 'Multiple')], default='单人评审', verbose_name='CaseReview Mode'),
        ),
    ]
