# Generated by Django 4.2.30 on 2026-06-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_remove_issueworklog_unique_active_timer_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('work_item', 'Work Item')], db_index=True, default='project', max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('paragraph', 'Paragraph'), ('number', 'Number'), ('single_select', 'Single select'), ('multi_select', 'Multi select'), ('boolean', 'Checkbox'), ('radio', 'Radio'), ('date', 'Date'), ('datetime', 'Date time'), ('color', 'Color'), ('url', 'Hyperlink'), ('email', 'Email')], max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('admin_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('width', models.PositiveSmallIntegerField(default=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'db_table': 'custom_fields',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.customfield')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
                'db_table': 'custom_field_values',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('custom_field', 'project'), name='custom_field_value_unique_field_project_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'entity_type', 'key'), name='custom_field_unique_key_per_entity_when_deleted_at_null'),
        ),
    ]
