# Generated by Django 4.2.30 on 2026-07-15 11:53

from django.db import migrations, models
import plane.db.models.workspace


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issuetimelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetimelog',
            name='auto_stop_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Auto Stop At'),
        ),
        migrations.AddField(
            model_name='issuetimelog',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('state_change', 'State change'), ('working_hours', 'Working hours'), ('manual_entry', 'Manual entry')], max_length=20, null=True, verbose_name='Stop Reason'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='working_hours',
            field=models.JSONField(default=plane.db.models.workspace.get_default_working_hours),
        ),
        migrations.AddIndex(
            model_name='issuetimelog',
            index=models.Index(condition=models.Q(('auto_stop_at__isnull', False), ('stopped_at__isnull', True)), fields=['auto_stop_at'], name='itl_open_autostop_idx'),
        ),
    ]
