# Generated by Django 4.2.28 on 2026-02-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issue_worklog_and_estimate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueview',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
    ]
