# Generated by Django 5.2.15 on 2026-09-15 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_research_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceResearchSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('module_enabled', models.BooleanField(default=False)),
                ('org_enabled', models.BooleanField(default=True)),
                ('report_enabled', models.BooleanField(default=True)),
                ('approval_enabled', models.BooleanField(default=True)),
                ('allow_multiple_projects', models.BooleanField(default=False)),
                ('default_report_visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DIRECT_ADVISOR', 'Direct advisors'), ('UNIT', 'Organisation unit'), ('ANCESTRY', 'Ancestry principal investigators'), ('WORKSPACE', 'Workspace'), ('CUSTOM', 'Custom grants')], default='DIRECT_ADVISOR', max_length=32)),
                ('weekly_default_visibility', models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('DIRECT_ADVISOR', 'Direct advisors'), ('UNIT', 'Organisation unit'), ('ANCESTRY', 'Ancestry principal investigators'), ('WORKSPACE', 'Workspace'), ('CUSTOM', 'Custom grants')], max_length=32, null=True)),
                ('monthly_default_visibility', models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('DIRECT_ADVISOR', 'Direct advisors'), ('UNIT', 'Organisation unit'), ('ANCESTRY', 'Ancestry principal investigators'), ('WORKSPACE', 'Workspace'), ('CUSTOM', 'Custom grants')], max_length=32, null=True)),
                ('image_max_mb', models.PositiveIntegerField(default=20)),
                ('pdf_max_mb', models.PositiveIntegerField(default=100)),
                ('markdown_max_mb', models.PositiveIntegerField(default=5)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_retention_days', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_setting', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Research Setting',
                'verbose_name_plural': 'Workspace Research Settings',
                'db_table': 'workspace_research_settings',
                'ordering': ('-created_at',),
            },
        ),
    ]
