# Generated by Django 4.2.30 on 2026-07-18 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_issuetimelog_auto_stop_at_issuetimelog_stop_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='allow_any_transition',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='db.state')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'State Transition',
                'verbose_name_plural': 'State Transitions',
                'db_table': 'state_transitions',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='statetransition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('from_state', 'to_state'), name='state_transition_unique_from_to_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='statetransition',
            unique_together={('from_state', 'to_state', 'deleted_at')},
        ),
    ]
