# Generated by Django 4.2.24 on 2025-11-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_casereview_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewmodule',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
