# Generated by Django 5.2.15 on 2026-08-14 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_userissueplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('macos', 'macOS')], max_length=16)),
                ('apns_token', models.CharField(max_length=255)),
                ('apns_env', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=16)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('seq', models.BigIntegerField()),
                ('entity_type', models.CharField(choices=[('issue', 'Issue'), ('issue_comment', 'Issue Comment'), ('cycle', 'Cycle'), ('module', 'Module'), ('project', 'Project'), ('pomodoro_timer', 'Pomodoro Timer')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('moved', 'Moved')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Sync Event',
                'verbose_name_plural': 'Sync Events',
                'db_table': 'sync_events',
                'ordering': ('workspace', 'seq'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSyncSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sequence', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Sync Sequence',
                'verbose_name_plural': 'Workspace Sync Sequences',
                'db_table': 'workspace_sync_sequences',
            },
        ),
        migrations.CreateModel(
            name='DeviceWorkspaceCursor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_cursors', to='db.device')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Device Workspace Cursor',
                'verbose_name_plural': 'Device Workspace Cursors',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'platform'], name='device_user_platform_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'apns_token'), name='device_unique_user_token'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['workspace', 'seq'], name='sync_event_workspace_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['workspace', 'entity_type', 'entity_id'], name='sync_event_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.UniqueConstraint(fields=('workspace', 'seq'), name='sync_event_unique_workspace_seq'),
        ),
        migrations.AddConstraint(
            model_name='deviceworkspacecursor',
            constraint=models.UniqueConstraint(fields=('device', 'workspace'), name='device_cursor_unique_device_workspace'),
        ),
    ]
