# Generated by Django 4.2.30 on 2026-06-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_customfield_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='db.issue'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('issue__isnull', False)), fields=('custom_field', 'issue'), name='custom_field_value_unique_field_issue_when_deleted_at_null'),
        ),
    ]
