# Generated by Django 4.2.28 on 2026-03-05 08:46

from django.db import migrations, models
import plane.db.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_cycleuserproperties_last_used_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleuserproperties',
            name='display_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_display_filters),
        ),
        migrations.AlterField(
            model_name='cycleuserproperties',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
        migrations.AlterField(
            model_name='issueview',
            name='display_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_display_filters),
        ),
        migrations.AlterField(
            model_name='moduleuserproperties',
            name='display_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_display_filters),
        ),
        migrations.AlterField(
            model_name='moduleuserproperties',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
        migrations.AlterField(
            model_name='projectuserproperty',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
        migrations.AlterField(
            model_name='workspaceuserproperties',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
    ]
