# Generated by Django 4.2.30 on 2026-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_issue_worklog_external_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='type',
            field=models.CharField(
                choices=[('categories', 'Categories'), ('points', 'Points'), ('time', 'Time')],
                default='categories',
                max_length=255,
            ),
        ),
    ]
