# Generated by Django 4.2.30 on 2026-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_contractchat_contractchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetag',
            name='kind',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('GROUP', 'Group'), ('PERSON', 'Person'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
    ]
