# Generated by Django 4.2.30 on 2026-06-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_customfieldvalue_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('crm_api_url', models.URLField(max_length=500)),
                ('crm_api_key_encrypted', models.TextField(blank=True, default='')),
                ('crm_invoice_hours_field_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('crm_project_id_custom_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_project_id_integration', to='db.customfield')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_integration', to='db.workspace')),
            ],
            options={
                'verbose_name': 'CRM Integration',
                'verbose_name_plural': 'CRM Integrations',
                'db_table': 'crm_integrations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CrmSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sync_month', models.DateField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20)),
                ('projects_processed', models.PositiveIntegerField(default=0)),
                ('projects_synced', models.PositiveIntegerField(default=0)),
                ('projects_skipped', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='db.crmintegration')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'CRM Sync Log',
                'verbose_name_plural': 'CRM Sync Logs',
                'db_table': 'crm_sync_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
