# SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
# SPDX-License-Identifier: LicenseRef-Plane-Commercial
#
# Licensed under the Plane Commercial License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# https://plane.so/legals/eula
#
# DO NOT remove or modify this notice.
# NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.

# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_alter_cycleuserproperties_display_filters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Last Activity At",
            ),
        ),
    ]
