# Generated by Django 4.2.24 on 2025-11-20 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_casereviewmodule_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='mode',
            field=models.CharField(choices=[('单人评审', 'green'), ('多人评审', 'blue')], default='单人评审', verbose_name='CaseReview Mode'),
        ),
        migrations.AlterField(
            model_name='casereview',
            name='state',
            field=models.CharField(choices=[('未开始', 'gray'), ('进行中', 'blue'), ('已完成', 'green')], default='未开始', verbose_name='CaseReview State'),
        ),
        migrations.AlterField(
            model_name='casereviewthrough',
            name='result',
            field=models.CharField(choices=[('通过', 'green'), ('不通过', 'red'), ('重新提审', 'gold'), ('评审中', 'blue'), ('未评审', 'gray')], default='未评审', verbose_name='CaseReview Result'),
        ),
        migrations.AlterField(
            model_name='casereviewthrough',
            name='state',
            field=models.CharField(choices=[('未开始', 'gray'), ('进行中', 'blue'), ('已完成', 'green')], default='未开始', verbose_name='CaseReview State'),
        ),
        migrations.CreateModel(
            name='CaseReviewRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result', models.CharField(choices=[('通过', 'green'), ('不通过', 'red'), ('重新提审', 'gold'), ('评审中', 'blue'), ('未评审', 'gray')], default='未评审', verbose_name='CaseReview Result')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='CaseReview Reason')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
