# Generated by Django 5.2.15 on 2026-09-15 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_research_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProjectProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('research_type', models.CharField(choices=[('PHD', 'PhD'), ('MASTER', 'Master'), ('POSTDOC', 'Postdoc'), ('RESEARCH_PROJECT', 'Research project')], default='RESEARCH_PROJECT', max_length=32)),
                ('workflow_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=16)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('expected_end_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_project_profiles', to='db.orgunit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_profiles', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_profile', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_profiles', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research Project Profile',
                'verbose_name_plural': 'Research Project Profiles',
                'db_table': 'research_project_profiles',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'workflow_status'], name='rsch_project_ws_status_idx'), models.Index(fields=['org_unit'], name='rsch_project_org_unit_idx'), models.Index(fields=['workspace', 'owner'], name='rsch_project_ws_owner_idx')],
            },
        ),
    ]
