# Generated by Django 5.2.15 on 2026-09-15 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_research_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('period_key', models.CharField(db_index=True, max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=16)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DIRECT_ADVISOR', 'Direct advisors'), ('UNIT', 'Organisation unit'), ('ANCESTRY', 'Ancestry principal investigators'), ('WORKSPACE', 'Workspace'), ('CUSTOM', 'Custom grants')], default='DIRECT_ADVISOR', max_length=32)),
                ('is_backfill', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_reports', to='db.orgunit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_report', to='db.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='db.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Periodic Report',
                'verbose_name_plural': 'Periodic Reports',
                'db_table': 'research_periodic_reports',
                'ordering': ('-period_start', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReportAccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_report_grants_given', to=settings.AUTH_USER_MODEL)),
                ('grantee_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_report_grants', to='db.orgunit')),
                ('grantee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_report_grants', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='db.periodicreport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Report Access Grant',
                'verbose_name_plural': 'Report Access Grants',
                'db_table': 'research_report_access_grants',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('RETURN', 'Return'), ('ACCEPT', 'Accept'), ('REOPEN', 'Reopen')], max_length=16)),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('ACCEPTED', 'Accepted')], max_length=16)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs revision'), ('ACCEPTED', 'Accepted')], max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('snapshot_version', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_report_review_logs', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='db.periodicreport')),
            ],
            options={
                'verbose_name': 'Report Review Log',
                'verbose_name_plural': 'Report Review Logs',
                'db_table': 'research_report_review_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='periodicreport',
            index=models.Index(fields=['workspace', 'status', 'period_key'], name='rsch_report_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicreport',
            index=models.Index(fields=['org_unit', 'period_key'], name='rsch_report_unit_period_idx'),
        ),
        migrations.AddIndex(
            model_name='periodicreport',
            index=models.Index(fields=['owner', 'report_type', 'period_start'], name='rsch_report_owner_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodicreport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'owner', 'report_type', 'period_key'), name='rsch_report_uq_owner_period'),
        ),
        migrations.AddIndex(
            model_name='reportaccessgrant',
            index=models.Index(fields=['report', 'is_revoked'], name='rsch_grant_report_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grantee_org_unit__isnull', True), ('grantee_user__isnull', False)), models.Q(('grantee_org_unit__isnull', False), ('grantee_user__isnull', True)), _connector='OR'), name='rsch_grant_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='reportreviewlog',
            index=models.Index(fields=['report', 'created_at'], name='rsch_review_log_report_idx'),
        ),
    ]
