# Generated by Django 4.2.30 on 2026-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_filetag_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterhistory',
            name='provider',
            field=models.CharField(choices=[('json', 'json'), ('csv', 'csv'), ('xlsx', 'xlsx'), ('zip', 'zip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exporterhistory',
            name='type',
            field=models.CharField(choices=[('issue_exports', 'Issue Exports'), ('issue_worklogs', 'Issue Worklogs'), ('file_library', 'File Library')], default='issue_exports', max_length=50),
        ),
    ]
