# Generated by Django 4.2.30 on 2026-07-13 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_alter_workspacefeature_key_expensecategory_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='invoice_asset',
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_documents', to='db.fileasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='db.expense')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_documents', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Expense Document',
                'verbose_name_plural': 'Expense Documents',
                'db_table': 'expense_documents',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='expensedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('expense', 'asset'), name='unique_expense_document_when_not_deleted'),
        ),
    ]
