# Generated by Django 4.2.24 on 2025-11-20 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_alter_casereview_mode_alter_casereview_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewrecord',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
