# Generated by Django 4.2.30 on 2026-07-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_alter_exporterhistory_provider_and_more'),
        ('db', '0128_remove_expense_invoice_asset_expensedocument_and_more'),
    ]

    operations = [
    ]
