# Generated by Django 4.2.24 on 2025-11-20 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_casereviewrecord_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewrecord',
            name='crt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to='db.casereviewthrough'),
        ),
    ]
