# Generated by Django 4.2.30 on 2026-07-14 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_merge_20260714_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'payroll_employees',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('aguinaldo_days', models.PositiveSmallIntegerField(default=15)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'db_table': 'payroll_offices',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('concept', models.CharField(choices=[('SALARY', 'Sueldo'), ('AGUINALDO', 'Aguinaldo'), ('BONUS', 'Bono'), ('OTHER', 'Otro')], default='SALARY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='db.employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='db.office')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Payroll Payment',
                'verbose_name_plural': 'Payroll Payments',
                'db_table': 'payroll_payments',
                'ordering': ('-scheduled_date',),
            },
        ),
        migrations.CreateModel(
            name='PayrollAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('can_view_annual_cost', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_access', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_access', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Payroll Access',
                'verbose_name_plural': 'Payroll Access',
                'db_table': 'payroll_access',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('BONUS', 'Bono'), ('DEBT', 'Adeudo'), ('SUPPORT', 'Apoyo')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='db.employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='db.office')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'db_table': 'payroll_adjustments',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('periodicity', models.CharField(choices=[('MONTHLY', 'Mensual'), ('BIWEEKLY', 'Quincenal'), ('WEEKLY', 'Semanal'), ('DAILY', 'Diario')], default='MONTHLY', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='db.employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='db.office')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
                'db_table': 'payroll_salaries',
                'ordering': ('-effective_from',),
                'indexes': [models.Index(fields=['employee', 'effective_from'], name='salary_employee_from_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True)), fields=('employee', 'office'), name='unique_open_salary_per_office_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_effective_to_after_from'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='salary_amount_not_negative'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['workspace', 'status', 'scheduled_date'], name='payroll_pay_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['employee', 'scheduled_date'], name='payroll_pay_employee_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payroll_payment_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollpayment',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_payment_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='payrollaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'user'), name='unique_payroll_access_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='unique_office_name_when_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['workspace', 'termination_date'], name='employee_ws_termination_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='employee_termination_after_hire'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['workspace', 'effective_date'], name='adjustment_ws_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='adjustment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='adjustment_amount_not_negative'),
        ),
    ]
