# Generated by Django 4.2.29 on 2026-03-12 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_issueactivity_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemRelationDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('outward', models.CharField(max_length=255)),
                ('inward', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Work Item Relation Definition',
                'verbose_name_plural': 'Work Item Relation Definitions',
                'db_table': 'work_item_relation_definitions',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='workitemrelationdefinition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workitemrelationdefinition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workitemrelationdefinition',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_relation_definitions', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='workitemrelationdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='unique_workspace_relation_def_name_when_not_deleted'),
        ),
        migrations.RemoveConstraint(
            model_name='issuerelation',
            name='issue_relation_unique_issue_related_issue_relation_type_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='issuerelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='category',
            field=models.CharField(choices=[('dependency', 'Dependency'), ('relation', 'Relation')], default='dependency', help_text="Discriminator: 'dependency' for CharField-based deps, 'relation' for FK-based relations.", max_length=20),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuerelation',
            name='relation_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Issue Relation Type'),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='definition',
            field=models.ForeignKey(blank=True, help_text='FK to WorkItemRelationDefinition. Set for relation rows, NULL for dependencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_relations', to='db.workitemrelationdefinition'),
        ),
        migrations.AddConstraint(
            model_name='issuerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'dependency'), ('deleted_at__isnull', True)), fields=('issue', 'related_issue', 'relation_type'), name='issue_relation_unique_dependency_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='issuerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'relation'), ('deleted_at__isnull', True)), fields=('issue', 'related_issue', 'definition'), name='issue_relation_unique_relation_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='workitemrelationdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'inward'), name='unique_workspace_relation_definition_inward_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='workitemrelationdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'outward'), name='unique_workspace_relation_definition_outward_when_not_deleted'),
        ),
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Project Identifier'),
        ),
    ]
