# Generated by Django 5.2.15 on 2026-09-15 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0130_research_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchprojectprofile",
            name="current_stage",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="code_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="code_snapshot_max_mb",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="experiment_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="integration_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="literature_max_entries",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="literature_min_included",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="stage_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="stage_min_reviewers",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="workspaceresearchsetting",
            name="stage_pass_ratio",
            field=models.FloatField(default=0.5),
        ),
        migrations.CreateModel(
            name="ResearchStageInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PRE_OPENING", "Pre-opening"),
                            ("OPENING", "Opening"),
                            ("MIDTERM", "Midterm"),
                            ("FINAL", "Final"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("SUBMITTED", "Submitted"),
                            ("NEEDS_REVISION", "Needs revision"),
                            ("PASSED", "Passed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("passed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gate_result",
                    models.CharField(
                        blank=True,
                        choices=[("PASS", "Pass"), ("BLOCKED", "Blocked"), ("WAIVED", "Waived")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_stage_instances",
                        to="db.orgunit",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_stage_instances",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_stage_instances",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Stage Instance",
                "verbose_name_plural": "Research Stage Instances",
                "db_table": "research_stage_instances",
                "ordering": ("project", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="ResearchStageRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PRE_OPENING", "Pre-opening"),
                            ("OPENING", "Opening"),
                            ("MIDTERM", "Midterm"),
                            ("FINAL", "Final"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("LITERATURE_COUNT", "Literature count"),
                            ("EXPERIMENT_LINKED", "Experiment linked"),
                            ("CODE_REPO", "Code repository"),
                            ("OUTCOME_COUNT", "Outcome count"),
                            ("MATERIAL_SET", "Material set"),
                            ("REVIEW_RULE", "Review rule"),
                        ],
                        max_length=24,
                    ),
                ),
                ("threshold", models.PositiveIntegerField(blank=True, null=True)),
                ("is_blocking", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_stage_requirements",
                        to="db.orgunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_stage_requirements",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Stage Requirement",
                "verbose_name_plural": "Research Stage Requirements",
                "db_table": "research_stage_requirements",
                "ordering": ("stage", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ENTER", "Enter"),
                            ("SUBMIT", "Submit"),
                            ("RETURN", "Return"),
                            ("PASS", "Pass"),
                            ("REOPEN", "Reopen"),
                            ("OVERRIDE", "Override"),
                        ],
                        max_length=32,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True, default="")),
                ("gate_snapshot", models.JSONField(blank=True, default=dict)),
                ("review_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_stage_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="db.researchstageinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Stage Transition",
                "verbose_name_plural": "Research Stage Transitions",
                "db_table": "research_stage_transitions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="researchstageinstance",
            index=models.Index(fields=["workspace", "stage", "status"], name="rsch_stage_ws_stage_st_idx"),
        ),
        migrations.AddIndex(
            model_name="researchstageinstance",
            index=models.Index(fields=["project", "sort_order"], name="rsch_stage_project_order_idx"),
        ),
        migrations.AddIndex(
            model_name="researchstageinstance",
            index=models.Index(fields=["workspace", "status", "updated_at"], name="rsch_stage_ws_status_up_idx"),
        ),
        migrations.AddConstraint(
            model_name="researchstageinstance",
            constraint=models.UniqueConstraint(fields=("project", "stage"), name="rsch_stage_uq_project_stage"),
        ),
        migrations.AddIndex(
            model_name="researchstagerequirement",
            index=models.Index(fields=["workspace", "stage"], name="rsch_req_ws_stage_idx"),
        ),
        migrations.AddConstraint(
            model_name="researchstagerequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org_unit__isnull", True)),
                fields=("workspace", "stage", "code"),
                name="rsch_req_uq_ws_stage_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchstagerequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org_unit__isnull", False)),
                fields=("workspace", "stage", "code", "org_unit"),
                name="rsch_req_uq_ws_stage_code_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(fields=["stage_instance", "created_at"], name="rsch_transition_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(fields=["action"], name="rsch_transition_action_idx"),
        ),
    ]
