# Generated by Django 4.2.24 on 2025-11-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_alter_casereviewrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='state',
        ),
    ]
