# Generated by Django 4.2.29 on 2026-03-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_backfill_relation_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='version',
        ),
        migrations.AddField(
            model_name='webhook',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded')], default='application/json', max_length=255),
        ),
        migrations.AddField(
            model_name='webhook',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='pql_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='webhook',
            name='rich_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='projectidentifier',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WebhookScope',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('module', 'Module'), ('cycle', 'Cycle'), ('milestone', 'Milestone'), ('page', 'Page'), ('page_comment', 'Page Comment'), ('work_item', 'Work Item'), ('work_item_comment', 'Work Item Comment'), ('work_item_link', 'Work Item Link'), ('work_item_vote', 'Work Item Vote'), ('work_item_attachment', 'Work Item Attachment'), ('work_item_relation', 'Work Item Relation'), ('work_item_dependency', 'Work Item Dependency'), ('work_item_page_link', 'Work Item Page Link')], max_length=255)),
                ('version', models.CharField(default='v2', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='db.webhook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Webhook Scope',
                'verbose_name_plural': 'Webhook Scopes',
                'db_table': 'webhook_scopes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status', models.TextField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time in milliseconds.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the request failed.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db.webhook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='webhookscope',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'webhook', 'scope', 'version'), name='webhook_scope_unique_workspace_webhook_scope_version_when_deleted_at_null'),
        ),
    ]
