# Generated by Django 4.2.28 on 2026-03-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_usernotificationpreference_worklog_reminder'),
        ('db', '0131_migrate_none_priority_to_medium'),
    ]

    operations = [
    ]
