# Generated by Django 5.2.15 on 2026-09-15 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0131_research_stages"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageMaterial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("material_type", models.CharField(max_length=48)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("DIRECT_ADVISOR", "Direct advisors"),
                            ("UNIT", "Organisation unit"),
                            ("ANCESTRY", "Ancestry principal investigators"),
                            ("WORKSPACE", "Workspace"),
                            ("CUSTOM", "Custom grants"),
                        ],
                        default="DIRECT_ADVISOR",
                        max_length=32,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_version_no", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_stage_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_stage_materials",
                        to="db.page",
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="db.researchstageinstance",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Stage Material",
                "verbose_name_plural": "Research Stage Materials",
                "db_table": "research_stage_materials",
                "ordering": ("stage_instance", "material_type"),
            },
        ),
        migrations.CreateModel(
            name="StageMaterialVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("version_no", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ADMIN_OVERRIDE", "Admin override"),
                            ("STAGE_REOPEN", "Stage reopen"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("diff_summary", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_stage_material_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="db.stagematerial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Stage Material Version",
                "verbose_name_plural": "Research Stage Material Versions",
                "db_table": "research_stage_material_versions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="stagematerial",
            index=models.Index(fields=["stage_instance", "status"], name="rsch_material_stage_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stagematerial",
            index=models.Index(fields=["owner", "status"], name="rsch_material_owner_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="stagematerial",
            constraint=models.UniqueConstraint(
                fields=("stage_instance", "material_type"), name="rsch_material_uq_stage_type"
            ),
        ),
        migrations.AddIndex(
            model_name="stagematerialversion",
            index=models.Index(fields=["material", "version_no"], name="rsch_material_version_idx"),
        ),
        migrations.AddConstraint(
            model_name="stagematerialversion",
            constraint=models.UniqueConstraint(fields=("material", "version_no"), name="rsch_material_version_uq"),
        ),
    ]
