# Generated by Django 4.2.28 on 2026-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_remove_webhook_version_webhook_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimatepoint',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimatepoint',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='type',
            field=models.CharField(choices=[('categories', 'Categories'), ('points', 'Points'), ('time', 'Time')], default='categories', max_length=255),
        ),
    ]
