# Generated by Django 4.2.24 on 2025-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_remove_plancase_state_remove_testplan_assignees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodule',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='planmodule',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='planmodule',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
