# Generated by Django 4.2.29 on 2026-03-31 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_estimate_external_id_estimate_external_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_reminder_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='webhookscope',
            name='scope',
            field=models.CharField(choices=[('project.created', 'Project Created'), ('project.updated', 'Project Updated'), ('project.archived', 'Project Archived'), ('project.deleted', 'Project Deleted'), ('module.created', 'Module Created'), ('module.updated', 'Module Updated'), ('module.archived', 'Module Archived'), ('module.deleted', 'Module Deleted'), ('cycle.created', 'Cycle Created'), ('cycle.updated', 'Cycle Updated'), ('cycle.archived', 'Cycle Archived'), ('cycle.deleted', 'Cycle Deleted'), ('milestone.created', 'Milestone Created'), ('milestone.updated', 'Milestone Updated'), ('milestone.deleted', 'Milestone Deleted'), ('page.created', 'Page Created'), ('page.updated', 'Page Updated'), ('page.archived', 'Page Archived'), ('page.deleted', 'Page Deleted'), ('page.comment.created', 'Page Comment Created'), ('page.comment.updated', 'Page Comment Updated'), ('page.comment.deleted', 'Page Comment Deleted'), ('workitem.created', 'Work Item Created'), ('workitem.updated', 'Work Item Updated'), ('workitem.archived', 'Work Item Archived'), ('workitem.deleted', 'Work Item Deleted'), ('workitem.comment.created', 'Work Item Comment Created'), ('workitem.comment.updated', 'Work Item Comment Updated'), ('workitem.comment.deleted', 'Work Item Comment Deleted'), ('workitem.link.created', 'Work Item Link Created'), ('workitem.link.updated', 'Work Item Link Updated'), ('workitem.link.deleted', 'Work Item Link Deleted'), ('workitem.vote.created', 'Work Item Vote Created'), ('workitem.vote.updated', 'Work Item Vote Updated'), ('workitem.vote.deleted', 'Work Item Vote Deleted'), ('workitem.attachment.created', 'Work Item Attachment Created'), ('workitem.attachment.updated', 'Work Item Attachment Updated'), ('workitem.attachment.deleted', 'Work Item Attachment Deleted'), ('workitem.relation.created', 'Work Item Relation Created'), ('workitem.relation.updated', 'Work Item Relation Updated'), ('workitem.relation.deleted', 'Work Item Relation Deleted'), ('workitem.dependency.created', 'Work Item Dependency Created'), ('workitem.dependency.updated', 'Work Item Dependency Updated'), ('workitem.dependency.deleted', 'Work Item Dependency Deleted'), ('workitem.page_link.created', 'Work Item Page Link Created'), ('workitem.page_link.updated', 'Work Item Page Link Updated'), ('workitem.page_link.deleted', 'Work Item Page Link Deleted')], max_length=255),
        ),
    ]
