# Generated by Django 5.2.15 on 2026-09-26 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_digest_delivery_and_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Workflow Name')),
                ('description', models.TextField(blank=True, verbose_name='Workflow Description')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flow_type', models.CharField(choices=[('transition', 'Transition'), ('approval', 'Approval')], default='transition', max_length=16)),
                ('sequence', models.FloatField(default=65535)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Flow',
                'verbose_name_plural': 'Workflow Flows',
                'db_table': 'workflow_flows',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowFlowActor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('actor_type', models.CharField(choices=[('ALL_PROJECT_MEMBERS', 'All project members'), ('STATIC_USERS', 'Static users'), ('PROJECT_ROLE', 'Project role'), ('REQUESTER_MANAGER', 'Requester manager'), ('DEPARTMENT_HEAD', 'Department head'), ('PORTAL_ROLE', 'Portal role'), ('PROPERTY_MEMBER', 'Member property')], max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='db.workflowflow')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Flow Actor',
                'verbose_name_plural': 'Workflow Flow Actors',
                'db_table': 'workflow_flow_actors',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_workflow_revisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='db.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Revision',
                'verbose_name_plural': 'Workflow Revisions',
                'db_table': 'workflow_revisions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workflowflow',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='db.workflowrevision'),
        ),
        migrations.CreateModel(
            name='IssueWorkflowBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_bindings_created', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_binding', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_bindings', to='db.workflow')),
                ('migrated_from_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_to_bindings', to='db.workflowrevision')),
                ('workflow_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_bindings', to='db.workflowrevision')),
            ],
            options={
                'verbose_name': 'Issue Workflow Binding',
                'verbose_name_plural': 'Issue Workflow Bindings',
                'db_table': 'issue_workflow_bindings',
                'ordering': ('-bound_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('allow_new_work_items', models.BooleanField(default=False)),
                ('sequence', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='db.workflowrevision')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state_inclusions', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'db_table': 'workflow_states',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='workflowflow',
            name='reject_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_target_flows', to='db.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowflow',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='db.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowflow',
            name='target_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='db.workflowstate'),
        ),
        migrations.CreateModel(
            name='WorkflowTypeAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_assignments', to='db.issuetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignments', to='db.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Type Assignment',
                'verbose_name_plural': 'Workflow Type Assignments',
                'db_table': 'workflow_type_assignments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project', 'is_active', 'is_default'], name='workflows_proj_active_dflt_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='workflows_unique_name_project_when_active'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('project',), name='workflows_unique_default_project_when_active'),
        ),
        migrations.AddIndex(
            model_name='workflowrevision',
            index=models.Index(fields=['workflow', 'status'], name='wf_revisions_wf_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrevision',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='workflow_revisions_unique_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'draft')), fields=('workflow',), name='workflow_revisions_unique_draft_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['revision', 'state'], name='workflow_states_rev_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('revision', 'state'), name='workflow_states_unique_revision_state'),
        ),
        migrations.AddIndex(
            model_name='workflowflow',
            index=models.Index(fields=['revision', 'source_state', 'is_active'], name='workflow_flows_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtypeassignment',
            index=models.Index(fields=['project', 'issue_type'], name='wf_type_assignments_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtypeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type'), name='workflow_type_assignments_unique_project_issue_type'),
        ),
    ]
