# Generated by Django 4.2.24 on 2025-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_remove_planmodule_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='TestPlan Description'),
        ),
    ]
