# Generated by Django 4.2.29 on 2026-04-10 11:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plane.db.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_project_auto_reminder_days_alter_webhookscope_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('namespace', models.CharField(choices=[('instance', 'Instance'), ('workspace', 'Workspace'), ('project', 'Project')], db_index=True, default='workspace', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text="List of permission strings like 'workitem:edit', 'project:*', 'workitem:delete+creator'", size=None)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_schemes', to='db.workspace')),
            ],
            options={
                'db_table': 'permission_schemes',
                'ordering': ['namespace', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('namespace', models.CharField(choices=[('instance', 'Instance'), ('workspace', 'Workspace'), ('project', 'Project')], db_index=True, default='workspace', help_text='Whether this role is for instance, workspace, or project-level resources', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.PositiveSmallIntegerField(default=10)),
                ('is_system', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=65535)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_roles', to='db.role')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['namespace', 'sort_order', 'name'],
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RolePermissionScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('permission_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_schemes', to='db.permissionscheme')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_schemes', to='db.role')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_schemes', to='db.workspace')),
            ],
            options={
                'db_table': 'role_permission_schemes',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permission_schemes',
            field=models.ManyToManyField(blank=True, related_name='roles', through='db.RolePermissionScheme', to='db.permissionscheme'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('teamspace', 'Teamspace')], default='user', max_length=20)),
                ('subject_id', models.UUIDField(db_index=True, help_text='ID of the user or teamspace')),
                ('relation', models.CharField(db_index=True, help_text='The role/relation name (admin, member, guest, or custom role slug)', max_length=50)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(db_index=True, help_text='ID of the resource (workspace, project, issue, etc.)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this permission expires (null = never)', null=True)),
                ('permissions_grant', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Additional permissions granted on this resource', size=None)),
                ('permissions_deny', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Permissions explicitly denied on this resource', size=None)),
                ('condition', models.JSONField(blank=True, help_text='JSON condition for conditional access', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to='db.workspace')),
            ],
            options={
                'db_table': 'resource_permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke'), ('modify', 'Modify')], max_length=20)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('teamspace', 'Teamspace')], max_length=20)),
                ('subject_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('relation_before', models.CharField(blank=True, max_length=50, null=True)),
                ('relation_after', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='db.workspace')),
            ],
            options={
                'db_table': 'permission_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_members', to='db.role'),
        ),
        migrations.AddField(
            model_name='projectmemberinvite',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_member_invites', to='db.role'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='role_ref',
            field=models.ForeignKey(blank=True, help_text='FK to Role. Source of truth for role assignment. Numeric role field derived from this.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspace_members', to='db.role'),
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspace_member_invites', to='db.role'),
        ),
        migrations.AddConstraint(
            model_name='rolepermissionscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('role', 'permission_scheme'), name='unique_active_role_permission_scheme'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace', 'is_system'], name='roles_workspa_29e985_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace', 'namespace'], name='roles_workspa_df2ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['namespace', 'slug'], name='roles_namespa_45c22c_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workspace__isnull', False)), fields=('workspace', 'namespace', 'slug'), name='unique_workspace_namespace_slug'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workspace__isnull', True)), fields=('namespace', 'slug'), name='unique_instance_namespace_slug'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['resource_type', 'resource_id'], name='idx_rp_resource_active'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['workspace', 'resource_type'], name='idx_rp_ws_restype_active'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['workspace', 'relation'], name='idx_rp_ws_relation_active'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('expires_at__isnull', False)), fields=['expires_at'], name='idx_rp_expires_active'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['resource_type', 'resource_id', 'subject_type'], name='idx_rp_res_subjtype_active'),
        ),
        migrations.AddConstraint(
            model_name='resourcepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('subject_type', 'subject_id', 'resource_type', 'resource_id'), name='resource_permission_unique_active_tuple'),
        ),
        migrations.AddIndex(
            model_name='permissionscheme',
            index=models.Index(fields=['workspace', 'is_system'], name='permission__workspa_4ff08f_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionscheme',
            index=models.Index(fields=['workspace', 'namespace'], name='permission__workspa_bc3ea8_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workspace__isnull', False)), fields=('workspace', 'namespace', 'slug'), name='unique_workspace_ps_namespace_slug'),
        ),
        migrations.AddConstraint(
            model_name='permissionscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workspace__isnull', True)), fields=('namespace', 'slug'), name='unique_system_ps_namespace_slug'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['workspace', 'action'], name='permission__workspa_bea588_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='permission__actor_i_cc9c27_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='permission__resourc_7e530b_idx'),
        ),
        migrations.CreateModel(
            name='RoleActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('field', models.CharField(blank=True, choices=[('name', 'Name'), ('description', 'Description'), ('level', 'Level'), ('status', 'Status'), ('sort_order', 'Sort Order'), ('based_on', 'Based On'), ('permission_scheme', 'Permission Scheme')], max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('old_identifier', models.UUIDField(blank=True, null=True)),
                ('new_identifier', models.UUIDField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.role')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_activities', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Role Activity',
                'verbose_name_plural': 'Role Activities',
                'db_table': 'role_activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['role', '-created_at'], name='role_activi_role_id_115741_idx'), models.Index(fields=['workspace', '-created_at'], name='role_activi_workspa_0bb86e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionSchemeActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('field', models.CharField(blank=True, choices=[('name', 'Name'), ('description', 'Description'), ('permissions', 'Permissions'), ('sort_order', 'Sort Order')], max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_scheme_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('permission_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.permissionscheme')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_scheme_activities', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Permission Scheme Activity',
                'verbose_name_plural': 'Permission Scheme Activities',
                'db_table': 'permission_scheme_activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['permission_scheme', '-created_at'], name='permission__permiss_644247_idx'), models.Index(fields=['workspace', '-created_at'], name='permission__workspa_eb026e_idx')],
            },
        ),
    ]
