# Generated by Django 5.2.15 on 2026-09-15 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_research_experiments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCodeRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('GITEA', 'Gitea'), ('LOCAL_GIT', 'Local git'), ('OTHER', 'Other')], default='GITHUB', max_length=16)),
                ('repository_url', models.URLField(max_length=500)),
                ('repository_slug', models.CharField(blank=True, default='', max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=128)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SYNC_FAILED', 'Sync failed')], default='ACTIVE', max_length=16)),
                ('credential_ref', models.CharField(blank=True, default='', max_length=128)),
                ('last_synced_commit', models.CharField(blank=True, default='', max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_code_repositories', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_code_repositories', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Code Repository',
                'verbose_name_plural': 'Project Code Repositories',
                'db_table': 'research_code_repositories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ref_type', models.CharField(choices=[('COMMIT', 'Commit'), ('BRANCH', 'Branch'), ('TAG', 'Tag'), ('SNAPSHOT', 'Snapshot')], max_length=16)),
                ('ref_value', models.CharField(max_length=255)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('linked_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_artifacts', to='db.experimentrecord')),
                ('snapshot_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_code_snapshots', to='db.fileasset')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='db.projectcoderepository')),
            ],
            options={
                'verbose_name': 'Code Artifact',
                'verbose_name_plural': 'Code Artifacts',
                'db_table': 'research_code_artifacts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='projectcoderepository',
            index=models.Index(fields=['workspace', 'status'], name='rsch_code_repo_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcoderepository',
            index=models.Index(fields=['project', 'provider'], name='rsch_code_repo_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcoderepository',
            constraint=models.UniqueConstraint(fields=('project', 'repository_url'), name='rsch_code_repo_uq_project_url'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['repository', 'ref_type', 'committed_at'], name='rsch_code_artifact_repo_idx'),
        ),
        migrations.AddConstraint(
            model_name='codeartifact',
            constraint=models.UniqueConstraint(fields=('repository', 'ref_type', 'ref_value'), name='rsch_code_artifact_uq_ref'),
        ),
    ]
