# Generated by Django 4.2.24 on 2025-11-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_testplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='begin_time',
            field=models.DateField(blank=True, null=True, verbose_name='TestPlan Begin Time'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='TestPlan End Time'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='result',
            field=models.CharField(default='-', max_length=30, verbose_name='TestPlan execute result'),
        ),
    ]
