# Generated by Django 4.2.27 on 2026-01-30 09:10

# Migration: Backfill namespace-scoped roles and permissions
# Optimized for large datasets with batch processing and minimal memory usage

import time
from datetime import datetime
from django.db import migrations, models
from django.utils import timezone


def log(message, level="INFO"):
    """Log with timestamp and level."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] [{level}] {message}")


def format_duration(seconds):
    """Format duration in human-readable format."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    elif seconds < 3600:
        minutes = seconds // 60
        secs = seconds % 60
        return f"{int(minutes)}m {int(secs)}s"
    else:
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        return f"{int(hours)}h {int(minutes)}m"


def format_number(num):
    """Format number with commas for readability."""
    return f"{num:,}"


# ---------------------------------------------------------------------------
# Import role definitions from the permissions module (single source of truth)
# ---------------------------------------------------------------------------
from plane.permissions.system_roles import (
    ROLE_SLUG_MAP as ROLE_MAP,
    PROJECT_ROLE_SLUG_MAP as PROJECT_ROLE_MAP,
    SYSTEM_ROLES,
)


def _roles_to_migration_format(roles_dict: dict, namespace: str) -> list[dict]:
    """
    Convert system_roles dict format to the list-of-dicts the migration expects.

    system_roles format:  {"admin": {"level": 20, "sort_order": 200, "permission_schemes": [...], "description": "..."}}
    migration format:     [{"slug": "admin", "name": "Admin", "level": 20, ...}]
    """
    result = []
    for slug, config in roles_dict.items():
        result.append({
            "slug": slug,
            "name": slug.title(),
            "level": config["level"],
            "sort_order": config["sort_order"],
            "description": config["description"],
        })
    return result


INSTANCE_ROLES = _roles_to_migration_format(SYSTEM_ROLES["instance"], "instance")
WORKSPACE_ROLES = _roles_to_migration_format(SYSTEM_ROLES["workspace"], "workspace")
PROJECT_ROLES = _roles_to_migration_format(SYSTEM_ROLES["project"], "project")

# Batch size for bulk operations
BATCH_SIZE = 5000


def _chunked_iterator(queryset, chunk_size=BATCH_SIZE, cutoff_time=None):
    """
    Iterate over a queryset in chunks to avoid loading everything into memory.

    Uses created_at ordering with a cutoff timestamp for consistency during
    concurrent modifications. Records created after cutoff_time are excluded
    (they'll be handled by the model's save() sync mechanism).

    Args:
        queryset: The base queryset to iterate
        chunk_size: Number of records per batch
        cutoff_time: Only process records created before this time (required)
    """
    if cutoff_time is None:
        raise ValueError("cutoff_time is required for consistent iteration")

    # Filter to records created before cutoff and order by created_at, then pk for determinism
    base_qs = queryset.filter(created_at__lt=cutoff_time).order_by("created_at", "pk")

    last_created_at = None
    last_pk = None

    while True:
        qs = base_qs

        # Keyset pagination using (created_at, pk) composite key
        if last_created_at is not None:
            qs = qs.filter(
                models.Q(created_at__gt=last_created_at) |
                models.Q(created_at=last_created_at, pk__gt=last_pk)
            )

        chunk = list(qs[:chunk_size])
        if not chunk:
            break

        yield chunk

        last_record = chunk[-1]
        last_created_at = last_record.created_at
        last_pk = last_record.pk


def forwards_func(apps, schema_editor):
    """
    Backfill namespace-scoped roles and permissions.

    Optimizations:
    - Bulk create roles instead of get_or_create in loop
    - Stream members using chunked iteration (low memory)
    - Batch bulk_create with ignore_conflicts
    - Use only() to fetch minimal fields
    """
    migration_start = time.time()
    stats = {
        "workspaces": 0,
        "roles_created": 0,
        "stale_owners_transferred": 0,
        "workspace_permissions": 0,
        "ws_role_ref_backfill": 0,
        "project_permissions": 0,
        "proj_role_ref_backfill": 0,
        "teamspace_memberships": 0,
        "teamspace_project_links": 0,
        "invite_role_ref_backfill": 0,
        "m2m_links_created": 0,
    }

    log("=" * 70)
    log("Starting permission system backfill migration")
    log("=" * 70)

    # Set cutoff time at the start - only process records created before this time.
    # Records created after this point will be handled by the model's save() sync.
    cutoff_time = timezone.now()
    log(f"Cutoff time: {cutoff_time.isoformat()} (records created after this will be synced via model save)")

    Workspace = apps.get_model("db", "Workspace")
    Role = apps.get_model("db", "Role")
    WorkspaceMember = apps.get_model("db", "WorkspaceMember")
    ProjectMember = apps.get_model("db", "ProjectMember")
    ResourcePermission = apps.get_model("db", "ResourcePermission")

    # =========================================================================
    # 1. Create instance-level roles (workspace=NULL) - only 1 role
    # =========================================================================
    step_start = time.time()
    log("STEP 1/8: Creating instance-level roles...")

    for role_data in INSTANCE_ROLES:
        Role.objects.get_or_create(
            workspace=None,
            namespace="instance",
            slug=role_data["slug"],
            defaults={
                "name": role_data["name"],
                "level": role_data["level"],
                "sort_order": role_data["sort_order"],
                "description": role_data["description"],
                "is_system": True,
            },
        )

    log(f"STEP 1/8: Completed in {format_duration(time.time() - step_start)}")

    # =========================================================================
    # 2. Bulk create workspace and project roles for all workspaces
    # =========================================================================
    step_start = time.time()
    log("STEP 2/8: Creating workspace and project roles...")

    # Get all workspace IDs first (just IDs, minimal memory)
    workspace_ids = list(
        Workspace.objects.filter(deleted_at__isnull=True)
        .values_list("id", flat=True)
    )
    stats["workspaces"] = len(workspace_ids)
    log(f"  Found {format_number(len(workspace_ids))} active workspaces")

    # Build all roles in memory (7 roles per workspace is manageable)
    all_roles = []
    for ws_id in workspace_ids:
        # Workspace-scoped roles
        for role_data in WORKSPACE_ROLES:
            all_roles.append(
                Role(
                    workspace_id=ws_id,
                    namespace="workspace",
                    slug=role_data["slug"],
                    name=role_data["name"],
                    level=role_data["level"],
                    sort_order=role_data["sort_order"],
                    description=role_data["description"],
                    is_system=True,
                )
            )
        # Project-scoped roles
        for role_data in PROJECT_ROLES:
            all_roles.append(
                Role(
                    workspace_id=ws_id,
                    namespace="project",
                    slug=role_data["slug"],
                    name=role_data["name"],
                    level=role_data["level"],
                    sort_order=role_data["sort_order"],
                    description=role_data["description"],
                    is_system=True,
                )
            )

    log(f"  Prepared {format_number(len(all_roles))} role records for bulk insert")

    # Bulk create with ignore_conflicts (idempotent)
    if all_roles:
        Role.objects.bulk_create(
            all_roles,
            ignore_conflicts=True,
            batch_size=BATCH_SIZE,
        )
    stats["roles_created"] = len(all_roles)

    log(f"STEP 2/8: Created {format_number(len(all_roles))} roles in {format_duration(time.time() - step_start)}")

    # Pre-cache all system Role PKs for role_ref backfill: (workspace_id, namespace, slug) → role_id
    role_cache = {}
    for r in Role.objects.filter(is_system=True, deleted_at__isnull=True).values("id", "workspace_id", "namespace", "slug"):
        role_cache[(r["workspace_id"], r["namespace"], r["slug"])] = r["id"]
    log(f"  Cached {format_number(len(role_cache))} system role IDs for role_ref backfill")

    # =========================================================================
    # 2.5. Seed system PermissionSchemes and create M2M links
    # =========================================================================
    step_start = time.time()
    log("STEP 2.5/8: Seeding system permission schemes and M2M links...")

    from plane.permissions.system_roles import _seed_system_permission_schemes
    PermissionScheme = apps.get_model("db", "PermissionScheme")
    RolePermissionScheme = apps.get_model("db", "RolePermissionScheme")

    # 8 upserts — one per system PS (global, workspace=NULL)
    _seed_system_permission_schemes()

    # PS lookup: (namespace, slug) -> ps_id — only 8 entries
    system_ps_map = {
        (ps["namespace"], ps["slug"]): ps["id"]
        for ps in PermissionScheme.objects.filter(
            workspace__isnull=True, is_system=True, deleted_at__isnull=True,
        ).values("id", "namespace", "slug")
    }
    log(f"  Seeded {len(system_ps_map)} system permission schemes")

    # Build M2M links in chunks from role_cache to keep memory bounded.
    # role_cache has (ws_id, namespace, slug) -> role_id for all 1.2M+ roles.
    # Each system role maps 1:1 to a PS of the same (namespace, slug).
    m2m_count = 0
    m2m_batch = []
    for (ws_id, namespace, slug), role_id in role_cache.items():
        ps_id = system_ps_map.get((namespace, slug))
        if ps_id is None:
            continue
        m2m_batch.append(
            RolePermissionScheme(
                workspace_id=ws_id,
                role_id=role_id,
                permission_scheme_id=ps_id,
            )
        )
        if len(m2m_batch) >= BATCH_SIZE:
            RolePermissionScheme.objects.bulk_create(
                m2m_batch, ignore_conflicts=True, batch_size=BATCH_SIZE,
            )
            m2m_count += len(m2m_batch)
            m2m_batch = []

    if m2m_batch:
        RolePermissionScheme.objects.bulk_create(
            m2m_batch, ignore_conflicts=True, batch_size=BATCH_SIZE,
        )
        m2m_count += len(m2m_batch)

    stats["m2m_links_created"] = m2m_count
    log(f"STEP 2.5/8: Created {format_number(m2m_count)} role-PS links in {format_duration(time.time() - step_start)}")

    # Pre-fetch workspace plan tiers for owner relation logic
    try:
        WorkspaceLicense = apps.get_model("ee", "WorkspaceLicense")
        free_pro_one_ws_ids = set(
            WorkspaceLicense.objects.filter(
                plan__in=["FREE", "PRO", "ONE"]
            ).values_list("workspace_id", flat=True)
        )
        log(f"  Found {format_number(len(free_pro_one_ws_ids))} Free/Pro/One workspaces (all admins → owner)")
    except LookupError:
        free_pro_one_ws_ids = set()
        log("  WorkspaceLicense model not found — treating all workspaces as Business/Enterprise")

    # =========================================================================
    # 3. Fix stale workspace owners (owner left but FK not updated)
    # =========================================================================
    step_start = time.time()
    log("STEP 3/8: Fixing stale workspace ownerships...")

    # Single query to find workspaces where owner is NOT an active member
    from django.db.models import Exists, OuterRef

    active_owner_subquery = WorkspaceMember.objects.filter(
        workspace_id=OuterRef("id"),
        member_id=OuterRef("owner_id"),
        is_active=True,
        deleted_at__isnull=True,
    )
    stale_owner_workspaces = (
        Workspace.objects.filter(deleted_at__isnull=True)
        .exclude(Exists(active_owner_subquery))
        .only("id", "owner_id")
    )

    transferred = 0
    for ws in stale_owner_workspaces:
        # Try active admins (role=20) first
        new_owner_member = (
            WorkspaceMember.objects
            .filter(workspace_id=ws.id, role=20, is_active=True, deleted_at__isnull=True)
            .order_by("created_at")
            .first()
        )
        if not new_owner_member:
            # Fall back to highest-role active member
            new_owner_member = (
                WorkspaceMember.objects
                .filter(workspace_id=ws.id, is_active=True, deleted_at__isnull=True)
                .order_by("-role", "created_at")
                .first()
            )
        if new_owner_member:
            ws.owner_id = new_owner_member.member_id
            ws.save(update_fields=["owner"])
            # Promote to role=20 if needed (so step 4's role=20 branch catches them)
            if new_owner_member.role != 20:
                log(f"  Workspace {ws.id}: promoted member {new_owner_member.member_id} from role={new_owner_member.role} to role=20")
                new_owner_member.role = 20
                new_owner_member.save(update_fields=["role"])
            transferred += 1
        else:
            log(f"  Workspace {ws.id} has no active members — cannot assign owner", level="WARN")

    stats["stale_owners_transferred"] = transferred
    log(f"  Transferred {transferred} stale workspace ownerships")
    log(f"STEP 3/8: Completed in {format_duration(time.time() - step_start)}")

    # Pre-fetch FK owner mapping for Business/Enterprise (role=20 resolution)
    biz_ent_ws_ids = set(workspace_ids) - free_pro_one_ws_ids
    owner_map = dict(
        Workspace.objects.filter(id__in=biz_ent_ws_ids, deleted_at__isnull=True)
        .values_list("id", "owner_id")
    ) if biz_ent_ws_ids else {}

    # =========================================================================
    # 4. Backfill workspace permissions + role_ref (single pass)
    # =========================================================================
    step_start = time.time()
    log("STEP 4/8: Backfilling workspace permissions and role_ref...")

    # Count total for progress reporting (only records before cutoff)
    total_ws_members = WorkspaceMember.objects.filter(
        is_active=True, deleted_at__isnull=True, created_at__lt=cutoff_time
    ).count()
    log(f"  Found {format_number(total_ws_members)} active workspace members to process")

    ws_perm_count = 0
    ws_ref_count = 0
    batch_num = 0

    ws_members_qs = (
        WorkspaceMember.objects
        .filter(is_active=True, deleted_at__isnull=True)
        .only("id", "workspace_id", "member_id", "role", "role_ref_id", "created_at")
    )

    for chunk in _chunked_iterator(ws_members_qs, BATCH_SIZE, cutoff_time=cutoff_time):
        batch_start = time.time()
        batch_num += 1
        ws_perms = []
        ref_updates = []

        for wm in chunk:
            role_slug = ROLE_MAP.get(wm.role, "guest")
            # Plan-aware role=20 resolution (mirrors _resolve_admin_or_owner)
            if wm.role == 20:
                if wm.workspace_id in free_pro_one_ws_ids:
                    # Free/Pro/One: all role=20 → "owner"
                    role_slug = "owner"
                elif wm.member_id == owner_map.get(wm.workspace_id):
                    # Business/Enterprise: FK owner → "owner"
                    role_slug = "owner"

            ws_perms.append(
                ResourcePermission(
                    workspace_id=wm.workspace_id,
                    subject_type="user",
                    subject_id=wm.member_id,
                    resource_type="workspace",
                    resource_id=wm.workspace_id,
                    relation=role_slug,
                )
            )

            # Set role_ref if not already set
            if not wm.role_ref_id:
                role_id = role_cache.get((wm.workspace_id, "workspace", role_slug))
                if role_id:
                    wm.role_ref_id = role_id
                    ref_updates.append(wm)

        if ws_perms:
            ResourcePermission.objects.bulk_create(
                ws_perms, ignore_conflicts=True, batch_size=BATCH_SIZE
            )
            ws_perm_count += len(ws_perms)

            progress = (ws_perm_count / total_ws_members * 100) if total_ws_members > 0 else 100
            batch_time = time.time() - batch_start
            rate = len(ws_perms) / batch_time if batch_time > 0 else 0

            log(f"  Batch {batch_num}: {format_number(ws_perm_count)}/{format_number(total_ws_members)} "
                f"({progress:.1f}%) - {format_number(int(rate))} records/sec")

        if ref_updates:
            WorkspaceMember.objects.bulk_update(ref_updates, ["role_ref_id"], batch_size=BATCH_SIZE)
            ws_ref_count += len(ref_updates)

    stats["workspace_permissions"] = ws_perm_count
    stats["ws_role_ref_backfill"] = ws_ref_count
    log(f"STEP 4/8: Completed {format_number(ws_perm_count)} permissions + {format_number(ws_ref_count)} role_refs in {format_duration(time.time() - step_start)}")

    # =========================================================================
    # 5. Backfill project permissions + role_ref (single pass)
    # =========================================================================
    step_start = time.time()
    log("STEP 5/8: Backfilling project permissions and role_ref...")

    # Count total for progress reporting (only records before cutoff)
    total_proj_members = ProjectMember.objects.filter(
        is_active=True, deleted_at__isnull=True, member__isnull=False, created_at__lt=cutoff_time
    ).count()
    log(f"  Found {format_number(total_proj_members)} active project members to process")

    proj_perm_count = 0
    proj_ref_count = 0
    batch_num = 0

    proj_members_qs = (
        ProjectMember.objects
        .filter(is_active=True, deleted_at__isnull=True, member__isnull=False)
        .only("id", "workspace_id", "project_id", "member_id", "role", "role_ref_id", "created_at")
    )

    for chunk in _chunked_iterator(proj_members_qs, BATCH_SIZE, cutoff_time=cutoff_time):
        batch_start = time.time()
        batch_num += 1
        proj_perms = []
        ref_updates = []

        for pm in chunk:
            role_slug = PROJECT_ROLE_MAP.get(pm.role, "guest")

            proj_perms.append(
                ResourcePermission(
                    workspace_id=pm.workspace_id,
                    subject_type="user",
                    subject_id=pm.member_id,
                    resource_type="project",
                    resource_id=pm.project_id,
                    relation=role_slug,
                )
            )

            # Set role_ref if not already set
            if not pm.role_ref_id:
                role_id = role_cache.get((pm.workspace_id, "project", role_slug))
                if role_id:
                    pm.role_ref_id = role_id
                    ref_updates.append(pm)

        if proj_perms:
            ResourcePermission.objects.bulk_create(
                proj_perms, ignore_conflicts=True, batch_size=BATCH_SIZE
            )
            proj_perm_count += len(proj_perms)

            progress = (proj_perm_count / total_proj_members * 100) if total_proj_members > 0 else 100
            batch_time = time.time() - batch_start
            rate = len(proj_perms) / batch_time if batch_time > 0 else 0

            log(f"  Batch {batch_num}: {format_number(proj_perm_count)}/{format_number(total_proj_members)} "
                f"({progress:.1f}%) - {format_number(int(rate))} records/sec")

        if ref_updates:
            ProjectMember.objects.bulk_update(ref_updates, ["role_ref_id"], batch_size=BATCH_SIZE)
            proj_ref_count += len(ref_updates)

    stats["project_permissions"] = proj_perm_count
    stats["proj_role_ref_backfill"] = proj_ref_count
    log(f"STEP 5/8: Completed {format_number(proj_perm_count)} permissions + {format_number(proj_ref_count)} role_refs in {format_duration(time.time() - step_start)}")

    # =========================================================================
    # 6. Backfill ResourcePermission from TeamspaceMember (user→teamspace)
    # =========================================================================
    step_start = time.time()
    log("STEP 6/8: Backfilling teamspace membership permissions...")

    try:
        TeamspaceMember = apps.get_model("ee", "TeamspaceMember")

        total_ts_members = TeamspaceMember.objects.filter(
            deleted_at__isnull=True, created_at__lt=cutoff_time
        ).count()
        log(f"  Found {format_number(total_ts_members)} active teamspace members to process")

        ts_member_count = 0
        batch_num = 0

        ts_members_qs = TeamspaceMember.objects.filter(deleted_at__isnull=True).only(
            "id", "workspace_id", "member_id", "team_space_id", "created_at"
        )

        for chunk in _chunked_iterator(ts_members_qs, BATCH_SIZE, cutoff_time=cutoff_time):
            batch_start = time.time()
            batch_num += 1
            ts_perms = []

            for tm in chunk:
                ts_perms.append(
                    ResourcePermission(
                        workspace_id=tm.workspace_id,
                        subject_type="user",
                        subject_id=tm.member_id,
                        resource_type="teamspace",
                        resource_id=tm.team_space_id,
                        relation="member",
                    )
                )

            if ts_perms:
                ResourcePermission.objects.bulk_create(
                    ts_perms, ignore_conflicts=True, batch_size=BATCH_SIZE
                )
                ts_member_count += len(ts_perms)

                progress = (ts_member_count / total_ts_members * 100) if total_ts_members > 0 else 100
                batch_time = time.time() - batch_start
                rate = len(ts_perms) / batch_time if batch_time > 0 else 0

                log(f"  Batch {batch_num}: {format_number(ts_member_count)}/{format_number(total_ts_members)} "
                    f"({progress:.1f}%) - {format_number(int(rate))} records/sec")

        stats["teamspace_memberships"] = ts_member_count
        log(f"STEP 6/8: Completed {format_number(ts_member_count)} teamspace memberships in {format_duration(time.time() - step_start)}")
    except LookupError:
        log("STEP 6/8: Skipping - TeamspaceMember model not found (EE module not installed)")
        stats["teamspace_memberships"] = 0

    # =========================================================================
    # 7. Backfill ResourcePermission from TeamspaceProject (teamspace→project links)
    # =========================================================================
    step_start = time.time()
    log("STEP 7/8: Backfilling teamspace-project link permissions...")

    try:
        TeamspaceProject = apps.get_model("ee", "TeamspaceProject")

        total_ts_projects = TeamspaceProject.objects.filter(
            deleted_at__isnull=True, created_at__lt=cutoff_time
        ).count()
        log(f"  Found {format_number(total_ts_projects)} active teamspace-project links to process")

        ts_project_count = 0
        batch_num = 0

        ts_projects_qs = TeamspaceProject.objects.filter(deleted_at__isnull=True).only(
            "id", "workspace_id", "team_space_id", "project_id", "created_at"
        )

        for chunk in _chunked_iterator(ts_projects_qs, BATCH_SIZE, cutoff_time=cutoff_time):
            batch_start = time.time()
            batch_num += 1
            link_tuples = []

            for tp in chunk:
                link_tuples.append(
                    ResourcePermission(
                        workspace_id=tp.workspace_id,
                        subject_type="teamspace",  # Subject is teamspace!
                        subject_id=tp.team_space_id,
                        resource_type="project",
                        resource_id=tp.project_id,
                        relation="contributor",
                    )
                )

            if link_tuples:
                ResourcePermission.objects.bulk_create(
                    link_tuples, ignore_conflicts=True, batch_size=BATCH_SIZE
                )
                ts_project_count += len(link_tuples)

                progress = (ts_project_count / total_ts_projects * 100) if total_ts_projects > 0 else 100
                batch_time = time.time() - batch_start
                rate = len(link_tuples) / batch_time if batch_time > 0 else 0

                log(f"  Batch {batch_num}: {format_number(ts_project_count)}/{format_number(total_ts_projects)} "
                    f"({progress:.1f}%) - {format_number(int(rate))} records/sec")

        stats["teamspace_project_links"] = ts_project_count
        log(f"STEP 7/8: Completed {format_number(ts_project_count)} teamspace-project links in {format_duration(time.time() - step_start)}")
    except LookupError:
        log("STEP 7/8: Skipping - TeamspaceProject model not found (EE module not installed)")
        stats["teamspace_project_links"] = 0

    # =========================================================================
    # 8. Backfill role_ref FK on invitation tables
    # =========================================================================
    step_start = time.time()
    log("STEP 8/8: Backfilling role_ref on invitation tables...")

    WorkspaceMemberInvite = apps.get_model("db", "WorkspaceMemberInvite")
    ProjectMemberInvite = apps.get_model("db", "ProjectMemberInvite")

    ws_invite_count = 0
    ws_invites_qs = (
        WorkspaceMemberInvite.objects
        .filter(deleted_at__isnull=True, role_ref__isnull=True)
        .only("id", "workspace_id", "role", "created_at")
    )
    for chunk in _chunked_iterator(ws_invites_qs, BATCH_SIZE, cutoff_time=cutoff_time):
        for inv in chunk:
            role_slug = ROLE_MAP.get(inv.role, "guest")
            # Plan-aware: Free/Pro/One role=20 → "owner" (no Admin on these plans)
            if inv.role == 20 and inv.workspace_id in free_pro_one_ws_ids:
                role_slug = "owner"
            role_id = role_cache.get((inv.workspace_id, "workspace", role_slug))
            if role_id:
                inv.role_ref_id = role_id
        WorkspaceMemberInvite.objects.bulk_update(chunk, ["role_ref_id"], batch_size=BATCH_SIZE)
        ws_invite_count += len(chunk)

    proj_invite_count = 0
    proj_invites_qs = (
        ProjectMemberInvite.objects
        .filter(deleted_at__isnull=True, role_ref__isnull=True)
        .only("id", "workspace_id", "role", "created_at")
    )
    for chunk in _chunked_iterator(proj_invites_qs, BATCH_SIZE, cutoff_time=cutoff_time):
        for inv in chunk:
            role_slug = PROJECT_ROLE_MAP.get(inv.role, "guest")
            role_id = role_cache.get((inv.workspace_id, "project", role_slug))
            if role_id:
                inv.role_ref_id = role_id
        ProjectMemberInvite.objects.bulk_update(chunk, ["role_ref_id"], batch_size=BATCH_SIZE)
        proj_invite_count += len(chunk)

    stats["invite_role_ref_backfill"] = ws_invite_count + proj_invite_count
    log(f"STEP 8/8: Backfilled {format_number(ws_invite_count)} workspace + {format_number(proj_invite_count)} project invite role_refs in {format_duration(time.time() - step_start)}")

    # =========================================================================
    # Summary
    # =========================================================================
    total_duration = time.time() - migration_start

    log("=" * 70)
    log("MIGRATION COMPLETE - Summary")
    log("=" * 70)
    log(f"  Workspaces processed:       {format_number(stats['workspaces'])}")
    log(f"  Roles created:              {format_number(stats['roles_created'])}")
    log(f"  Stale owners transferred:   {format_number(stats['stale_owners_transferred'])}")
    log(f"  Workspace permissions:      {format_number(stats['workspace_permissions'])}")
    log(f"  WS member role_refs:        {format_number(stats['ws_role_ref_backfill'])}")
    log(f"  Project permissions:        {format_number(stats['project_permissions'])}")
    log(f"  Proj member role_refs:      {format_number(stats['proj_role_ref_backfill'])}")
    log(f"  Teamspace memberships:      {format_number(stats['teamspace_memberships'])}")
    log(f"  Teamspace-project links:    {format_number(stats['teamspace_project_links'])}")
    log(f"  Invite role_refs:           {format_number(stats['invite_role_ref_backfill'])}")
    log(f"  Role-PS M2M links:          {format_number(stats['m2m_links_created'])}")
    total_records = (
        stats['roles_created'] +
        stats['workspace_permissions'] +
        stats['project_permissions'] +
        stats['teamspace_memberships'] +
        stats['teamspace_project_links']
    )
    log(f"  Total records created:      {format_number(total_records)}")
    log(f"  Total duration:             {format_duration(total_duration)}")
    log("=" * 70)


def _chunked_delete(queryset, chunk_size=BATCH_SIZE):
    """Delete a large queryset in chunks to stay within query timeout limits."""
    total = 0
    while True:
        # Get PKs for next chunk (bounded subquery avoids locking the full table)
        pks = list(queryset.values_list("pk", flat=True)[:chunk_size])
        if not pks:
            break
        deleted, _ = queryset.model.objects.filter(pk__in=pks).delete()
        total += deleted
    return total


def _chunked_update_null(queryset, field, chunk_size=BATCH_SIZE):
    """Set a field to NULL in chunks to stay within query timeout limits."""
    total = 0
    while True:
        pks = list(
            queryset.filter(**{f"{field}__isnull": False})
            .values_list("pk", flat=True)[:chunk_size]
        )
        if not pks:
            break
        updated = queryset.model.objects.filter(pk__in=pks).update(**{field: None})
        total += updated
    return total


def backwards_func(apps, schema_editor):
    """
    Reverse the backfill.

    All deletes/updates are chunked to stay within the 2-minute RDS query timeout.
    """
    migration_start = time.time()

    log("=" * 70)
    log("Starting permission system backfill ROLLBACK")
    log("=" * 70, level="WARN")

    Role = apps.get_model("db", "Role")
    ResourcePermission = apps.get_model("db", "ResourcePermission")
    WorkspaceMember = apps.get_model("db", "WorkspaceMember")
    ProjectMember = apps.get_model("db", "ProjectMember")
    WorkspaceMemberInvite = apps.get_model("db", "WorkspaceMemberInvite")
    ProjectMemberInvite = apps.get_model("db", "ProjectMemberInvite")
    PermissionScheme = apps.get_model("db", "PermissionScheme")

    # Clear role_ref before deleting system Roles (FK constraint)
    step_start = time.time()
    log("STEP 1/4: Clearing role_ref on member and invite tables...")
    cleared = 0
    cleared += _chunked_update_null(WorkspaceMember.objects.all(), "role_ref")
    cleared += _chunked_update_null(ProjectMember.objects.all(), "role_ref")
    cleared += _chunked_update_null(WorkspaceMemberInvite.objects.all(), "role_ref")
    cleared += _chunked_update_null(ProjectMemberInvite.objects.all(), "role_ref")
    log(f"STEP 1/4: Cleared {format_number(cleared)} role_refs in {format_duration(time.time() - step_start)}")

    # Delete backfilled permissions (chunked)
    step_start = time.time()
    log("STEP 2/4: Deleting backfilled permissions...")
    perm_filter = (
        models.Q(resource_type__in=["workspace", "project"], subject_type="user") |
        models.Q(resource_type="teamspace", subject_type="user") |
        models.Q(resource_type="project", subject_type="teamspace")
    )
    deleted_perms = _chunked_delete(ResourcePermission.objects.filter(perm_filter))
    log(f"STEP 2/4: Deleted {format_number(deleted_perms)} permissions in {format_duration(time.time() - step_start)}")

    # Delete system roles (chunked — CASCADE handles RolePermissionScheme per chunk)
    step_start = time.time()
    log("STEP 3/4: Deleting system roles and M2M links...")
    deleted_roles = _chunked_delete(Role.objects.filter(is_system=True))
    log(f"STEP 3/4: Deleted {format_number(deleted_roles)} roles in {format_duration(time.time() - step_start)}")

    # Delete system permission schemes (only 8 rows — no chunking needed)
    step_start = time.time()
    log("STEP 4/4: Deleting system permission schemes...")
    deleted_ps, _ = PermissionScheme.objects.filter(is_system=True).delete()
    log(f"STEP 4/4: Deleted {format_number(deleted_ps)} permission schemes in {format_duration(time.time() - step_start)}")

    log("=" * 70)
    log(f"ROLLBACK COMPLETE in {format_duration(time.time() - migration_start)}")
    log("=" * 70)


class Migration(migrations.Migration):
    """
    Backfill namespace-scoped roles and permissions from existing data.

    This migration:
    1. Creates instance-level system role (admin) with workspace=NULL
    2. Creates workspace/project system roles for all workspaces
    3. Fixes stale workspace owners (inactive FK → promote highest-role active member)
    4. Backfills workspace ResourcePermission + role_ref (single pass, plan-aware owner resolution)
    5. Backfills project ResourcePermission + role_ref (single pass)
    6. Backfills ResourcePermission from TeamspaceMember (user→teamspace tuples)
    7. Backfills ResourcePermission from TeamspaceProject (teamspace→project link tuples)
    8. Backfills role_ref on invitation tables (workspace + project)
    """

    atomic = False

    dependencies = [
        ('db', '0135_resourcepermission_permissionauditlog_role_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
