# Generated by Django 4.2.24 on 2025-11-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_alter_testplan_begin_time_alter_testplan_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_case',
        ),
    ]
