# Generated by Django 4.2.28 on 2026-03-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_remove_default_labels_from_projects'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='issueworklog',
            new_name='issue_workl_issue_i_424c6b_idx',
            old_name='issue_workl_issue_i_idx',
        ),
        migrations.RenameIndex(
            model_name='issueworklog',
            new_name='issue_workl_project_1bde2d_idx',
            old_name='issue_workl_project_idx',
        ),
    ]
