# Generated by Django 5.2.15 on 2026-09-15 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_research_stage_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('output_type', models.CharField(choices=[('PAPER', 'Paper'), ('PATENT', 'Patent'), ('SOFTWARE', 'Software'), ('DATASET', 'Dataset'), ('AWARD', 'Award'), ('OTHER', 'Other')], default='PAPER', max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DIRECT_ADVISOR', 'Direct advisors'), ('UNIT', 'Organisation unit'), ('ANCESTRY', 'Ancestry principal investigators'), ('WORKSPACE', 'Workspace'), ('CUSTOM', 'Custom grants')], default='DIRECT_ADVISOR', max_length=32)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_outcomes', to='db.fileasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_outcomes', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_outcomes', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research Outcome',
                'verbose_name_plural': 'Research Outcomes',
                'db_table': 'research_outcomes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResearchOutcomeLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_type', models.CharField(choices=[('EXPERIMENT_RECORD', 'Experiment record'), ('CODE_ARTIFACT', 'Code artifact'), ('STAGE_MATERIAL', 'Stage material'), ('PERIODIC_REPORT', 'Periodic report')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='db.researchoutcome')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Research Outcome Link',
                'verbose_name_plural': 'Research Outcome Links',
                'db_table': 'research_outcome_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='researchoutcome',
            index=models.Index(fields=['project', 'output_type', 'status'], name='rsch_outcome_project_idx'),
        ),
        migrations.AddIndex(
            model_name='researchoutcome',
            index=models.Index(fields=['workspace', 'status', 'published_at'], name='rsch_outcome_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchoutcomelink',
            index=models.Index(fields=['target_type', 'target_id'], name='rsch_outcome_link_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchoutcomelink',
            constraint=models.UniqueConstraint(fields=('outcome', 'target_type', 'target_id'), name='rsch_outcome_link_uq'),
        ),
    ]
