# Generated by Django 5.2.15 on 2026-09-15 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_research_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystemConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('system', models.CharField(choices=[('RAGPORTAL', 'RAGPortal'), ('WEKNORA', 'WeKnora'), ('SPECLABOS', 'SpecLabOS'), ('SMARTACCESS', 'SmartAccess'), ('POLY_AGENT', 'Poly_Agent'), ('SPEC_AGENT', 'Spec_Agent')], max_length=24)),
                ('display_name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_mode', models.CharField(choices=[('HMAC', 'AI4MS HMAC'), ('BEARER', 'Bearer token'), ('OIDC_CLIENT', 'OIDC client credentials'), ('NONE', 'None')], default='HMAC', max_length=16)),
                ('credential_ref', models.CharField(blank=True, default='', max_length=128)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=3)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300)),
                ('degraded_mode', models.CharField(choices=[('LINK_ONLY', 'Link only'), ('HIDDEN', 'Hidden')], default='LINK_ONLY', max_length=16)),
                ('is_enabled', models.BooleanField(default=False)),
                ('health_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('OK', 'Ok'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], default='UNKNOWN', max_length=16)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_integration_connections', to='db.workspace')),
            ],
            options={
                'verbose_name': 'External System Connection',
                'verbose_name_plural': 'External System Connections',
                'db_table': 'research_external_system_connections',
                'ordering': ('system',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationCallLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('system', models.CharField(choices=[('RAGPORTAL', 'RAGPortal'), ('WEKNORA', 'WeKnora'), ('SPECLABOS', 'SpecLabOS'), ('SMARTACCESS', 'SmartAccess'), ('POLY_AGENT', 'Poly_Agent'), ('SPEC_AGENT', 'Spec_Agent')], max_length=24)),
                ('operation', models.CharField(max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='db.externalsystemconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_integration_call_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Integration Call Log',
                'verbose_name_plural': 'Integration Call Logs',
                'db_table': 'research_integration_call_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResearchExternalReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('system', models.CharField(choices=[('RAGPORTAL', 'RAGPortal'), ('WEKNORA', 'WeKnora'), ('SPECLABOS', 'SpecLabOS'), ('SMARTACCESS', 'SmartAccess'), ('POLY_AGENT', 'Poly_Agent'), ('SPEC_AGENT', 'Spec_Agent')], max_length=24)),
                ('external_type', models.CharField(choices=[('KNOWLEDGE_ENTRY', 'Knowledge entry'), ('RD_PROJECT', 'R&D project'), ('RD_TASK', 'R&D task'), ('RUN_RECORD', 'Run record'), ('DATA_ASSET', 'Data asset'), ('ANALYSIS_RESULT', 'Analysis result'), ('REPORT', 'Report')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('external_parent_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(max_length=500)),
                ('acl_hint', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNAVAILABLE', 'Unavailable'), ('REVOKED', 'Revoked'), ('DEGRADED', 'Degraded')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_external_references', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Research External Reference',
                'verbose_name_plural': 'Research External References',
                'db_table': 'research_external_references',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExternalReferenceLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('STAGE_MATERIAL', 'Stage material'), ('LITERATURE_ENTRY', 'Literature entry'), ('EXPERIMENT_RECORD', 'Experiment record'), ('PERIODIC_REPORT', 'Periodic report'), ('OUTCOME', 'Outcome')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_external_reference_links', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='db.researchexternalreference')),
            ],
            options={
                'verbose_name': 'External Reference Link',
                'verbose_name_plural': 'External Reference Links',
                'db_table': 'research_external_reference_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='externalsystemconnection',
            index=models.Index(fields=['workspace', 'is_enabled'], name='rsch_connection_ws_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalsystemconnection',
            constraint=models.UniqueConstraint(fields=('workspace', 'system'), name='rsch_connection_uq_ws_system'),
        ),
        migrations.AddIndex(
            model_name='integrationcalllog',
            index=models.Index(fields=['workspace', 'system', 'created_at'], name='rsch_call_log_ws_system_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationcalllog',
            index=models.Index(fields=['outcome'], name='rsch_call_log_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='researchexternalreference',
            index=models.Index(fields=['workspace', 'system', 'status'], name='rsch_reference_ws_system_idx'),
        ),
        migrations.AddIndex(
            model_name='researchexternalreference',
            index=models.Index(fields=['external_type', 'external_id'], name='rsch_reference_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchexternalreference',
            constraint=models.UniqueConstraint(fields=('workspace', 'system', 'external_type', 'external_id'), name='rsch_reference_uq_external'),
        ),
        migrations.AddIndex(
            model_name='externalreferencelink',
            index=models.Index(fields=['target_type', 'target_id'], name='rsch_reference_link_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalreferencelink',
            constraint=models.UniqueConstraint(fields=('reference', 'target_type', 'target_id'), name='rsch_reference_link_uq'),
        ),
    ]
