# Generated by Django 4.2.24 on 2025-12-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0141_projecttemplate_issue_template_project_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='workspace',
            field=models.ForeignKey(default='a29df89c-6208-4272-a18d-ec491b81d183', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
            preserve_default=False,
        ),
    ]
