# Generated by Django 5.2.15 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0141_research_workspace_model_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentassetlink",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("PLANE", "PiLab"),
                    ("SPECLABOS", "SpecLabOS"),
                    ("SMARTACCESS", "SmartAccess"),
                    ("RAGPORTAL", "RAGPortal"),
                    ("POLY_AGENT", "Poly_Agent"),
                    ("SPEC_AGENT", "Spec_Agent"),
                    ("OTHER", "Other"),
                ],
                default="SPECLABOS",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="externalsystemconnection",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("HMAC", "PiLab HMAC"),
                    ("BEARER", "Bearer token"),
                    ("OIDC_CLIENT", "OIDC client credentials"),
                    ("NONE", "None"),
                ],
                default="HMAC",
                max_length=16,
            ),
        ),
    ]
