# Generated by Django 4.2.24 on 2025-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0142_projecttemplate_workspace'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('repository__isnull', False)), fields=('repository', 'name'), name='unique_case_repository_name_when_not_deleted'),
        ),
    ]
