# Generated by Django 4.2.24 on 2025-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0143_testcase_unique_case_repository_name_when_not_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
        migrations.AddField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
