# Generated by Django 4.2.24 on 2025-12-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_remove_project_template_project_is_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='network',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='project_lead',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='template_description',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='workspace',
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='db.project'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Template Name'),
        ),
        migrations.AlterModelTable(
            name='projecttemplate',
            table='project_template',
        ),
    ]
