# Generated by Django 4.2.24 on 2025-12-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0145_remove_projecttemplate_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='zh-CN', max_length=255),
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='cycles',
        ),
        migrations.AddField(
            model_name='testplan',
            name='cycles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='db.cycle'),
        ),
    ]
