# Generated by Django 4.2.24 on 2025-12-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0146_alter_profile_language_remove_testplan_cycles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplan',
            old_name='cycles',
            new_name='cycle',
        ),
    ]
