# Generated by Django 4.2.28 on 2026-05-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0177_rename_scheduled_system_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'db_table': 'help_articles',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HelpArticleTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('locale', models.CharField(choices=[('vi', 'Vietnamese'), ('en', 'English'), ('ko', 'Korean')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('description_json', models.JSONField(blank=True, default=dict)),
                ('description_stripped', models.TextField(blank=True, null=True)),
                ('search_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Help Article Translation',
                'verbose_name_plural': 'Help Article Translations',
                'db_table': 'help_article_translations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'db_table': 'help_categories',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HelpCategoryTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('locale', models.CharField(choices=[('vi', 'Vietnamese'), ('en', 'English'), ('ko', 'Korean')], max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Help Category Translation',
                'verbose_name_plural': 'Help Category Translations',
                'db_table': 'help_category_translations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='helpcategorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='db.helpcategory'),
        ),
        migrations.AddField(
            model_name='helpcategorytranslation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='helpcategorytranslation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='helparticletranslation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='db.helparticle'),
        ),
        migrations.AddField(
            model_name='helparticletranslation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='helparticletranslation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='db.helpcategory'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddConstraint(
            model_name='helpcategorytranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('category', 'locale'), name='help_category_translation_unique_locale_active'),
        ),
        migrations.AddConstraint(
            model_name='helpcategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='help_category_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='helparticletranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('article', 'locale'), name='help_article_translation_unique_locale_active'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['status'], name='help_article_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='helparticle',
            constraint=models.UniqueConstraint(fields=('slug',), name='help_article_unique_slug'),
        ),
    ]
