/**
 * SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
 * SPDX-License-Identifier: LicenseRef-Plane-Commercial
 *
 * Licensed under the Plane Commercial License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://plane.so/legals/eula
 *
 * DO NOT remove or modify this notice.
 * NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.
 */

// Action icons
import {
  AddIcon,
  AddReactionIcon,
  AddWorkItemIcon,
  CheckIcon,
  CloseIcon,
  CopyIcon,
  EditIcon,
  FilterAppliedIcon,
  FilterIcon,
  GlobeIcon,
  LinkIcon,
  LockIcon,
  NewTabIcon,
  PlusIcon,
  PreferencesIcon,
  SearchIcon,
  SortByUpIcon,
  SortByDownIcon,
  TrashIcon,
  UpgradeIcon,
  CommandIcon,
} from "./actions";
// Arrow icons
import {
  AccordionCloseIcon,
  AccordionOpenIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ExternalLinkIcon,
  ReplyIcon,
  ImportIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BackspaceIcon,
} from "./arrows";
// Default icon
import { DefaultIcon } from "./default-icon";
// Layout icons
import {
  BoardLayoutIcon,
  CalendarLayoutIcon,
  CardLayoutIcon,
  GridLayoutIcon,
  ListLayoutIcon,
  SheetLayoutIcon,
  TimelineLayoutIcon,
} from "./layouts";
// Misc icons
import { InfoIcon, AlertIcon, HistoryIcon, ShiftIcon, TickCircleIcon } from "./misc";
// Project icons
import {
  CycleIcon,
  EpicIcon,
  IntakeIcon,
  ModuleIcon,
  PageIcon,
  PropertiesIcon,
  ViewsIcon,
  WorkItemsIcon,
} from "./project";
// Property icons
import {
  BooleanPropertyIcon,
  CompletedAtPropertyIcon,
  CreatedAtPropertyIcon,
  DependencyPropertyIcon,
  DropdownPropertyIcon,
  DueDatePropertyIcon,
  DuplicatePropertyIcon,
  EstimatePropertyIcon,
  HashPropertyIcon,
  LabelPropertyIcon,
  MembersPropertyIcon,
  OverdueDatePropertyIcon,
  ParentPropertyIcon,
  PriorityPropertyIcon,
  RelatesToPropertyIcon,
  RelationPropertyIcon,
  ScopePropertyIcon,
  StartDatePropertyIcon,
  StatePropertyIcon,
  UpdatedAtPropertyIcon,
  UserCirclePropertyIcon,
  UserPropertyIcon,
  UserSquarePropertyIcon,
  WorkflowsPropertyIcon,
} from "./properties";
// Sub-brand icons
import { CopyLinkIcon } from "./actions/copy-link";
import { LabelFilledIcon } from "./properties/label-filled-icon";
import { PiChatLogo, PlaneNewIcon, WikiIcon } from "./sub-brand";
// Workspace icons
import {
  AnalyticsIcon,
  ArchiveIcon,
  DashboardIcon,
  DraftIcon,
  HomeIcon,
  InboxIcon,
  MultipleStickyIcon,
  ProjectIcon,
  YourWorkIcon,
} from "./workspace";
// Formatting icons
import {
  AlignCenterIcon,
  AlignCenterFilledIcon,
  AlignLeftIcon,
  AlignLeftFilledIcon,
  AlignRightIcon,
  AlignRightFilledIcon,
  BoldIcon,
  BoldFilledIcon,
  BulletedListIcon,
  BulletedListFilledIcon,
  CalloutIcon,
  CalloutFilledIcon,
  CodeIcon,
  CodeFilledIcon,
  DividerIcon,
  DividerFilledIcon,
  EmbedIcon,
  EmbedFilledIcon,
  FormulaIcon,
  FormulaFilledIcon,
  H1Icon,
  H1FilledIcon,
  H2Icon,
  H2FilledIcon,
  H3Icon,
  H3FilledIcon,
  H4Icon,
  H4FilledIcon,
  H5Icon,
  H5FilledIcon,
  H6Icon,
  H6FilledIcon,
  ImageIcon,
  ImageFilledIcon,
  ItalicIcon,
  ItalicFilledIcon,
  NumberedListIcon,
  NumberedListFilledIcon,
  QuoteIcon,
  QuoteFilledIcon,
  StrikeThroughIcon,
  StrikethroughFilledIcon,
  TableIcon,
  TableFilledIcon,
  TextIcon,
  TextFilledIcon,
  TodoListIcon,
  TodoListFilledIcon,
  ToggleListIcon,
  ToggleListFilledIcon,
  UnderlineIcon,
  UnderlineFilledIcon,
} from "./formatting";
import {
  AsanaIcon,
  ClickupIcon,
  GitlabIcon,
  JiraIcon,
  LinearIcon,
  MondayIcon,
  RaycastIcon,
  SentryIcon,
} from "./other-products";

export const ICON_REGISTRY = {
  // Sub-brand icons
  "sub-brand.plane": PlaneNewIcon,
  "sub-brand.wiki": WikiIcon,
  "sub-brand.pi-chat": PiChatLogo,

  // Workspace icons
  "workspace.analytics": AnalyticsIcon,
  "workspace.archive": ArchiveIcon,
  "workspace.cycle": CycleIcon,
  "workspace.dashboard": DashboardIcon,
  "workspace.draft": DraftIcon,
  "workspace.home": HomeIcon,
  "workspace.inbox": InboxIcon,
  "workspace.multiple-sticky": MultipleStickyIcon,
  "workspace.page": PageIcon,
  "workspace.project": ProjectIcon,
  "workspace.views": ViewsIcon,
  "workspace.your-work": YourWorkIcon,

  // Project icons
  "project.cycle": CycleIcon,
  "project.epic": EpicIcon,
  "project.intake": IntakeIcon,
  "project.module": ModuleIcon,
  "project.page": PageIcon,
  "project.view": ViewsIcon,
  "project.work-items": WorkItemsIcon,
  "project.properties": PropertiesIcon,

  // Layout icons
  "layout.calendar": CalendarLayoutIcon,
  "layout.card": CardLayoutIcon,
  "layout.timeline": TimelineLayoutIcon,
  "layout.grid": GridLayoutIcon,
  "layout.board": BoardLayoutIcon,
  "layout.list": ListLayoutIcon,
  "layout.sheet": SheetLayoutIcon,

  // Property icons
  "property.boolean": BooleanPropertyIcon,
  "property.completed-at": CompletedAtPropertyIcon,
  "property.created-at": CreatedAtPropertyIcon,
  "property.dependency": DependencyPropertyIcon,
  "property.dropdown": DropdownPropertyIcon,
  "property.due-date": DueDatePropertyIcon,
  "property.duplicate": DuplicatePropertyIcon,
  "property.estimate": EstimatePropertyIcon,
  "property.hash": HashPropertyIcon,
  "property.label": LabelPropertyIcon,
  "property.members": MembersPropertyIcon,
  "property.overdue-date": OverdueDatePropertyIcon,
  "property.parent": ParentPropertyIcon,
  "property.priority": PriorityPropertyIcon,
  "property.relates-to": RelatesToPropertyIcon,
  "property.relation": RelationPropertyIcon,
  "property.scope": ScopePropertyIcon,
  "property.start-date": StartDatePropertyIcon,
  "property.state": StatePropertyIcon,
  "property.updated-at": UpdatedAtPropertyIcon,
  "property.user-circle": UserCirclePropertyIcon,
  "property.user": UserPropertyIcon,
  "property.user-square": UserSquarePropertyIcon,
  "property.workflows": WorkflowsPropertyIcon,
  "property.label-filled": LabelFilledIcon,

  // Formatting icons
  "formatting.align-center": AlignCenterIcon,
  "formatting.align-center-filled": AlignCenterFilledIcon,
  "formatting.align-left": AlignLeftIcon,
  "formatting.align-left-filled": AlignLeftFilledIcon,
  "formatting.align-right": AlignRightIcon,
  "formatting.align-right-filled": AlignRightFilledIcon,
  "formatting.bold": BoldIcon,
  "formatting.bold-filled": BoldFilledIcon,
  "formatting.bulleted-list": BulletedListIcon,
  "formatting.bulleted-list-filled": BulletedListFilledIcon,
  "formatting.callout": CalloutIcon,
  "formatting.callout-filled": CalloutFilledIcon,
  "formatting.code": CodeIcon,
  "formatting.code-filled": CodeFilledIcon,
  "formatting.divider": DividerIcon,
  "formatting.divider-filled": DividerFilledIcon,
  "formatting.embed": EmbedIcon,
  "formatting.embed-filled": EmbedFilledIcon,
  "formatting.formula": FormulaIcon,
  "formatting.formula-filled": FormulaFilledIcon,
  "formatting.h1": H1Icon,
  "formatting.h1-filled": H1FilledIcon,
  "formatting.h2": H2Icon,
  "formatting.h2-filled": H2FilledIcon,
  "formatting.h3": H3Icon,
  "formatting.h3-filled": H3FilledIcon,
  "formatting.h4": H4Icon,
  "formatting.h4-filled": H4FilledIcon,
  "formatting.h5": H5Icon,
  "formatting.h5-filled": H5FilledIcon,
  "formatting.h6": H6Icon,
  "formatting.h6-filled": H6FilledIcon,
  "formatting.image": ImageIcon,
  "formatting.image-filled": ImageFilledIcon,
  "formatting.italic": ItalicIcon,
  "formatting.italic-filled": ItalicFilledIcon,
  "formatting.numbered-list": NumberedListIcon,
  "formatting.numbered-list-filled": NumberedListFilledIcon,
  "formatting.quote": QuoteIcon,
  "formatting.quote-filled": QuoteFilledIcon,
  "formatting.strikethrough": StrikeThroughIcon,
  "formatting.strikethrough-filled": StrikethroughFilledIcon,
  "formatting.table": TableIcon,
  "formatting.table-filled": TableFilledIcon,
  "formatting.text": TextIcon,
  "formatting.text-filled": TextFilledIcon,
  "formatting.todo-list": TodoListIcon,
  "formatting.todo-list-filled": TodoListFilledIcon,
  "formatting.toggle-list": ToggleListIcon,
  "formatting.toggle-list-filled": ToggleListFilledIcon,
  "formatting.underline": UnderlineIcon,
  "formatting.underline-filled": UnderlineFilledIcon,

  // Action icons
  "action.add": AddIcon,
  "action.add-workitem": AddWorkItemIcon,
  "action.add-reaction": AddReactionIcon,
  "action.check": CheckIcon,
  "action.close": CloseIcon,
  "action.copy": CopyIcon,
  "action.command": CommandIcon,
  "action.edit": EditIcon,
  "action.globe": GlobeIcon,
  "action.link": LinkIcon,
  "action.lock": LockIcon,
  "action.new-tab": NewTabIcon,
  "action.filter": FilterIcon,
  "action.filter-applied": FilterAppliedIcon,
  "action.search": SearchIcon,
  "action.plus": PlusIcon,
  "action.preferences": PreferencesIcon,
  "action.trash": TrashIcon,
  "action.copy-link": CopyLinkIcon,
  "action.upgrade": UpgradeIcon,
  "action.sort-by-up": SortByUpIcon,
  "action.sort-by-down": SortByDownIcon,

  // Arrow icons
  "arrow.accordion-close": AccordionCloseIcon,
  "arrow.accordion-open": AccordionOpenIcon,
  "arrow.chevron-down": ChevronDownIcon,
  "arrow.chevron-left": ChevronLeftIcon,
  "arrow.chevron-right": ChevronRightIcon,
  "arrow.chevron-up": ChevronUpIcon,
  "arrow.arrow-left": ArrowLeftIcon,
  "arrow.arrow-right": ArrowRightIcon,
  "arrow.backspace": BackspaceIcon,

  // Misc icons
  "misc.info": InfoIcon,
  "misc.alert": AlertIcon,
  "misc.history": HistoryIcon,
  "misc.tick-circle": TickCircleIcon,
  // Backward-compatible alias
  "misc.tick-circle-solid": TickCircleIcon,
  "arrow.reply": ReplyIcon,
  "arrow.external-link": ExternalLinkIcon,
  "arrow.import": ImportIcon,
  // Other products icons
  "other-products.jira": JiraIcon,
  "other-products.clickup": ClickupIcon,
  "other-products.asana": AsanaIcon,
  "other-products.linear": LinearIcon,
  "other-products.monday": MondayIcon,
  "other-products.sentry": SentryIcon,
  "other-products.raycast": RaycastIcon,
  "other-products.gitlab": GitlabIcon,
  "misc.shift": ShiftIcon,

  // Default fallback
  default: DefaultIcon,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
