# Django imports
from django.urls import path

# Module imports
from plane.ee.views.app.team import (
    TeamSpaceEndpoint,
    TeamSpaceEntitiesEndpoint,
    TeamSpaceMembersEndpoint,
    TeamSpaceViewEndpoint,
    TeamSpaceCycleEndpoint,
    TeamSpacePageEndpoint,
    TeamSpacePageArchiveEndpoint,
    TeamSpacePageUnarchiveEndpoint,
    TeamSpacePagesDescriptionEndpoint,
    TeamSpacePageLockEndpoint,
    TeamSpacePageFavoriteEndpoint,
    TeamSpacePageVersionEndpoint,
    TeamSpaceIssueEndpoint,
    TeamSpaceUserPropertiesEndpoint,
    TeamSpaceActivityEndpoint,
    TeamSpaceCommentEndpoint,
    TeamSpaceCommentReactionEndpoint,
    TeamSpacePageDuplicateEndpoint,
)

urlpatterns = [
    path("workspaces/<str:slug>/teams/", TeamSpaceEndpoint.as_view(), name="teams"),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/",
        TeamSpaceEndpoint.as_view(),
        name="teams",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/entities/",
        TeamSpaceEntitiesEndpoint.as_view(),
        name="team-entities",
    ),
    path(
        "workspaces/<str:slug>/team-members/",
        TeamSpaceMembersEndpoint.as_view(),
        name="workspace-team-members",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/members/",
        TeamSpaceMembersEndpoint.as_view(),
        name="team-members",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/members/<uuid:pk>/",
        TeamSpaceMembersEndpoint.as_view(),
        name="team-members",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/views/",
        TeamSpaceViewEndpoint.as_view(),
        name="team-views",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/views/<uuid:pk>/",
        TeamSpaceViewEndpoint.as_view(),
        name="team-views",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/cycles/",
        TeamSpaceCycleEndpoint.as_view(),
        name="team-cycle",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/",
        TeamSpacePageEndpoint.as_view(),
        name="team-pages",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/",
        TeamSpacePageEndpoint.as_view(),
        name="team-pages",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/duplicate/",
        TeamSpacePageDuplicateEndpoint.as_view(),
        name="team-page-duplicate",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/archive/",
        TeamSpacePageArchiveEndpoint.as_view(),
        name="team-pages-archive",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/unarchive/",
        TeamSpacePageUnarchiveEndpoint.as_view(),
        name="team-pages-unarchive",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/description/",
        TeamSpacePagesDescriptionEndpoint.as_view(),
        name="team-pages-description",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/lock/",
        TeamSpacePageLockEndpoint.as_view(),
        name="team-pages-lock",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:pk>/favorite/",
        TeamSpacePageFavoriteEndpoint.as_view(),
        name="team-pages-favorite",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:page_id>/versions/",
        TeamSpacePageVersionEndpoint.as_view(),
        name="team-pages-versions",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/pages/<uuid:page_id>/versions/<uuid:pk>/",
        TeamSpacePageVersionEndpoint.as_view(),
        name="team-pages-versions",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/issues/",
        TeamSpaceIssueEndpoint.as_view(),
        name="team-issues",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/user-properties/",
        TeamSpaceUserPropertiesEndpoint.as_view(),
        name="team-issues-user-properties",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/history/",
        TeamSpaceActivityEndpoint.as_view(),
        name="team-activities",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/comments/",
        TeamSpaceCommentEndpoint.as_view(),
        name="team-space-comments",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/comments/<uuid:pk>/",
        TeamSpaceCommentEndpoint.as_view(),
        name="team-space-comments",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/comments/<uuid:comment_id>/reactions/",
        TeamSpaceCommentReactionEndpoint.as_view(),
        name="team-space-comments-reactions",
    ),
    path(
        "workspaces/<str:slug>/teams/<uuid:team_space_id>/comments/<uuid:comment_id>/reactions/<str:reaction_code>/",
        TeamSpaceCommentReactionEndpoint.as_view(),
        name="team-space-comments-reactions",
    ),
]
