# Generated by Django 4.2.22 on 2025-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='initiator_id',
            field=models.UUIDField(blank=True, help_text='The user ID who triggered the event', null=True),
        ),
    ]
