# Generated by Django 3.2.16 on 2023-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0012_auto_20230104_0117"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="description_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="description_stripped",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="view_props",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.JSONField(blank=True),
        ),
    ]
