import { useContext } from "react";
// context
import { StoreContext } from "@/lib/store-context";

export enum E_FEATURE_FLAGS {
  BULK_OPS = "BULK_OPS",
  BULK_OPS_ADVANCED = "BULK_OPS_ADVANCED",
  COLLABORATION_CURSOR = "COLLABORATION_CURSOR",
  EDITOR_AI_OPS = "EDITOR_AI_OPS",
  ESTIMATE_WITH_TIME = "ESTIMATE_WITH_TIME",
  ISSUE_TYPE_DISPLAY = "ISSUE_TYPE_DISPLAY",
  ISSUE_TYPE_SETTINGS = "ISSUE_TYPE_SETTINGS",
  OIDC_SAML_AUTH = "OIDC_SAML_AUTH",
  PAGE_ISSUE_EMBEDS = "PAGE_ISSUE_EMBEDS",
  PAGE_PUBLISH = "PAGE_PUBLISH",
  VIEW_ACCESS_PRIVATE = "VIEW_ACCESS_PRIVATE",
  VIEW_LOCK = "VIEW_LOCK",
  VIEW_PUBLISH = "VIEW_PUBLISH",
  WORKSPACE_ACTIVE_CYCLES = "WORKSPACE_ACTIVE_CYCLES",
  WORKSPACE_PAGES = "WORKSPACE_PAGES",
  ISSUE_WORKLOG = "ISSUE_WORKLOG",
  PROJECT_GROUPING = "PROJECT_GROUPING",
  ACTIVE_CYCLE_PRO = "ACTIVE_CYCLE_PRO",
  FILE_SIZE_LIMIT_PRO = "FILE_SIZE_LIMIT_PRO",
  TIMELINE_DEPENDENCY = "TIMELINE_DEPENDENCY",
  // integrations
  SILO_IMPORTERS = "SILO_IMPORTERS",
  SILO_INTEGRATIONS = "SILO_INTEGRATIONS",
  JIRA_IMPORTER = "JIRA_IMPORTER",
  JIRA_ISSUE_TYPES_IMPORTER = "JIRA_ISSUE_TYPES_IMPORTER",
  LINEAR_IMPORTER = "LINEAR_IMPORTER",
  LINEAR_TEAMS_IMPORTER = "LINEAR_TEAMS_IMPORTER",
  ASANA_IMPORTER = "ASANA_IMPORTER",
  ASANA_ISSUE_PROPERTIES_IMPORTER = "ASANA_ISSUE_PROPERTIES_IMPORTER",
  GITHUB_INTEGRATION = "GITHUB_INTEGRATION",
  GITLAB_INTEGRATION = "GITLAB_INTEGRATION",
  SLACK_INTEGRATION = "SLACK_INTEGRATION",

  SILO_JIRA_INTEGRATION = "SILO_JIRA_INTEGRATION", // DEPRECATED
  SILO_LINEAR_INTEGRATION = "SILO_LINEAR_INTEGRATION", // DEPRECATED
  SILO_INTEGRATION = "SILO_INTEGRATION", // DEPRECATED

  // intake
  INTAKE_SETTINGS = "INTAKE_SETTINGS",
  // PI
  PI_CHAT = "PI_CHAT",
  PI_DEDUPE = "PI_DEDUPE",
}

export const useFlag = (
  workspaceSlug: string,
  flag: keyof typeof E_FEATURE_FLAGS,
  defaultValue: boolean = false
): boolean => {
  const context = useContext(StoreContext);
  if (context === undefined) throw new Error("useFlag must be used within StoreProvider");
  return context.featureFlags.flags[workspaceSlug]?.[E_FEATURE_FLAGS[flag]] ?? defaultValue;
};
