import { EProductSubscriptionEnum } from "./payment";

export enum E_FEATURE_FLAGS {
  BULK_OPS_ONE = "BULK_OPS_ONE",
  BULK_OPS_PRO = "BULK_OPS_PRO",
  COLLABORATION_CURSOR = "COLLABORATION_CURSOR",
  EDITOR_AI_OPS = "EDITOR_AI_OPS",
  ESTIMATE_WITH_TIME = "ESTIMATE_WITH_TIME",
  ISSUE_TYPES = "ISSUE_TYPES",
  EPICS = "EPICS",
  WORK_ITEM_CONVERSION = "WORK_ITEM_CONVERSION",
  OIDC_SAML_AUTH = "OIDC_SAML_AUTH",
  PAGE_ISSUE_EMBEDS = "PAGE_ISSUE_EMBEDS",
  PAGE_PUBLISH = "PAGE_PUBLISH",
  MOVE_PAGES = "MOVE_PAGES",
  NESTED_PAGES = "NESTED_PAGES",
  VIEW_ACCESS_PRIVATE = "VIEW_ACCESS_PRIVATE",
  VIEW_LOCK = "VIEW_LOCK",
  VIEW_PUBLISH = "VIEW_PUBLISH",
  WORKSPACE_ACTIVE_CYCLES = "WORKSPACE_ACTIVE_CYCLES",
  WORKSPACE_PAGES = "WORKSPACE_PAGES",
  ISSUE_WORKLOG = "ISSUE_WORKLOG",
  PROJECT_GROUPING = "PROJECT_GROUPING",
  CYCLE_PROGRESS_CHARTS = "CYCLE_PROGRESS_CHARTS",
  FILE_SIZE_LIMIT_PRO = "FILE_SIZE_LIMIT_PRO",
  TIMELINE_DEPENDENCY = "TIMELINE_DEPENDENCY",
  TEAMSPACES = "TEAMSPACES",
  INBOX_STACKING = "INBOX_STACKING",
  PROJECT_OVERVIEW = "PROJECT_OVERVIEW",
  PROJECT_UPDATES = "PROJECT_UPDATES",
  CYCLE_MANUAL_START_STOP = "CYCLE_MANUAL_START_STOP",
  HOME_ADVANCED = "HOME_ADVANCED",
  ADVANCED_SEARCH = "ADVANCED_SEARCH",
  WORKFLOWS = "WORKFLOWS",
  CUSTOMERS = "CUSTOMERS",
  WORKITEM_TEMPLATES = "WORKITEM_TEMPLATES",
  PROJECT_TEMPLATES = "PROJECT_TEMPLATES",
  PAGE_TEMPLATES = "PAGE_TEMPLATES",
  TIME_ESTIMATES = "TIME_ESTIMATES",
  PROJECT_TEMPLATES_PUBLISH = "PROJECT_TEMPLATES_PUBLISH",

  // ====== silo importers ======
  SILO_IMPORTERS = "SILO_IMPORTERS",

  FLATFILE_IMPORTER = "FLATFILE_IMPORTER",

  JIRA_IMPORTER = "JIRA_IMPORTER",
  JIRA_ISSUE_TYPES_IMPORTER = "JIRA_ISSUE_TYPES_IMPORTER",

  JIRA_SERVER_IMPORTER = "JIRA_SERVER_IMPORTER",
  JIRA_SERVER_ISSUE_TYPES_IMPORTER = "JIRA_SERVER_ISSUE_TYPES_IMPORTER",

  LINEAR_IMPORTER = "LINEAR_IMPORTER",
  LINEAR_TEAMS_IMPORTER = "LINEAR_TEAMS_IMPORTER",

  ASANA_IMPORTER = "ASANA_IMPORTER",
  ASANA_ISSUE_PROPERTIES_IMPORTER = "ASANA_ISSUE_PROPERTIES_IMPORTER",

  NOTION_IMPORTER = "NOTION_IMPORTER",

  // ==== silo ======
  SILO = "SILO",

  // ====== silo integrations ======
  SILO_INTEGRATIONS = "SILO_INTEGRATIONS",
  GITHUB_INTEGRATION = "GITHUB_INTEGRATION",

  GITLAB_INTEGRATION = "GITLAB_INTEGRATION",
  SLACK_INTEGRATION = "SLACK_INTEGRATION",

  // ====== silo deprecated ======
  SILO_JIRA_INTEGRATION = "SILO_JIRA_INTEGRATION", // DEPRECATED
  SILO_LINEAR_INTEGRATION = "SILO_LINEAR_INTEGRATION", // DEPRECATED
  SILO_INTEGRATION = "SILO_INTEGRATION", // DEPRECATED

  // intake
  INTAKE_EMAIL = "INTAKE_EMAIL",
  INTAKE_FORM = "INTAKE_FORM",
  // PI
  PI_CHAT = "PI_CHAT",
  PI_DEDUPE = "PI_DEDUPE",
  // initiatives
  INITIATIVES = "INITIATIVES",
  // dashboards
  DASHBOARDS = "DASHBOARDS",
  DASHBOARDS_ADVANCED = "DASHBOARDS_ADVANCED",
  // applications
  APPLICATIONS = "APPLICATIONS",
}

/**
 * This map is used to determine the base plan for a feature flag.
 */
// TODO: Update this to include all features flags
export const FEATURE_TO_BASE_PLAN_MAP = {
  [E_FEATURE_FLAGS.WORKFLOWS]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.CUSTOMERS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PROJECT_TEMPLATES]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.PROJECT_TEMPLATES_PUBLISH]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.WORKITEM_TEMPLATES]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PAGE_TEMPLATES]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.DASHBOARDS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.SILO_INTEGRATIONS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.EPICS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PROJECT_UPDATES]: EProductSubscriptionEnum.PRO,
};

export type TSupportedFlagsForUpgrade = keyof typeof FEATURE_TO_BASE_PLAN_MAP;
