/**
 * SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
 * SPDX-License-Identifier: LicenseRef-Plane-Commercial
 *
 * Licensed under the Plane Commercial License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://plane.so/legals/eula
 *
 * DO NOT remove or modify this notice.
 * NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.
 */

import { EProductSubscriptionEnum } from "@plane/types";

export enum E_FEATURE_FLAGS {
  BULK_OPS_ONE = "BULK_OPS_ONE",
  BULK_OPS_PRO = "BULK_OPS_PRO",
  ESTIMATE_WITH_TIME = "ESTIMATE_WITH_TIME",
  // work item types
  ISSUE_TYPES = "ISSUE_TYPES",
  WORKSPACE_WORK_ITEM_TYPES = "WORKSPACE_WORK_ITEM_TYPES",
  WORKITEM_TYPE_HIERARCHY = "WORKITEM_TYPE_HIERARCHY",
  EPICS = "EPICS",
  WORK_ITEM_CONVERSION = "WORK_ITEM_CONVERSION",
  OIDC_SAML_AUTH = "OIDC_SAML_AUTH",
  VIEW_ACCESS_PRIVATE = "VIEW_ACCESS_PRIVATE",
  VIEW_LOCK = "VIEW_LOCK",
  VIEW_PUBLISH = "VIEW_PUBLISH",
  WORKSPACE_ACTIVE_CYCLES = "WORKSPACE_ACTIVE_CYCLES",
  ISSUE_WORKLOG = "ISSUE_WORKLOG",
  IDP_GROUP_SYNC = "IDP_GROUP_SYNC",
  PROJECT_GROUPING = "PROJECT_GROUPING",
  WORKSPACE_PROJECT_LABELS = "WORKSPACE_PROJECT_LABELS",
  CYCLE_PROGRESS_CHARTS = "CYCLE_PROGRESS_CHARTS",
  FILE_SIZE_LIMIT_PRO = "FILE_SIZE_LIMIT_PRO",
  TIMELINE_DEPENDENCY = "TIMELINE_DEPENDENCY",
  CUSTOM_RELATIONS = "CUSTOM_RELATIONS",
  TEAMSPACES = "TEAMSPACES",
  INBOX_STACKING = "INBOX_STACKING",
  PROJECT_OVERVIEW = "PROJECT_OVERVIEW",
  PROJECT_UPDATES = "PROJECT_UPDATES",
  HOME_ADVANCED = "HOME_ADVANCED",
  ADVANCED_SEARCH = "ADVANCED_SEARCH",
  WORKFLOWS = "WORKFLOWS",
  MULTIPLE_WORKFLOWS = "MULTIPLE_WORKFLOWS",
  CUSTOMERS = "CUSTOMERS",
  WORKITEM_TEMPLATES = "WORKITEM_TEMPLATES",
  PROJECT_TEMPLATES = "PROJECT_TEMPLATES",
  PAGE_TEMPLATES = "PAGE_TEMPLATES",
  TIME_ESTIMATES = "TIME_ESTIMATES",
  PROJECT_TEMPLATES_PUBLISH = "PROJECT_TEMPLATES_PUBLISH",
  GLOBAL_VIEWS_TIMELINE = "GLOBAL_VIEWS_TIMELINE",
  GLOBAL_VIEWS_CAL_BOARD = "GLOBAL_VIEWS_CAL_BOARD", // For layouts Kanban and calendar
  COPY_WORK_ITEM = "COPY_WORK_ITEM",
  LINK_PAGES = "LINK_PAGES",
  ADVANCED_EXPORTS = "ADVANCED_EXPORTS",
  MILESTONES = "MILESTONES",
  AUTO_SCHEDULE_CYCLES = "AUTO_SCHEDULE_CYCLES",
  PARALLEL_CYCLES = "PARALLEL_CYCLES",
  WORKSPACE_MEMBERS_IMPORT = "WORKSPACE_MEMBERS_IMPORT",
  PROJECT_MEMBERS_IMPORT = "PROJECT_MEMBERS_IMPORT",

  // ====== silo importers ======
  SILO_IMPORTERS = "SILO_IMPORTERS",

  FLATFILE_IMPORTER = "FLATFILE_IMPORTER",

  JIRA_IMPORTER = "JIRA_IMPORTER",
  JIRA_ISSUE_TYPES_IMPORTER = "JIRA_ISSUE_TYPES_IMPORTER",

  JIRA_SERVER_IMPORTER = "JIRA_SERVER_IMPORTER",
  JIRA_SERVER_ISSUE_TYPES_IMPORTER = "JIRA_SERVER_ISSUE_TYPES_IMPORTER",
  JIRA_SERVER_WORKSPACE_ISSUE_TYPES = "JIRA_SERVER_WORKSPACE_ISSUE_TYPES",

  JIRA_CONFIGURE_JQL = "JIRA_CONFIGURE_JQL",
  IMPORT_SUMMARY = "IMPORT_SUMMARY",

  LINEAR_IMPORTER = "LINEAR_IMPORTER",
  LINEAR_TEAMS_IMPORTER = "LINEAR_TEAMS_IMPORTER",

  ASANA_IMPORTER = "ASANA_IMPORTER",
  ASANA_ISSUE_PROPERTIES_IMPORTER = "ASANA_ISSUE_PROPERTIES_IMPORTER",

  CLICKUP_IMPORTER = "CLICKUP_IMPORTER",
  CLICKUP_ISSUE_PROPERTIES_IMPORTER = "CLICKUP_ISSUE_PROPERTIES_IMPORTER",

  NOTION_IMPORTER = "NOTION_IMPORTER",
  CONFLUENCE_IMPORTER = "CONFLUENCE_IMPORTER",
  ZIP_IMPORTER_URL_IMPORT = "ZIP_IMPORTER_URL_IMPORT",
  CSV_IMPORTER = "CSV_IMPORTER",

  // ==== silo ======
  SILO = "SILO",
  AGENT_SIDECAR = "AGENT_SIDECAR",

  // ====== silo integrations ======
  SILO_INTEGRATIONS = "SILO_INTEGRATIONS",
  GITHUB_INTEGRATION = "GITHUB_INTEGRATION",
  SENTRY_INTEGRATION = "SENTRY_INTEGRATION",
  GITHUB_ENTERPRISE_INTEGRATION = "GITHUB_ENTERPRISE_INTEGRATION",
  GITLAB_INTEGRATION = "GITLAB_INTEGRATION",
  GITLAB_ENTERPRISE_INTEGRATION = "GITLAB_ENTERPRISE_INTEGRATION",
  SLACK_INTEGRATION = "SLACK_INTEGRATION",
  BITBUCKET_DC_INTEGRATION = "BITBUCKET_DC_INTEGRATION",
  SLACK_WORK_OBJECTS = "SLACK_WORK_OBJECTS",
  CURSOR_INTEGRATION = "CURSOR_INTEGRATION",
  OAUTH_BRIDGE_INTEGRATION = "OAUTH_BRIDGE_INTEGRATION",

  // ====== silo deprecated ======
  SILO_JIRA_INTEGRATION = "SILO_JIRA_INTEGRATION", // DEPRECATED
  SILO_LINEAR_INTEGRATION = "SILO_LINEAR_INTEGRATION", // DEPRECATED
  SILO_INTEGRATION = "SILO_INTEGRATION", // DEPRECATED

  // intake
  INTAKE_EMAIL = "INTAKE_EMAIL",
  INTAKE_FORM = "INTAKE_FORM",
  INTAKE_RESPONSIBILITY = "INTAKE_RESPONSIBILITY",
  // PI
  AI_CHAT = "AI_CHAT",
  AI_DEDUPE = "AI_DEDUPE",
  AI_CONVERSE = "AI_CONVERSE",
  AI_FILE_UPLOADS = "AI_FILE_UPLOADS",
  // initiatives
  INITIATIVES = "INITIATIVES",
  // dashboards
  DASHBOARDS = "DASHBOARDS",
  DASHBOARDS_ADVANCED = "DASHBOARDS_ADVANCED",
  // applications
  APPLICATIONS = "APPLICATIONS",
  // pages and editor
  COLLABORATION_CURSOR = "COLLABORATION_CURSOR",
  EDITOR_AI_OPS = "EDITOR_AI_OPS",
  AI_PAGES_BLOCKS = "AI_PAGES_BLOCKS",
  PAGE_ISSUE_EMBEDS = "PAGE_ISSUE_EMBEDS",
  PAGE_PUBLISH = "PAGE_PUBLISH",
  MOVE_PAGES = "MOVE_PAGES",
  NESTED_PAGES = "NESTED_PAGES",
  WORKSPACE_PAGES = "WORKSPACE_PAGES",
  SHARED_PAGES = "SHARED_PAGES",
  AI_PAGES_SUMMARY = "AI_PAGES_SUMMARY",
  EDITOR_ATTACHMENTS = "EDITOR_ATTACHMENTS",
  EDITOR_VIDEO_ATTACHMENTS = "EDITOR_VIDEO_ATTACHMENTS",
  PAGE_COMMENTS = "PAGE_COMMENTS",
  EDITOR_MULTI_COLUMN = "EDITOR_MULTI_COLUMN",
  EDITOR_MATHEMATICS = "EDITOR_MATHEMATICS",
  EDITOR_EXTERNAL_EMBEDS = "EDITOR_EXTERNAL_EMBEDS",
  EDITOR_COPY_BLOCK_LINK = "EDITOR_COPY_BLOCK_LINK",
  EDITOR_ADVANCED_MENTIONS = "EDITOR_ADVANCED_MENTIONS",
  EDITOR_SELECTION_CONVERSION = "EDITOR_SELECTION_CONVERSION",
  PAGE_DOCX_EXPORT = "PAGE_DOCX_EXPORT",
  // analytics
  ANALYTICS_ADVANCED = "ANALYTICS_ADVANCED",
  // app rail
  APP_RAIL = "APP_RAIL",
  // recurring workitems
  RECURRING_WORKITEMS = "RECURRING_WORKITEMS",
  // automations
  PROJECT_AUTOMATIONS = "PROJECT_AUTOMATIONS",
  DUE_DATE_REMINDER = "DUE_DATE_REMINDER",
  WORKSPACE_AUTOMATIONS = "WORKSPACE_AUTOMATIONS",
  // runners
  PLANE_RUNNER = "PLANE_RUNNER",
  // connectors
  AI_MCP_CONNECTORS = "AI_MCP_CONNECTORS",
  SCHEDULED_AUTOMATIONS = "SCHEDULED_AUTOMATIONS",
  WORKFLOW_CONDITIONS = "WORKFLOW_CONDITIONS",
  // rich filters
  RICH_FILTERS = "RICH_FILTERS",
  // intake type form
  WORKITEM_TYPE_INTAKE_FORM = "WORKITEM_TYPE_INTAKE_FORM",
  // formula field for work item types
  WORKITEM_TYPE_FORMULA_FIELD = "WORKITEM_TYPE_FORMULA_FIELD",
  // release picker for work item types
  WORKITEM_TYPE_RELEASE_PICKER = "WORKITEM_TYPE_RELEASE_PICKER",
  // workspace members activity
  WORKSPACE_MEMBER_ACTIVITY = "WORKSPACE_MEMBER_ACTIVITY",
  // project members activity
  PROJECT_MEMBER_ACTIVITY = "PROJECT_MEMBER_ACTIVITY",
  // SSO
  CLOUD_SSO = "CLOUD_SSO",
  // workspace socket connections
  WORKSPACE_SOCKET = "WORKSPACE_SOCKET",
  // project subscribers
  PROJECT_SUBSCRIBERS = "PROJECT_SUBSCRIBERS",
  // releases
  RELEASES = "RELEASES",
  // pql
  PQL = "PQL",
  // Work Item Subscribers
  MANAGE_WORK_ITEM_SUBSCRIBERS = "MANAGE_WORK_ITEM_SUBSCRIBERS",
  // Work Item State Duration
  WORK_ITEM_STATE_DURATION = "WORK_ITEM_STATE_DURATION",
}

/**
 * This map is used to determine the base plan for a feature flag.
 */
// TODO: Update this to include all features flags
export const FEATURE_TO_BASE_PLAN_MAP = {
  [E_FEATURE_FLAGS.WORKFLOWS]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.CUSTOMERS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PROJECT_TEMPLATES]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.PROJECT_TEMPLATES_PUBLISH]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.WORKITEM_TEMPLATES]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PAGE_TEMPLATES]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.DASHBOARDS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.SILO_INTEGRATIONS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.EPICS]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.PROJECT_UPDATES]: EProductSubscriptionEnum.PRO,
  [E_FEATURE_FLAGS.RECURRING_WORKITEMS]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.PROJECT_AUTOMATIONS]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.WORKSPACE_AUTOMATIONS]: EProductSubscriptionEnum.ENTERPRISE,
  [E_FEATURE_FLAGS.WORKITEM_TYPE_FORMULA_FIELD]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.WORKITEM_TYPE_RELEASE_PICKER]: EProductSubscriptionEnum.BUSINESS,
  [E_FEATURE_FLAGS.IDP_GROUP_SYNC]: EProductSubscriptionEnum.ENTERPRISE,
  [E_FEATURE_FLAGS.PARALLEL_CYCLES]: EProductSubscriptionEnum.ENTERPRISE,
  [E_FEATURE_FLAGS.DUE_DATE_REMINDER]: EProductSubscriptionEnum.BUSINESS,
};

export type TSupportedFlagsForUpgrade = keyof typeof FEATURE_TO_BASE_PLAN_MAP;
