import { EUserWorkspaceRoles } from "./user";
import { WORKSPACE_SETTINGS } from "./workspace";

export enum WORKSPACE_SETTINGS_CATEGORY {
  ADMINISTRATION = "administration",
  FEATURES = "features",
  DEVELOPER = "developer",
}

export enum ACCOUNT_SETTINGS_CATEGORY {
  YOUR_ACCOUNT = "your account",
  DEVELOPER = "developer",
}

export enum PROJECT_SETTINGS_CATEGORY {
  PROJECTS = "projects",
}

export const WORKSPACE_SETTINGS_CATEGORIES = [
  WORKSPACE_SETTINGS_CATEGORY.ADMINISTRATION,
  WORKSPACE_SETTINGS_CATEGORY.FEATURES,
  WORKSPACE_SETTINGS_CATEGORY.DEVELOPER,
];

export const ACCOUNT_SETTINGS_CATEGORIES = [
  ACCOUNT_SETTINGS_CATEGORY.YOUR_ACCOUNT,
  ACCOUNT_SETTINGS_CATEGORY.DEVELOPER,
];

export const PROJECT_SETTINGS_CATEGORIES = [PROJECT_SETTINGS_CATEGORY.PROJECTS];

export const GROUPED_WORKSPACE_SETTINGS = {
  [WORKSPACE_SETTINGS_CATEGORY.ADMINISTRATION]: [
    WORKSPACE_SETTINGS["general"],
    WORKSPACE_SETTINGS["members"],
    WORKSPACE_SETTINGS["billing-and-plans"],
    WORKSPACE_SETTINGS["export"],
  ],
  [WORKSPACE_SETTINGS_CATEGORY.FEATURES]: [],
  [WORKSPACE_SETTINGS_CATEGORY.DEVELOPER]: [WORKSPACE_SETTINGS["webhooks"], WORKSPACE_SETTINGS["api-tokens"]],
};

export const GROUPED_ACCOUNT_SETTINGS = {
  [ACCOUNT_SETTINGS_CATEGORY.YOUR_ACCOUNT]: [],
  [ACCOUNT_SETTINGS_CATEGORY.DEVELOPER]: [],
};
