# Generated by Django 4.2.21 on 2025-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_application_website_applicationcategory_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_mentionable",
            field=models.BooleanField(default=False),
        ),
    ]
