# Generated by Django 4.2.22 on 2025-06-25 14:26

from django.db import migrations

from plane.authentication.utils.oauth_utils import update_bot_user_type


def update_bot_user_type_migration(apps, schema_editor):
    update_bot_user_type(
        application_model=apps.get_model("authentication", "Application"),
        workspace_app_installation_model=apps.get_model("authentication", "WorkspaceAppInstallation"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20250620_0618'),
        ("db", "__first__"),
    ]

    operations = [
        migrations.RunPython(update_bot_user_type_migration, reverse_code=migrations.RunPython.noop),
    ]
