# Generated by Django 4.2.22 on 2025-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20250701_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='configuration_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
