# Generated by Django 4.2.22 on 2025-09-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
        ('authentication', '0008_application_configuration_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_access_tokens', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='workspace_app_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_access_tokens', to='authentication.workspaceappinstallation'),
        ),
        migrations.AddField(
            model_name='grant',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_grants', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='grant',
            name='workspace_app_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_grants', to='authentication.workspaceappinstallation'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='workspace_app_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to='authentication.workspaceappinstallation'),
        ),
    ]
