# Generated by Django 4.2.27 on 2026-01-07 11:25

from django.db import migrations, models

def populate_app_resource_permissions(apps, schema_editor):
    Application = apps.get_model("authentication", "Application")
    Application.objects.update(resource_permissions=["read", "write"])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_identityprovider_disable_requested_authn_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resource_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_app_resource_permissions, reverse_code=migrations.RunPython.noop),
    ]
