# Generated by Django 4.2.28 on 2026-02-17 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_projectmember_source'),
        ('authentication', '0016_application_resource_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSyncConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sync_on_login', models.BooleanField(default=True)),
                ('auto_remove', models.BooleanField(default=False)),
                ('sync_offline', models.BooleanField(default=False)),
                ('group_attribute_key', models.CharField(default='groups', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sync_config', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Group Sync Config',
                'verbose_name_plural': 'Group Sync Configs',
                'db_table': 'group_sync_configs',
            },
        ),
        migrations.CreateModel(
            name='GroupMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('idp_group_name', models.CharField(db_index=True, max_length=255)),
                ('default_role', models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (5, 'Guest')], default=15)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Group Mapping',
                'verbose_name_plural': 'Group Mappings',
                'db_table': 'group_mappings',
            },
        ),
        migrations.AddConstraint(
            model_name='groupsyncconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace',), name='group_sync_config_unique_workspace_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='groupmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'idp_group_name', 'project'), name='group_mapping_unique_workspace_group_project_when_deleted_at_null'),
        ),
    ]
