# Generated by Django 4.2.28 on 2026-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_groupsyncconfig_groupmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='attribute_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='name_id_format',
            field=models.CharField(default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=255),
        ),
    ]
