services:
  web:
    image: ${DOCKERHUB_USER:-local}/plane-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: Dockerfile.node
      args:
        APP_SCOPE: web

  space:
    image: ${DOCKERHUB_USER:-local}/plane-space:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: Dockerfile.node
      args:
        APP_SCOPE: space

  admin:
    image: ${DOCKERHUB_USER:-local}/plane-admin:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: Dockerfile.node
      args:
        APP_SCOPE: admin

  live:
    image: ${DOCKERHUB_USER:-local}/plane-live:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/live/Dockerfile.live

  api:
    image: ${DOCKERHUB_USER:-local}/plane-backend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: Dockerfile.api

  proxy:
    image: ${DOCKERHUB_USER:-local}/plane-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../apps/proxy
      dockerfile: Dockerfile.ce
