services:
  web:
    image: ${DOCKERHUB_USER:-luodaxia}/plane-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../../
      dockerfile: apps/web/Dockerfile.web

  space:
    image: ${DOCKERHUB_USER:-luodaxia}/plane-space:${APP_RELEASE:-latest}
    build:
      context: ../../../
      dockerfile: apps/space/Dockerfile.space

  admin:
    image: ${DOCKERHUB_USER:-luodaxia}/plane-admin:${APP_RELEASE:-latest}
    build:
      context: ../../../
      dockerfile: apps/admin/Dockerfile.admin

  live:
    image: ${DOCKERHUB_USER:-luodaxia}/plane-live:${APP_RELEASE:-latest}
    build:
      context: ../../../
      dockerfile: apps/live/Dockerfile.live

  api:
    image: ${DOCKERHUB_USER:-luodaxia}/advanced-search:${APP_RELEASE:-v1.3.1-advanced-search}
    build:
      context: ../../../
      dockerfile: apps/api/Dockerfile.api

  proxy:
    image: ${DOCKERHUB_USER:-luodaxia}/plane-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../../
      dockerfile: apps/proxy/Dockerfile.ce
