# Generated by Django 4.2.16 on 2024-11-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0014_epicuserproperties_initiativeactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityissuestateactivity',
            name='team',
        ),
        migrations.RemoveField(
            model_name='entityprogress',
            name='team',
        ),
        migrations.RemoveField(
            model_name='entityupdates',
            name='team',
        ),
    ]
