# Generated by Django 4.2.20 on 2025-05-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_auto_20250425_0902'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0032_auto_20250509_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workitem_pages', to='db.issue')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workitem_pages', to='db.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Work Item Page',
                'verbose_name_plural': 'Work Item Pages',
                'db_table': 'workitem_pages',
                'ordering': ('-created_at',),
            },
        ),
    ]
