# Generated by Django 4.2.21 on 2025-06-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_user_is_email_valid_user_masked_at'),
        ('ee', '0037_pageuser_pageuser_unique_page_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importreport',
            name='completed_batch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='db.project'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PROGRESSING', 'Progressing'), ('CREATED', 'Created'), ('QUEUED', 'Queued'), ('INITIATED', 'Initiated'), ('PULLING', 'Pulling'), ('PULLED', 'Pulled'), ('TRANSFORMING', 'Transforming'), ('PUSHING', 'Pushing'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
