# Generated by Django 4.2.30 on 2026-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceuserconnection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workspaceconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'connection_type', 'connection_id'), name='workspace_connections_unique_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='workspaceuserconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'user', 'connection_type'), name='workspace_user_connections_unique_when_not_deleted'),
        ),
    ]
