# Generated by Django 3.2.19 on 2023-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0031_analyticview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="icon",
            new_name="emoji",
        ),
        migrations.AddField(
            model_name="project",
            name="icon_prop",
            field=models.JSONField(null=True),
        ),
    ]
