FROM node:18-alpine
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

COPY . .
RUN yarn global add turbo
RUN yarn install
EXPOSE 3333
ENV NEXT_PUBLIC_DEPLOY_WITH_NGINX=1

VOLUME [ "/app/node_modules", "/app/god-mode/node_modules"]
CMD ["yarn","dev", "--filter=god-mode"]
