"use client";
import { FC } from "react";
// icons
import {
  CalendarDays,
  Link2,
  Signal,
  Tag,
  Triangle,
  Paperclip,
  CalendarCheck2,
  CalendarClock,
  Users,
  Tags,
} from "lucide-react";
// types
import { IIssueDisplayProperties, TIssue, TIssueOrderByOptions } from "@plane/types";
// ui
import { LayersIcon, DoubleCircleIcon, DiceIcon, ContrastIcon } from "@plane/ui";
import { ISvgIcons } from "@plane/ui/src/icons/type";
import {
  SpreadsheetAssigneeColumn,
  SpreadsheetAttachmentColumn,
  SpreadsheetCreatedOnColumn,
  SpreadsheetDueDateColumn,
  SpreadsheetEstimateColumn,
  SpreadsheetLabelColumn,
  SpreadsheetModuleColumn,
  SpreadsheetCycleColumn,
  SpreadsheetLinkColumn,
  SpreadsheetPriorityColumn,
  SpreadsheetStartDateColumn,
  SpreadsheetStateColumn,
  SpreadsheetSubIssueColumn,
  SpreadsheetUpdatedOnColumn,
  SpreadsheetStandardPropertyColumn,
} from "@/components/issues/issue-layouts/spreadsheet";

export const SPREADSHEET_PROPERTY_DETAILS: {
  [key: string]: {
    title: string;
    ascendingOrderKey: TIssueOrderByOptions;
    ascendingOrderTitle: string;
    descendingOrderKey: TIssueOrderByOptions;
    descendingOrderTitle: string;
    icon: FC<ISvgIcons>;
    Column: React.FC<{
      issue: TIssue;
      onClose: () => void;
      onChange: (issue: TIssue, data: Partial<TIssue>, updates: any) => void;
      disabled: boolean;
      property: string;
    }>;
  };
} = {
  assignee: {
    title: "assignees",
    ascendingOrderKey: "assignees__first_name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-assignees__first_name",
    descendingOrderTitle: "Z",
    icon: Users,
    Column: SpreadsheetAssigneeColumn,
  },
  created_on: {
    title: "created_on",
    ascendingOrderKey: "-created_at",
    ascendingOrderTitle: "New",
    descendingOrderKey: "created_at",
    descendingOrderTitle: "Old",
    icon: CalendarDays,
    Column: SpreadsheetCreatedOnColumn,
  },
  due_date: {
    title: "due_date",
    ascendingOrderKey: "-target_date",
    ascendingOrderTitle: "New",
    descendingOrderKey: "target_date",
    descendingOrderTitle: "Old",
    icon: CalendarCheck2,
    Column: SpreadsheetDueDateColumn,
  },
  estimate: {
    title: "estimate",
    ascendingOrderKey: "estimate_point",
    ascendingOrderTitle: "Low",
    descendingOrderKey: "-estimate_point",
    descendingOrderTitle: "High",
    icon: Triangle,
    Column: SpreadsheetEstimateColumn,
  },
  labels: {
    title: "labels",
    ascendingOrderKey: "labels__name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-labels__name",
    descendingOrderTitle: "Z",
    icon: Tag,
    Column: SpreadsheetLabelColumn,
  },
  modules: {
    title: "modules",
    ascendingOrderKey: "issue_module__module__name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-issue_module__module__name",
    descendingOrderTitle: "Z",
    icon: DiceIcon,
    Column: SpreadsheetModuleColumn,
  },
  cycle: {
    title: "cycle",
    ascendingOrderKey: "issue_cycle__cycle__name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-issue_cycle__cycle__name",
    descendingOrderTitle: "Z",
    icon: ContrastIcon,
    Column: SpreadsheetCycleColumn,
  },
  priority: {
    title: "priority",
    ascendingOrderKey: "priority",
    ascendingOrderTitle: "None",
    descendingOrderKey: "-priority",
    descendingOrderTitle: "Urgent",
    icon: Signal,
    Column: SpreadsheetPriorityColumn,
  },
  start_date: {
    title: "start_date",
    ascendingOrderKey: "-start_date",
    ascendingOrderTitle: "New",
    descendingOrderKey: "start_date",
    descendingOrderTitle: "Old",
    icon: CalendarClock,
    Column: SpreadsheetStartDateColumn,
  },
  state: {
    title: "state",
    ascendingOrderKey: "state__name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-state__name",
    descendingOrderTitle: "Z",
    icon: DoubleCircleIcon,
    Column: SpreadsheetStateColumn,
  },
  updated_on: {
    title: "updated_on",
    ascendingOrderKey: "-updated_at",
    ascendingOrderTitle: "New",
    descendingOrderKey: "updated_at",
    descendingOrderTitle: "Old",
    icon: CalendarDays,
    Column: SpreadsheetUpdatedOnColumn,
  },
  link: {
    title: "link",
    ascendingOrderKey: "-link_count",
    ascendingOrderTitle: "Most",
    descendingOrderKey: "link_count",
    descendingOrderTitle: "Least",
    icon: Link2,
    Column: SpreadsheetLinkColumn,
  },
  attachment_count: {
    title: "attachment",
    ascendingOrderKey: "-attachment_count",
    ascendingOrderTitle: "Most",
    descendingOrderKey: "attachment_count",
    descendingOrderTitle: "Least",
    icon: Paperclip,
    Column: SpreadsheetAttachmentColumn,
  },
  sub_issue_count: {
    title: "sub_issue",
    ascendingOrderKey: "-sub_issues_count",
    ascendingOrderTitle: "Most",
    descendingOrderKey: "sub_issues_count",
    descendingOrderTitle: "Least",
    icon: LayersIcon,
    Column: SpreadsheetSubIssueColumn,
  },
  trip_reference_number: {
    title: "trip_reference_number",
    ascendingOrderKey: "trip_reference_number",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-trip_reference_number",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  reference_number: {
    title: "reference_number",
    ascendingOrderKey: "reference_number",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-reference_number",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  hub_code: {
    title: "hub_code",
    ascendingOrderKey: "hub_code",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-hub_code",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  hub_name: {
    title: "hub_name",
    ascendingOrderKey: "hub_name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-hub_name",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  customer_code: {
    title: "customer_code",
    ascendingOrderKey: "customer_code",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-customer_code",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  customer_name: {
    title: "customer_name",
    ascendingOrderKey: "customer_name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-customer_name",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  vendor_name: {
    title: "vendor_name",
    ascendingOrderKey: "vendor_name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-vendor_name",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  vendor_code: {
    title: "vendor_code",
    ascendingOrderKey: "vendor_code",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-vendor_code",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  worker_code: {
    title: "worker_code",
    ascendingOrderKey: "worker_code",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-worker_code",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  worker_name: {
    title: "worker_name",
    ascendingOrderKey: "worker_name",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-worker_name",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
  business_type: {
    title: "business_type",
    ascendingOrderKey: "business_type",
    ascendingOrderTitle: "A",
    descendingOrderKey: "-business_type",
    descendingOrderTitle: "Z",
    icon: Tags,
    Column: SpreadsheetStandardPropertyColumn,
  },
};

export const SPREADSHEET_PROPERTY_LIST: (keyof IIssueDisplayProperties)[] = [
  "state",
  "priority",
  "assignee",
  "labels",
  "modules",
  "cycle",
  "start_date",
  "due_date",
  "estimate",
  "created_on",
  "updated_on",
  "link",
  "attachment_count",
  "sub_issue_count",
  "trip_reference_number",
  "reference_number",
  "hub_code",
  "hub_name",
  "customer_code",
  "customer_name",
  "vendor_name",
  "vendor_code",
  "worker_code",
  "worker_name",
  "business_type",
];

export const SPREADSHEET_SELECT_GROUP = "spreadsheet-issues";
