FROM node:22-alpine
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

COPY . .

ARG TURBO_VERSION=2.8.21
RUN corepack enable pnpm && pnpm add -g turbo@${TURBO_VERSION}
RUN pnpm install

ENV VITE_ADMIN_BASE_PATH="/god-mode/"

EXPOSE 3000

VOLUME [ "/app/node_modules", "/app/admin/node_modules" ]

CMD ["pnpm", "dev", "--filter=admin"]
