# Generated by Django 4.2.11 on 2024-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0002_rename_version_instance_current_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="version",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="instance",
            name="current_version",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="instance",
            name="latest_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="namespace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="product",
            field=models.CharField(default="plane-ce", max_length=255),
        ),
    ]
