# Generated by Django 4.2.15 on 2024-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0004_changelog_deleted_at_instance_deleted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="product",
            new_name="edition",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="license_key",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="user_count",
        ),
        migrations.AddField(
            model_name="instance",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instance",
            name="edition",
            field=models.CharField(default="PLANE_COMMUNITY", max_length=255),
        ),
    ]
