# Generated by Django 3.2.14 on 2022-11-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_label_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="colour",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
