# Generated by Django 4.2.11 on 2024-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0070_apitoken_is_service_exporterhistory_filters_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IssueProperty",
            new_name="IssueUserProperty",
        ),
        migrations.AlterModelOptions(
            name="issueuserproperty",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Issue User Property",
                "verbose_name_plural": "Issue User Properties",
            },
        ),
        migrations.AlterModelTable(
            name="issueuserproperty",
            table="issue_user_properties",
        ),
        migrations.AddField(
            model_name="issuetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_issue_type_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issuetype",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
