# Generated by Django 4.2.18 on 2025-02-25 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0091_issuecomment_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deprecateddashboardwidget",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="deprecateddashboardwidget",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="deprecateddashboardwidget",
            name="dashboard",
        ),
        migrations.RemoveField(
            model_name="deprecateddashboardwidget",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="deprecateddashboardwidget",
            name="widget",
        ),
        migrations.DeleteModel(
            name="DeprecatedDashboard",
        ),
        migrations.DeleteModel(
            name="DeprecatedDashboardWidget",
        ),
        migrations.DeleteModel(
            name="DeprecatedWidget",
        ),
    ]
