# Generated by Django 4.2.27 on 2026-01-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_auto_20260105_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_view_mode',
            field=models.CharField(choices=[('full', 'Full'), ('compact', 'Compact')], default='full', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='explored_features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='tips',
            field=models.JSONField(default=dict),
        ),
    ]
