# Generated by Django 4.2.14 on 2024-10-03 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0007_workspacelicense_current_period_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityUpdates",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("CYCLE", "Cycle"),
                            ("MODULE", "Module"),
                            ("PROJECT", "Project"),
                            ("TEAM", "Team"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONTRACK", "On Track"),
                            ("OFFTRACK", "Off Track"),
                            ("AT_RISK", "At Risk"),
                            ("STARTED", "Started"),
                            ("ENDED", "Ended"),
                            ("SCOPE_INCREASED", "Scope Increased"),
                            ("SCOPE_DECREASED", "Scope Decreased"),
                        ],
                        max_length=30,
                    ),
                ),
                ("completed_issues", models.IntegerField(default=0)),
                ("total_issues", models.IntegerField(default=0)),
                ("total_estimate_points", models.FloatField(default=0)),
                ("completed_estimate_points", models.FloatField(default=0)),
                ("scope_change", models.FloatField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cycle_updates",
                        to="db.cycle",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="module_updates",
                        to="db.module",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_updates",
                        to="ee.entityupdates",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_updates",
                        to="db.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="team_updates",
                        to="db.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_updates",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Updates",
                "verbose_name_plural": "Entity Updates",
                "db_table": "entity_updates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkspaceActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        default="created",
                        max_length=255,
                        verbose_name="Action",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Field Name",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Old Value"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="New Value"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Comment"),
                ),
                ("old_identifier", models.UUIDField(null=True)),
                ("new_identifier", models.UUIDField(null=True)),
                ("epoch", models.FloatField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Activity",
                "verbose_name_plural": "Workspace Activities",
                "db_table": "workspace_activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UpdateReaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reaction", models.CharField(max_length=20)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_update_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_reactions",
                        to="ee.entityupdates",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Update Reaction",
                "verbose_name_plural": "Update Reactions",
                "db_table": "update_reactions",
                "ordering": ("-created_at",),
                "unique_together": {("actor", "reaction", "update")},
            },
        ),
        migrations.CreateModel(
            name="EntityIssueStateActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("CYCLE", "Cycle"),
                            ("MODULE", "Module"),
                            ("PROJECT", "Project"),
                            ("TEAM", "Team"),
                        ],
                        max_length=30,
                    ),
                ),
                ("state_group", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADDED", "Added"),
                            ("UPDATED", "Updated"),
                            ("REMOVED", "Removed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("estimate_value", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cycle_issue_state_progress",
                        to="db.cycle",
                    ),
                ),
                (
                    "estimate_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="issue_estimate_state_progress",
                        to="db.estimatepoint",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="issue_state_progress",
                        to="db.issue",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="module_issue_state_progress",
                        to="db.module",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_issue_state_progress",
                        to="db.project",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="entity_issue_state_progress",
                        to="db.state",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="team_issue_state_progress",
                        to="db.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_issue_state_progress",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Issue State Activity",
                "verbose_name_plural": "Entity Issue State Activities",
                "db_table": "entity_issue_state_activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EntityProgress",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("CYCLE", "Cycle"),
                            ("MODULE", "Module"),
                            ("PROJECT", "Project"),
                            ("TEAM", "Team"),
                        ],
                        max_length=30,
                    ),
                ),
                ("progress_date", models.DateTimeField()),
                ("data", models.JSONField(default=dict)),
                ("total_issues", models.IntegerField(default=0)),
                ("total_estimate_points", models.FloatField(default=0)),
                ("backlog_issues", models.IntegerField(default=0)),
                ("unstarted_issues", models.IntegerField(default=0)),
                ("started_issues", models.IntegerField(default=0)),
                ("completed_issues", models.IntegerField(default=0)),
                ("cancelled_issues", models.IntegerField(default=0)),
                ("backlog_estimate_points", models.FloatField(default=0)),
                ("unstarted_estimate_points", models.FloatField(default=0)),
                ("started_estimate_points", models.FloatField(default=0)),
                ("completed_estimate_points", models.FloatField(default=0)),
                ("cancelled_estimate_points", models.FloatField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cycle_progress",
                        to="db.cycle",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="module_progress",
                        to="db.module",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_progress",
                        to="db.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="team_progress",
                        to="db.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_progress",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Progress",
                "verbose_name_plural": "Entity Progress",
                "db_table": "entity_progress",
                "ordering": ("-created_at",),
            },
        ),
    ]
