# Generated by Django 4.2.16 on 2024-11-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('ee', '0012_intakesetting'), ('ee', '0013_alter_intakesetting_intake')]

    dependencies = [
        ('ee', '0011_initiative_initiativeproject_initiativelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_in_app_enabled', models.BooleanField(default=True)),
                ('is_email_enabled', models.BooleanField(default=False)),
                ('is_form_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_settings', to='db.intake')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Setting',
                'verbose_name_plural': 'Intake Settings',
                'db_table': 'intake_settings',
                'ordering': ('-created_at',),
            },
        ),
    ]
