# Generated by Django 4.2.16 on 2024-11-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0012_intakesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakesetting",
            name="intake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intake_settings",
                to="db.intake",
            ),
        ),
    ]
