# Generated by Django 4.2.16 on 2024-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0017_workflow_workflowtransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityupdates',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='updatereaction',
            unique_together={('actor', 'reaction', 'update', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='updatereaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('actor', 'reaction', 'update'), name='update_reaction_unique_update_actor_reaction_when_deleted_at_null'),
        ),
    ]
