# Generated by Django 4.2.17 on 2024-12-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_remove_issueversion_description_and_more'),
        ('ee', '0018_entityupdates_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_hostname', models.TextField(blank=True, null=True)),
                ('source_hostname', models.TextField(blank=True, null=True)),
                ('connection_type', models.CharField(max_length=50)),
                ('connection_id', models.CharField(max_length=255)),
                ('connection_data', models.JSONField(default=dict)),
                ('scopes', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Connection',
                'verbose_name_plural': 'Workspace Connections',
                'db_table': 'workspace_connections',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='entityupdates',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='WorkspaceEntityConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_data', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_connections', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_connections', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_connections', to='db.workspace')),
                ('workspace_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_connections', to='ee.workspaceconnection')),
            ],
            options={
                'verbose_name': 'Workspace Entity Connection',
                'verbose_name_plural': 'Workspace Entity Connections',
                'db_table': 'workspace_entity_connections',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=20)),
                ('source_access_token', models.TextField(blank=True, null=True)),
                ('source_refresh_token', models.TextField(blank=True, null=True)),
                ('source_hostname', models.TextField(blank=True, null=True)),
                ('target_access_token', models.TextField(blank=True, null=True)),
                ('target_refresh_token', models.TextField(blank=True, null=True)),
                ('target_hostname', models.TextField(blank=True, null=True)),
                ('is_pat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Credential',
                'verbose_name_plural': 'Workspace Credentials',
                'db_table': 'workspace_credentials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_size', models.IntegerField(default=0)),
                ('total_batch_count', models.IntegerField(default=0)),
                ('imported_batch_count', models.IntegerField(default=0)),
                ('errored_batch_count', models.IntegerField(default=0)),
                ('total_issue_count', models.IntegerField(default=0)),
                ('imported_issue_count', models.IntegerField(default=0)),
                ('errored_issue_count', models.IntegerField(default=0)),
                ('total_page_count', models.IntegerField(default=0)),
                ('imported_page_count', models.IntegerField(default=0)),
                ('errored_page_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Import Report',
                'verbose_name_plural': 'Import Reports',
                'db_table': 'import_reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('INITIATED', 'Initiated'), ('PULLING', 'Pulling'), ('TRANSFORMING', 'Transforming'), ('PUSHING', 'Pushing'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('with_issue_types', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('success_metadata', models.JSONField(default=dict)),
                ('error_metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ee.workspacecredential')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='db.project')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ee.importreport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'db_table': 'import_jobs',
                'ordering': ('-created_at',),
            },
        ),
    ]
