# Generated by Django 4.2.17 on 2025-01-10 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_workspacehomepreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0021_initiativeepic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='created', max_length=255, verbose_name='Action')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('old_identifier', models.UUIDField(null=True)),
                ('new_identifier', models.UUIDField(null=True)),
                ('epoch', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Workflow Activity',
                'verbose_name_plural': 'Workflow Activities',
                'db_table': 'workflow_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Approval',
                'verbose_name_plural': 'Workflow Approvals',
                'db_table': 'workflow_approvals',
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Workflow Approver',
                'verbose_name_plural': 'Workflow Approvers',
                'db_table': 'workflow_approvers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransitionactor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='workflow_transition',
        ),
        migrations.RemoveField(
            model_name='workflowtransitionactor',
            name='workspace',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtransition',
            name='workflow_transition_unique_workflow_transition_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflow',
            name='allow_issue_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='approval_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approval_transitions', to='db.state'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='rejection_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rejection_transitions', to='db.state'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='required_approvals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='type',
            field=models.CharField(default='STATE', max_length=255),
        ),
        migrations.AddField(
            model_name='workspaceconnection',
            name='connection_slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceconnection',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ee.workspacecredential'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='transition_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='db.state'),
        ),
        migrations.DeleteModel(
            name='WorkflowTransitionActor',
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvers', to='ee.workflow'),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='workflow_transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvers', to='ee.workflowtransition'),
        ),
        migrations.AddField(
            model_name='workflowapprover',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='db.issue'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='ee.workflow'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow_transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='ee.workflowtransition'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_activities', to='ee.workflow'),
        ),
        migrations.AddField(
            model_name='workflowactivity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='workflowapprover',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow_transition', 'approver'), name='workflow_approver_unique_workflow_transition_approver_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowapprover',
            unique_together={('workflow_transition', 'approver', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workflowapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow_transition', 'issue', 'approver'), name='workflow_approval_unique_transition_issue_approver_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowapproval',
            unique_together={('workflow_transition', 'issue', 'approver', 'deleted_at')},
        ),
    ]
