# Generated by Django 4.2.18 on 2025-03-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0027_projecttemplate_cover_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='ee.template'),
        ),
        migrations.AddField(
            model_name='teamspacecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
