# Generated by Django 4.2.20 on 2025-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0033_workitempage'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='relation_map',
            field=models.JSONField(default=dict),
        ),
    ]
