# Generated by Django 4.2.21 on 2025-06-20 10:56

from django.db import migrations, models
from django.utils.text import slugify
from plane.ee.utils import generate_short_id


def populate_template_short_id_and_slug(apps, schema_editor):
    Template = apps.get_model('ee', 'Template')
    
    # Get all templates that need updating
    templates = Template.objects.filter(
        models.Q(short_id__isnull=True) | models.Q(slug__isnull=True)
    ).only('id', 'name', 'short_id', 'slug')
    
    # Process in batches to avoid memory issues
    batch_size = 1000
    templates_to_update = []
    
    for template in templates:
        # Generate short_id if missing
        if not template.short_id:
            # Ensure uniqueness by checking existing short_ids
            max_attempts = 3
            for _ in range(max_attempts):
                candidate_id = generate_short_id()
                if not Template.objects.filter(short_id=candidate_id).exists():
                    template.short_id = candidate_id
                    break
            else:
                # Fallback to longer ID if all attempts fail
                template.short_id = generate_short_id(length=8)
        
        # Generate slug if missing
        if not template.slug:
            template.slug = slugify(template.name)
        
        templates_to_update.append(template)
        
        # Bulk update when batch size is reached
        if len(templates_to_update) >= batch_size:
            Template.objects.bulk_update(
                templates_to_update,
                ['short_id', 'slug'],
                batch_size=batch_size
            )
            templates_to_update = []
    
    # Update any remaining templates
    if templates_to_update:
        Template.objects.bulk_update(
            templates_to_update, 
            ['short_id', 'slug'],
            batch_size=batch_size
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0039_template_cover_image_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='short_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_template_short_id_and_slug, migrations.RunPython.noop),
    ]
