# Generated by Django 4.2.22 on 2025-08-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("db", "0100_profile_has_marketing_email_consent_and_more"),
        ("ee", "0041_workitemtemplate_parent_workitem_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringworkitemtask",
            name="interval_type",
            field=models.CharField(default="monthly", max_length=20),
        ),
        migrations.AlterField(
            model_name="recurringworkitemtask",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                help_text="Keeps Beat in sync with this row",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_workitem_task",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.CreateModel(
            name="RecurringWorkItemTaskActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        default="created", max_length=255, verbose_name="Action"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Field Name"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Old Value"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="New Value"),
                ),
                ("old_identifier", models.UUIDField(null=True)),
                ("new_identifier", models.UUIDField(null=True)),
                ("epoch", models.FloatField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_workitem_task_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_workitem_task_activities",
                        to="ee.issueproperty",
                    ),
                ),
                (
                    "recurring_workitem_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_workitem_task_activities",
                        to="ee.recurringworkitemtask",
                    ),
                ),
                (
                    "recurring_workitem_task_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_workitem_task_activities",
                        to="ee.recurringworkitemtasklog",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Workitem Task Activity",
                "verbose_name_plural": "Recurring Workitem Task Activities",
                "db_table": "recurring_workitem_task_activities",
                "ordering": ("-created_at",),
            },
        ),
    ]
