# Generated by Django 4.2.22 on 2025-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0042_recurringworkitemtask_interval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefeature',
            name='is_pi_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacefeature',
            name='is_wiki_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
