# Generated by Django 4.2.22 on 2025-08-21 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ee", "0045_pagecomment_initiative_logo_props_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="initiator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_initiators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
