# Generated by Django 4.2.22 on 2025-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0046_automationrun_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicuserproperties',
            name='rich_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='initiativeuserproperty',
            name='rich_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teamspaceuserproperty',
            name='rich_filters',
            field=models.JSONField(default=dict),
        ),
    ]
