# Generated by Django 4.2.22 on 2025-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0048_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=100),
        ),
    ]
