# Generated by Django 4.2.22 on 2025-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0049_initiative_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='status',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=100),
        ),
    ]
