# Generated by Django 4.2.22 on 2025-09-26 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0050_remove_initiative_status_alter_initiative_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeLabelAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Initiative Label Association',
                'verbose_name_plural': 'Initiative Label Associations',
                'db_table': 'initiative_label_associations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='initiativelabel',
            name='initiative_label_unique_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='initiativelabel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='initiativelabel',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='initiativelabel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='initiativelabel',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='initiativelabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='uniq_inlabel_ws_name_null'),
        ),
        migrations.AddField(
            model_name='initiativelabelassociation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='initiativelabelassociation',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_label_associations', to='ee.initiative'),
        ),
        migrations.AddField(
            model_name='initiativelabelassociation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_label_associations', to='ee.initiativelabel'),
        ),
        migrations.AddField(
            model_name='initiativelabelassociation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='initiativelabelassociation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_label_associations', to='db.workspace'),
        ),
        migrations.RemoveField(
            model_name='initiativelabel',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='initiativelabel',
            name='label',
        ),
        migrations.AddField(
            model_name='initiative',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='initiatives', through='ee.InitiativeLabelAssociation', to='ee.initiativelabel'),
        ),
        migrations.AddConstraint(
            model_name='initiativelabelassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('initiative', 'label'), name='uniq_ilassoc_init_lbl_null'),
        ),
    ]
