# Generated by Django 4.2.27 on 2026-01-22 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_workspacemember_explored_features_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0061_projectlabel_projectlabelassociation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importreport',
            name='summary_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_summary_asset', to='db.fileasset'),
        ),
        migrations.CreateModel(
            name='ImportExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(db_index=True, help_text='Type of the entity (USER, WORK_ITEM_TYPE, WORK_ITEM, etc.)', max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='info', help_text='Log level', max_length=20)),
                ('phase', models.CharField(blank=True, db_index=True, help_text='Phase of execution (PULL_USERS, PUSH_ISSUES, etc.)', max_length=100, null=True)),
                ('related_entity', models.CharField(blank=True, help_text='External ID this log relates to', max_length=255, null=True)),
                ('related_entity_type', models.CharField(blank=True, help_text='Type of the related entity, USER, WORK_ITEM_TYPE, WORK_ITEM', max_length=255, null=True)),
                ('ignore_summarization', models.BooleanField(default=False, help_text='Whether to exclude from summary calculations')),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_plane_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('entity_external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('already_exists', models.BooleanField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict, help_text='Metrics for INFO logs (total, pulled, imported, etc.)')),
                ('is_fatal', models.BooleanField(default=False)),
                ('error', models.JSONField(default=dict, help_text='Error details (message, stack, etc.)')),
                ('additional_data', models.JSONField(default=dict, help_text='Additional contextual data')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='ee.importjob')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='ee.importreport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Import Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'db_table': 'import_execution_logs',
                'ordering': ('created_at',),
            },
        ),
    ]
