# Generated by Django 4.2.25 on 2026-02-04 10:00

from django.db import migrations
from django.utils import timezone


def migrate_deploy_board_to_intake_email(apps, schema_editor):
    """
    Migrate intake email entries from DeployBoard to IntakeEmail model.
    """
    DeployBoard = apps.get_model("db", "DeployBoard")
    IntakeEmail = apps.get_model("ee", "IntakeEmail")
    Intake = apps.get_model("db", "Intake")

    # Get all DeployBoard entries where entity_name is "intake_email"
    deploy_board_intake_emails = DeployBoard.objects.filter(
        entity_name="intake_email"
    )

    # Pre-fetch intake IDs by project in a single query
    project_ids = deploy_board_intake_emails.values_list("project_id", flat=True)
    intake_by_project = {
        project_id: intake_id
        for project_id, intake_id in Intake.objects.filter(
            project_id__in=project_ids
        ).values_list("project_id", "id")
    }

    intake_emails_to_create = [
        IntakeEmail(
            intake_id=intake_by_project[db_entry.project_id],
            project_id=db_entry.project_id,
            workspace_id=db_entry.workspace_id,
            anchor=db_entry.anchor,
            is_disabled=db_entry.is_disabled,
            created_at=db_entry.created_at,
            updated_at=db_entry.updated_at,
            created_by_id=db_entry.created_by_id,
            updated_by_id=db_entry.updated_by_id,
            deleted_at=db_entry.deleted_at,
        )
        for db_entry in deploy_board_intake_emails
        if db_entry.project_id in project_ids
    ]

    if intake_emails_to_create:
        IntakeEmail.objects.bulk_create(intake_emails_to_create, batch_size=1000)

    # Soft-delete migrated DeployBoard entries
    deploy_board_intake_emails.update(deleted_at=timezone.now())


def reverse_migrate_intake_email_to_deploy_board(apps, schema_editor):
    """
    Reverse migration: Move IntakeEmail data back to DeployBoard.
    Since anchor is unique across the table, recover soft-deleted
    DeployBoard records where possible instead of creating new ones.
    """
    DeployBoard = apps.get_model("db", "DeployBoard")
    IntakeEmail = apps.get_model("ee", "IntakeEmail")

    intake_email_anchors = IntakeEmail.objects.values("anchor")

    # Restore soft-deleted DeployBoard intake_email records with matching anchors
    DeployBoard.objects.filter(
        anchor__in=intake_email_anchors,
        entity_name="intake_email",
        deleted_at__isnull=False,
    ).update(deleted_at=None)

    # Create new DeployBoard records for IntakeEmail entries that don't have
    # a restored DeployBoard. Use ignore_conflicts to handle the rare case
    # where the anchor collides with a different entity's DeployBoard record.
    restored_anchors = DeployBoard.objects.filter(
        anchor__in=intake_email_anchors,
        entity_name="intake_email",
    ).values("anchor")

    boards_to_create = [
        DeployBoard(
            entity_identifier=ie.intake_id,
            entity_name="intake_email",
            project_id=ie.project_id,
            workspace_id=ie.workspace_id,
            intake_id=ie.intake_id,
            anchor=ie.anchor,
            is_disabled=ie.is_disabled,
            created_at=ie.created_at,
            updated_at=ie.updated_at,
            created_by_id=ie.created_by_id,
            updated_by_id=ie.updated_by_id,
        )
        for ie in IntakeEmail.objects.exclude(anchor__in=restored_anchors)
    ]

    if boards_to_create:
        DeployBoard.objects.bulk_create(
            boards_to_create, batch_size=1000, ignore_conflicts=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0063_intakeemail"),
    ]

    operations = [
        migrations.RunPython(
            migrate_deploy_board_to_intake_email,
            reverse_code=reverse_migrate_intake_email_to_deploy_board,
        ),
    ]
