# Generated by Django 4.2.28 on 2026-02-05 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0118_remove_workspaceuserproperties_product_tour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0064_migrate_deploy_board_to_intake_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubscriber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subscribers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Subscriber',
                'verbose_name_plural': 'Project Subscribers',
                'db_table': 'project_subscribers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='projectsubscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'subscriber'), name='project_subscriber_unique_project_subscriber_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsubscriber',
            unique_together={('project', 'subscriber', 'deleted_at')},
        ),
    ]
