# Generated by Django 4.2.28 on 2026-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0065_projectsubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
    ]
