# Generated by Django 4.2.28 on 2026-02-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0122_workitemcommentsource_and_more'),
        ('ee', '0066_customer_archived_at_customerrequest_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeemail',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_work_item_emails', to='db.issue'),
        ),
        migrations.AddField(
            model_name='intakesetting',
            name='is_trackable_link_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='automations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='milestones',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='modules',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='recurring_work_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='property_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('DATETIME', 'Datetime'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('OPTION', 'Option'), ('RELATION', 'Relation'), ('URL', 'URL'), ('EMAIL', 'Email'), ('FILE', 'File'), ('FORMULA', 'Formula')], max_length=255),
        ),
        migrations.CreateModel(
            name='FormulaProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('formula', models.TextField()),
                ('example_output', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'formula_properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='formula_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='ee.formulaproperty'),
        ),
    ]
