# Generated by Django 4.2.27 on 2026-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0068_backfill_and_cleanup_issue_type_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PROGRESSING', 'Progressing'), ('CREATED', 'Created'), ('QUEUED', 'Queued'), ('INITIATED', 'Initiated'), ('PULLING', 'Pulling'), ('TIMED_OUT', 'Timed Out'), ('PULLED', 'Pulled'), ('TRANSFORMING', 'Transforming'), ('PUSHING', 'Pushing'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
