# Generated by Django 4.2.28 on 2026-03-03 11:00

from django.db import migrations, models
import plane.db.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0069_alter_importjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicuserproperties',
            name='last_used_filter',
            field=models.CharField(default='rich_filters', max_length=255),
        ),
        migrations.AddField(
            model_name='epicuserproperties',
            name='pql_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_pql_filter_state),
        ),
        migrations.AddField(
            model_name='initiativeuserproperty',
            name='last_used_filter',
            field=models.CharField(default='rich_filters', max_length=255),
        ),
        migrations.AddField(
            model_name='initiativeuserproperty',
            name='pql_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_pql_filter_state),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='is_workitem_description_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamspaceuserproperty',
            name='last_used_filter',
            field=models.CharField(default='rich_filters', max_length=255),
        ),
        migrations.AddField(
            model_name='teamspaceuserproperty',
            name='pql_filters',
            field=models.JSONField(default=plane.db.mixins.get_default_pql_filter_state),
        ),
        migrations.AddField(
            model_name='workspacefeature',
            name='is_release_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='is_workitem_name_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakeformfield',
            name='sort_order',
            field=models.PositiveIntegerField(default=65535),
        ),
    ]
