# Generated by Django 4.2.28 on 2026-03-05 08:48

from django.db import migrations, models
import plane.db.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0070_epicuserproperties_last_used_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicuserproperties',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
        migrations.AlterField(
            model_name='teamspaceuserproperty',
            name='filters',
            field=models.JSONField(default=plane.db.mixins.get_default_filters),
        ),
    ]
