# Generated by Django 4.2.27 on 2026-02-03 21:51


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0071_alter_epicuserproperties_filters_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workflow',
            new_name='WorkflowState',
        ),
        migrations.AlterModelOptions(
            name='workflowstate',
            options={'verbose_name': 'Workflow State', 'verbose_name_plural': 'Workflow States'},
        ),
        migrations.RemoveConstraint(
            model_name='workflowstate',
            name='workflow_unique_project_state_when_deleted_at_null',
        ),
        migrations.RenameField(
            model_name='workflowtransition',
            old_name='workflow',
            new_name='workflow_state',
        ),
        migrations.RenameField(
            model_name='workflowtransitionactivity',
            old_name='workflow',
            new_name='workflow_state',
        ),
        migrations.RenameField(
            model_name='workflowtransitionapproval',
            old_name='workflow',
            new_name='workflow_state',
        ),
        migrations.RenameField(
            model_name='workflowtransitionapprover',
            old_name='workflow',
            new_name='workflow_state',
        ),
        migrations.AlterModelTable(
            name='workflowstate',
            table='workflow_states',
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By', db_index=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project', db_index=False)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By', db_index=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace', db_index=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowWorkItemType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_work_item_types', to='db.issuetype')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_work_item_types', to='ee.workflow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Work Item Type',
                'verbose_name_plural': 'Workflow Work Item Types',
                'db_table': 'workflow_work_item_types',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='type',
            field=models.CharField(default='transition', max_length=255),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_states', to='ee.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together={('project', 'state', 'workflow', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'state', 'workflow'), name='workflow_state_unique_project_state_when_deleted_at_null'),
        ),
        migrations.AddField(
            model_name='workflowtransitionactivity',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_activities', to='ee.workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowworkitemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('work_item_type', 'project'), name='workflow_work_item_type_unique_work_item_type_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowworkitemtype',
            unique_together={('work_item_type', 'project', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workspace'], name='workflows_workspa_29029e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project'], name='workflows_project_ae1218_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_by'], name='workflows_created_9ae838_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['updated_by'], name='workflows_updated_1ef20a_idx'),
        ),

        # This tells Django that ForeignKeys have db_index=True (default)
        # but we don't actually create duplicate indexes in the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='workflow',
                    name='created_by',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By'
                    ),
                ),
                migrations.AlterField(
                    model_name='workflow',
                    name='project',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_%(class)s',
                        to='db.project'
                    ),
                ),
                migrations.AlterField(
                    model_name='workflow',
                    name='updated_by',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last Modified By'
                    ),
                ),
                migrations.AlterField(
                    model_name='workflow',
                    name='workspace',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='workspace_%(class)s',
                        to='db.workspace'
                    ),
                ),
            ],
            database_operations=[
                # No actual database changes - indexes already created above
            ],
        ),
    ]
