# Generated by Django 4.2.29 on 2026-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0073_backfill_workflow_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='is_parallel_cycles_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
