# Generated by Django 4.2.29 on 2026-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0074_projectfeature_is_parallel_cycles_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefeature',
            name='is_workitem_hierarchy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('ISSUE', 'Issue'), ('USER', 'User'), ('RELEASE', 'Release')], max_length=255, null=True),
        ),
    ]
