# Generated by Django 4.2.29 on 2026-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0075_workspacefeature_is_workitem_hierarchy_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefeature',
            name='is_work_item_types_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
