# Generated by Django 4.2.29 on 2026-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0076_workspacefeature_is_work_item_types_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationnode',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, help_text='Last time this scheduled trigger was dispatched.', null=True),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='next_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Next scheduled execution time (UTC). Only for scheduled triggers.', null=True),
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(condition=models.Q(('handler_name', 'scheduled'), ('is_enabled', True)), fields=['next_scheduled_at'], name='autonode_sched_next_idx'),
        ),
    ]
