# Generated by Django 4.2.29 on 2026-03-30 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid



def create_automation_project_associations(apps, schema_editor):
    Automation = apps.get_model('ee', 'Automation')
    AutomationProjectAssociation = apps.get_model('ee', 'AutomationProjectAssociation')
    
    automation_project_associations = []
    for automation in Automation.objects.values_list('id', 'project_id', 'workspace_id', 'created_by_id'):
        automation_project_associations.append(
            AutomationProjectAssociation(
                automation_id=automation[0],
                project_id=automation[1],
                workspace_id=automation[2],
                created_by_id=automation[3],
             )
            )
    AutomationProjectAssociation.objects.bulk_create(automation_project_associations)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_estimate_external_id_estimate_external_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0078_workflowtransitionhook_workflowtransitionhookstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationProjectAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Automation Project Association',
                'verbose_name_plural': 'Automation Project Associations',
                'db_table': 'automation_project_associations',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='automation',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Whether this automation is global (not tied to a specific project)'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='automationactivity',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='automationedge',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='automationnode',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='automationversion',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddConstraint(
            model_name='automation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', True)), fields=('workspace', 'name'), name='automation_unique_workspace_name_when_not_deleted'),
        ),
        migrations.AddField(
            model_name='automationprojectassociation',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_projects', to='ee.automation'),
        ),
        migrations.AddField(
            model_name='automationprojectassociation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='automationprojectassociation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_automations', to='db.project'),
        ),
        migrations.AddField(
            model_name='automationprojectassociation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='automationprojectassociation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='automationprojectassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('automation', 'project'), name='automation_project_unique_automation_project'),
        ),
        migrations.RunPython(create_automation_project_associations, reverse_code=migrations.RunPython.noop),
    ]
