# Generated by Django 4.2.29 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0079_automationprojectassociation_automation_is_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=False),
        ),        
        migrations.AddField(
            model_name='workspacefeature',
            name='work_item_type_default_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
