# Generated by Django 4.2.29 on 2026-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0079_automationprojectassociation_automation_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefeature',
            name='work_item_type_default_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
