# Generated by Django 4.2.29 on 2026-04-06 16:04

from django.db import migrations
from django.conf import settings

import logging

logger = logging.getLogger("plane.migrations")


def backfill_workflow_states(apps, schema_editor):
    """Dispatch background task to seed WorkflowState entries for all default workflows."""
    try:
        from plane.ee.bgtasks.seed_workflow_projects_task import seed_workflow_default_states

        # If self-managed, run synchronously to ensure data consistency before proceeding. Otherwise, dispatch as a background task.
        if settings.IS_SELF_MANAGED:
            seed_workflow_default_states()
        else:
            seed_workflow_default_states.delay()
        logger.info("Dispatched seed_workflow_default_states background task")
    except Exception as e:
        logger.warning(f"Could not dispatch seed_workflow_default_states task: {e}")


def reverse_backfill_workflow_states(apps, schema_editor):
    """Reverse: delete all WorkflowState entries linked to default workflows."""
    Workflow = apps.get_model("ee", "Workflow")
    WorkflowState = apps.get_model("ee", "WorkflowState")

    default_workflow_ids = Workflow.objects.filter(is_default=True).values_list("id", flat=True)
    deleted, _ = WorkflowState.objects.filter(workflow_id__in=default_workflow_ids).delete()
    logger.info(f"Reverse backfill: deleted {deleted} workflow state entries")



class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('ee', '0080_alter_workflow_is_active'),
    ]

    operations = [
        migrations.RunPython(backfill_workflow_states, reverse_backfill_workflow_states),
    ]
