# Generated by Django 4.2.30 on 2026-04-17 08:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0083_auto_20260326_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
