# Generated by Django 4.2.27 on 2026-02-05 14:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("db", "0118_remove_workspaceuserproperties_product_tour_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Script Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Script Description"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System scripts are built-in and read-only for all workspaces",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("node22", "Node.js 22")],
                        default="node22",
                        max_length=30,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "code_type",
                    models.CharField(
                        blank=True,
                        choices=[("inline", "Inline"), ("main_fn", "Main Function")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("build", models.TextField(blank=True, null=True)),
                (
                    "function_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Function names used by this script (detected during build)",
                        size=None,
                    ),
                ),
                ("env_variables", models.JSONField(blank=True, null=True)),
                ("allowed_domains", models.JSONField(blank=True, null=True)),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        help_text="Variable definitions that the script expects from the invoking system",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_scripts",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system scripts",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_scripts",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "scripts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptFunction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Function Name"),
                ),
                ("description", models.TextField(verbose_name="Function Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("http", "HTTP"),
                            ("notifications", "Notifications"),
                            ("data", "Data"),
                            ("utils", "Utils"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=list, help_text="Array of parameter definitions"
                    ),
                ),
                (
                    "return_type",
                    models.CharField(
                        default="void", max_length=255, verbose_name="Return Type"
                    ),
                ),
                ("code", models.TextField(verbose_name="Function Code")),
                (
                    "usage_example",
                    models.TextField(
                        blank=True, null=True, verbose_name="Usage Example"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System functions are built-in and immutable by users",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system functions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_functions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "script_functions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("manual", "Manual"),
                            ("automation", "Automation"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the triggering entity (automation rule, runner task, etc.)",
                        null=True,
                    ),
                ),
                (
                    "trigger_context",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context about the trigger (event payload, etc.)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("errored", "Errored"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("code", models.TextField(blank=True, null=True)),
                ("code_type", models.CharField(blank=True, max_length=30, null=True)),
                ("platform", models.CharField(blank=True, max_length=30, null=True)),
                ("build", models.TextField(blank=True, null=True)),
                ("input_data", models.JSONField(blank=True, null=True)),
                (
                    "execution_variables",
                    models.JSONField(
                        blank=True,
                        help_text="Variable values passed by the invoking system during execution",
                        null=True,
                    ),
                ),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("error_data", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_script_executions",
                        to="db.project",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="runnerctl.script",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_script_executions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "script_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="scriptfunction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("workspace__isnull", False)
                ),
                fields=("name", "workspace"),
                name="unique_function_name_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="scriptfunction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_system", True)),
                fields=("name",),
                name="unique_system_function_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="script",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_system", True)),
                fields=("name",),
                name="unique_system_script_name",
            ),
        ),
    ]
