# Generated by Django 4.2.29 on 2026-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runnerctl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('automation', 'Automation'), ('workflow_transition', 'Workflow Transition'), ('cron_trigger', 'Cron Trigger')], default='automation', max_length=255),
        ),
    ]
