import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/accordion/index.ts",
    "src/animated-counter/index.ts",
    "src/avatar/index.ts",
    "src/button/index.ts",
    "src/calendar/index.ts",
    "src/card/index.ts",
    "src/charts/*/index.ts",
    "src/collapsible/index.ts",
    "src/combobox/index.ts",
    "src/command/index.ts",
    "src/context-menu/index.ts",
    "src/dialog/index.ts",
    "src/empty-state/index.ts",
    "src/emoji-icon-picker/index.ts",
    "src/emoji-reaction/index.ts",
    "src/emoji-reaction-picker/index.ts",
    "src/icons/index.ts",
    "src/input/index.ts",
    "src/menu/index.ts",
    "src/pill/index.ts",
    "src/popover/index.ts",
    "src/portal/index.ts",
    "src/scrollarea/index.ts",
    "src/skeleton/index.ts",
    "src/switch/index.ts",
    "src/table/index.ts",
    "src/tabs/index.ts",
    "src/toast/index.ts",
    "src/toolbar/index.ts",
    "src/tooltip/index.ts",
    "src/utils/index.ts",
  ],
  outDir: "dist",
  format: ["esm", "cjs"],
  exports: {
    customExports: (out) => ({
      ...out,
      "./styles/fonts": "./dist/styles/fonts/index.css",
      "./styles/react-day-picker": "./dist/styles/react-day-picker.css",
    }),
  },
  copy: ["src/styles"],
  dts: true,
  clean: true,
  sourcemap: false,
});
