import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/accordion/index.ts",
    "src/animated-counter/index.ts",
    "src/avatar/index.ts",
    "src/badge/index.ts",
    "src/banner/index.ts",
    "src/button/index.ts",
    "src/calendar/index.ts",
    "src/card/index.ts",
    "src/charts/*/index.ts",
    "src/collapsible/index.ts",
    "src/combobox/index.ts",
    "src/command/index.ts",
    "src/context-menu/index.ts",
    "src/dialog/index.ts",
    "src/empty-state/index.ts",
    "src/emoji-icon-picker/index.ts",
    "src/emoji-reaction/index.ts",
    "src/emoji-reaction-picker/index.ts",
    "src/icon-button/index.ts",
    "src/icons/index.ts",
    "src/input/index.ts",
    "src/menu/index.ts",
    "src/pill/index.ts",
    "src/popover/index.ts",
    "src/portal/index.ts",
    "src/scrollarea/index.ts",
    "src/skeleton/index.ts",
    "src/switch/index.ts",
    "src/table/index.ts",
    "src/tab-navigation/index.ts",
    "src/tabs/index.ts",
    "src/toast/index.ts",
    "src/toolbar/index.ts",
    "src/tooltip/index.ts",
    "src/utils/index.ts",
  ],
  format: ["esm"],
  dts: true,
  copy: ["src/styles"],
  exports: {
    customExports: (exports) => ({
      ...exports,
      "./styles/react-day-picker.css": "./dist/styles/react-day-picker.css",
      "./styles/react-day-picker": "./dist/styles/react-day-picker.css",
    }),
  },
  platform: "neutral",
});
