from django.urls import path

from .views import (
    ProductEndpoint,
    PaymentLinkEndpoint,
    WorkspaceProductEndpoint,
    SubscriptionEndpoint,
    WorkspaceLicenseEndpoint,
    UpgradeSubscriptionEndpoint,
    FeatureFlagProxyEndpoint,
    WorkspaceLicenseRefreshEndpoint,
    WorkspaceLicenseSyncEndpoint,
    WorkspaceFreeTrialEndpoint,
    PurchaseSubscriptionSeatEndpoint,
    RemoveUnusedSeatsEndpoint,
    LicenseDeActivateEndpoint,
    CancelTrialSubscriptionEndpoint,
    ProrationPreviewEndpoint,
    FeatureFlagProxySpaceEndpoint,
    LicenseActivateUploadEndpoint,
    LicenseFileFetchEndpoint,
)

urlpatterns = [
    path("workspaces/<str:slug>/products/", ProductEndpoint.as_view(), name="products"),
    path(
        "workspaces/<str:slug>/current-plan/",
        WorkspaceProductEndpoint.as_view(),
        name="products",
    ),
    path(
        "workspaces/<str:slug>/payment-link/",
        PaymentLinkEndpoint.as_view(),
        name="products",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/",
        SubscriptionEndpoint.as_view(),
        name="subscription",
    ),
    path(
        "workspaces/<str:slug>/licenses/",
        WorkspaceLicenseEndpoint.as_view(),
        name="license-activate",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/upgrade/",
        UpgradeSubscriptionEndpoint.as_view(),
        name="subscription",
    ),
    path(
        "workspaces/<str:slug>/flags/", FeatureFlagProxyEndpoint.as_view(), name="flags"
    ),
    path(
        "workspaces/<str:slug>/license-refresh/",
        WorkspaceLicenseRefreshEndpoint.as_view(),
        name="license-refresh",
    ),
    path(
        "workspaces/license-sync/",
        WorkspaceLicenseSyncEndpoint.as_view(),
        name="license-sync",
    ),
    path(
        "workspaces/<str:slug>/trial-subscriptions/",
        WorkspaceFreeTrialEndpoint.as_view(),
        name="trial-subscriptions",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/seats/",
        PurchaseSubscriptionSeatEndpoint.as_view(),
        name="purchase-subscription-seats",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/seats/remove-unused/",
        RemoveUnusedSeatsEndpoint.as_view(),
        name="remove-unused-seats",
    ),
    path(
        "workspaces/<str:slug>/licenses/deactivate/",
        LicenseDeActivateEndpoint.as_view(),
        name="license-deactivate",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/cancel-trial/",
        CancelTrialSubscriptionEndpoint.as_view(),
        name="cancel-trial",
    ),
    path(
        "workspaces/<str:slug>/subscriptions/proration-preview/",
        ProrationPreviewEndpoint.as_view(),
        name="proration-preview",
    ),
    path(
        "workspaces/<str:slug>/licenses/upload/",
        LicenseActivateUploadEndpoint.as_view(),
        name="license-upload",
    ),
    path(
        "workspaces/<str:slug>/license-file/",
        LicenseFileFetchEndpoint.as_view(),
        name="license-fetch",
    ),
]


space_urlpatterns = [
    path(
        "anchor/<str:anchor>/flags/",
        FeatureFlagProxySpaceEndpoint.as_view(),
        name="flags",
    ),
]
