# SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
# SPDX-License-Identifier: LicenseRef-Plane-Commercial
#
# Licensed under the Plane Commercial License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# https://plane.so/legals/eula
#
# DO NOT remove or modify this notice.
# NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f15f14eb119d"
down_revision: Union[str, None] = "f0a5b792a8c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_models",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("base_api_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=True),
        sa.Column("connector_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("deployment_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_embedding_models_id"), "embedding_models", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_embedding_models_id"), table_name="embedding_models")
    op.drop_table("embedding_models")
    # ### end Alembic commands ###
