FROM caddy:builder AS caddy-builder

RUN xcaddy build
    # --with github.com/caddy-dns/cloudflare \
    # --with github.com/caddy-dns/digitalocean \
    # --with github.com/mholt/caddy-l4

FROM caddy:alpine

RUN apk add nss-tools bash curl 

COPY --from=caddy-builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile.ee /etc/caddy/Caddyfile