#!/usr/bin/env bash
# Build 3 dynamic SHB Docker images for linux/amd64 and export as tar.gz archives.
# Also generates docker-compose.shb.yml override (dynamic services only).
#
# Images: plane-frontend (web), plane-admin (admin), plane-backend (api/worker/beat)
# Static services (space, live, proxy, postgres, redis) are pre-loaded at initial provisioning.
#
# Usage: ./scripts/build-shb-images.sh
#
# Produces:
#   dist/.shb-version                    ← version tag (e.g. shb_v1.2.0)
#   dist/plane-frontend-shb_v*.tar.gz
#   dist/plane-admin-shb_v*.tar.gz
#   dist/plane-backend-shb_v*.tar.gz
#   docker-compose.shb.yml               ← compose override for dynamic services

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT_DIR}"

DIST_DIR="dist"

# ── Preflight checks ──────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1    || { echo "ERROR: docker not found"; exit 1; }
command -v node >/dev/null 2>&1      || { echo "ERROR: node not found (required for version detection)"; exit 1; }
docker buildx version >/dev/null 2>&1 || { echo "ERROR: docker buildx not available. Enable Docker Desktop buildx."; exit 1; }

# ── Auto-detect version from package.json ─────────────────────────────────────
VERSION=$(node -p "require('./package.json').version")
TAG="shb_v${VERSION}"

echo "========================================="
echo " SHB Docker Build"
echo "========================================="
echo " Version  : ${VERSION}"
echo " Tag      : ${TAG}"
echo " Platform : linux/amd64"
echo " Output   : ${DIST_DIR}/"
echo "========================================="
echo ""

mkdir -p "${DIST_DIR}"

# ── Image build definitions: NAME | DOCKERFILE | BUILD_CONTEXT ───────────────
# 3 dynamic images only (web/admin/api share the same release package slot per service).
IMAGES=(
  "plane-frontend:apps/web/Dockerfile.web:."
  "plane-admin:apps/admin/Dockerfile.admin:."
  # "plane-space:apps/space/Dockerfile.space:."
  # "plane-live:apps/live/Dockerfile.live:."
  "plane-backend:apps/api/Dockerfile.api:./apps/api"
  # "plane-proxy:apps/proxy/Dockerfile.ce:./apps/proxy"
)

TOTAL=${#IMAGES[@]}

# ── Build + save loop ─────────────────────────────────────────────────────────
for i in "${!IMAGES[@]}"; do
  IDX=$((i + 1))
  ENTRY="${IMAGES[$i]}"

  # Parse tuple
  NAME="${ENTRY%%:*}"
  REST="${ENTRY#*:}"
  DOCKERFILE="${REST%%:*}"
  CONTEXT="${REST##*:}"

  IMAGE="makeplane/${NAME}:${TAG}"
  OUTFILE="${DIST_DIR}/${NAME}-${TAG}.tar.gz"

  echo "[${IDX}/${TOTAL}] Building ${IMAGE} ..."
  docker buildx build \
    --platform linux/amd64 \
    --load \
    -f "${DOCKERFILE}" \
    -t "${IMAGE}" \
    "${CONTEXT}"

  echo "[${IDX}/${TOTAL}] Saving → ${OUTFILE} ..."
  docker save "${IMAGE}" | gzip > "${OUTFILE}"
  echo "        Size: $(du -sh "${OUTFILE}" | cut -f1)"
  echo ""
done

# ── Write version manifest ────────────────────────────────────────────────────
echo "${TAG}" > "${DIST_DIR}/.shb-version"
echo "Version manifest written → ${DIST_DIR}/.shb-version"
echo ""

# ── Verify architecture of built images ───────────────────────────────────────
echo "Verifying linux/amd64 architecture ..."
bash "${SCRIPT_DIR}/verify-release-package-architecture.sh" "${DIST_DIR}"
echo ""

# ── Generate docker-compose.shb.yml override (dynamic services only) ─────────
cat > docker-compose.shb.yml <<EOF
# Auto-generated by scripts/build-shb-images.sh — do not edit manually.
# Version: ${TAG}
# Dynamic services only: web, admin, api, worker, beat-worker, migrator.
# Static services (space, live, proxy, postgres, redis) are not overridden here.

services:
  web:
    image: makeplane/plane-frontend:${TAG}

  admin:
    image: makeplane/plane-admin:${TAG}

  api:
    image: makeplane/plane-backend:${TAG}

  worker:
    image: makeplane/plane-backend:${TAG}

  beat-worker:
    image: makeplane/plane-backend:${TAG}

  migrator:
    image: makeplane/plane-backend:${TAG}
EOF

echo "Override file generated → docker-compose.shb.yml"
echo ""

# ── Final summary ─────────────────────────────────────────────────────────────
echo "========================================="
echo " Build Complete — Tag: ${TAG}"
echo "========================================="
echo ""
echo "Files in ${DIST_DIR}/:"
ls -lh "${DIST_DIR}/" | grep -v "^total"
echo ""
echo "Next steps:"
echo "  1. Transfer to production server:"
echo "     scp -r ${DIST_DIR}/ docker-compose.shb.yml scripts/deploy-shb.sh user@server:/path/to/plane/"
echo "  2. On server: chmod +x /path/to/plane/scripts/deploy-shb.sh"
echo "  3. On server: cd /path/to/plane && ./scripts/deploy-shb.sh"
echo ""
