// Workspace Events
export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const UPDATE_WORKSPACE = "UPDATE_WORKSPACE";
export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
// Workspace invite related
export const WORKSPACE_USER_INVITE = "WORKSPACE_USER_INVITE";
export const WORKSPACE_USER_INVITE_ACCEPT = "WORKSPACE_USER_INVITE_ACCEPT";
export const WORKSPACE_USER_BULK_INVITE_ACCEPT = "WORKSPACE_USER_BULK_INVITE_ACCEPT";
// Project Events
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_MEMBER_INVITE = "PROJECT_MEMBER_INVITE";
// Issue Events
export const ISSUE_CREATE = "ISSUE_CREATE";
export const ISSUE_UPDATE = "ISSUE_UPDATE";
export const ISSUE_DELETE = "ISSUE_DELETE";
// Cycle Events
export const CYCLE_CREATE = "CYCLE_CREATE";
export const CYCLE_UPDATE = "CYCLE_UPDATE";
export const CYCLE_DELETE = "CYCLE_DELETE";
// State Events
export const STATE_CREATE = "STATE_CREATE";
export const STATE_UPDATE = "STATE_UPDATE";
export const STATE_DELETE = "STATE_DELETE";
// Module Events
export const MODULE_CREATE = "MODULE_CREATE";
export const MODULE_UPDATE = "MODULE_UPDATE";
export const MODULE_DELETE = "MODULE_DELETE";
// Pages Events
export const PAGE_CREATE = "PAGE_CREATE";
export const PAGE_UPDATE = "PAGE_UPDATE";
export const PAGE_DELETE = "PAGE_DELETE";
// View Events
export const VIEW_CREATE = "VIEW_CREATE";
export const VIEW_UPDATE = "VIEW_UPDATE";
export const VIEW_DELETE = "VIEW_DELETE";
// Issue Comment Events
export const ISSUE_COMMENT_CREATE = "ISSUE_COMMENT_CREATE";
export const ISSUE_COMMENT_UPDATE = "ISSUE_COMMENT_UPDATE";
export const ISSUE_COMMENT_DELETE = "ISSUE_COMMENT_DELETE";
// Miscellaneous Events
export const TOGGLE_CYCLE_ON = "TOGGLE_CYCLE_ON";
export const TOGGLE_CYCLE_OFF = "TOGGLE_CYCLE_OFF";
export const TOGGLE_MODULE_ON = "TOGGLE_MODULE_ON";
export const TOGGLE_MODULE_OFF = "TOGGLE_MODULE_OFF";
export const TOGGLE_VIEW_ON = "TOGGLE_VIEW_ON";
export const TOGGLE_VIEW_OFF = "TOGGLE_VIEW_OFF";
export const TOGGLE_PAGES_ON = "TOGGLE_PAGES_ON";
export const TOGGLE_PAGES_OFF = "TOGGLE_PAGES_OFF";
export const TOGGLE_STATE_ON = "TOGGLE_STATE_ON";
export const TOGGLE_STATE_OFF = "TOGGLE_STATE_OFF";
export const TOGGLE_INBOX_ON = "TOGGLE_INBOX_ON";
export const TOGGLE_INBOX_OFF = "TOGGLE_INBOX_OFF";
// Integration Events
export const ADD_WORKSPACE_INTEGRATION = "ADD_WORKSPACE_INTEGRATION";
export const REMOVE_WORKSPACE_INTEGRATION = "REMOVE_WORKSPACE_INTEGRATION";
// GitHub Sync Events
export const GITHUB_REPO_SYNC = "GITHUB_REPO_SYNC";
// Page Blocks Events
export const PAGE_BLOCK_CREATE = "PAGE_BLOCK_CREATE";
export const PAGE_BLOCK_UPDATE = "PAGE_BLOCK_UPDATE";
export const PAGE_BLOCK_DELETE = "PAGE_BLOCK_DELETE";
export const PAGE_BLOCK_CONVERTED_TO_ISSUE = "PAGE_BLOCK_CONVERTED_TO_ISSUE";
// Issue Label Events
export const ISSUE_LABEL_CREATE = "ISSUE_LABEL_CREATE";
export const ISSUE_LABEL_UPDATE = "ISSUE_LABEL_UPDATE";
export const ISSUE_LABEL_DELETE = "ISSUE_LABEL_DELETE";
// GPT Events
export const ASK_GPT = "ASK_GPT";
export const USE_GPT_RESPONSE_IN_ISSUE = "USE_GPT_RESPONSE_IN_ISSUE";
export const USE_GPT_RESPONSE_IN_PAGE_BLOCK = "USE_GPT_RESPONSE_IN_PAGE_BLOCK";
// Issue Estimate Events
export const ESTIMATE_CREATE = "ESTIMATE_CREATE";
export const ESTIMATE_UPDATE = "ESTIMATE_UPDATE";
export const ESTIMATE_DELETE = "ESTIMATE_DELETE";
// Inbox Events
export const INBOX_CREATE = "INBOX_CREATE";
export const INBOX_UPDATE = "INBOX_UPDATE";
export const INBOX_DELETE = "INBOX_DELETE";
export const INBOX_ISSUE_CREATE = "INBOX_ISSUE_CREATE";
export const INBOX_ISSUE_UPDATE = "INBOX_ISSUE_UPDATE";
export const INBOX_ISSUE_DELETE = "INBOX_ISSUE_DELETE";
export const INBOX_ISSUE_DUPLICATED = "INBOX_ISSUE_DUPLICATED";
export const INBOX_ISSUE_ACCEPTED = "INBOX_ISSUE_ACCEPTED";
export const INBOX_ISSUE_SNOOZED = "INBOX_ISSUE_SNOOZED";
export const INBOX_ISSUE_REJECTED = "INBOX_ISSUE_REJECTED";
// Importer Events
export const GITHUB_IMPORTER_CREATE = "GITHUB_IMPORTER_CREATE";
export const GITHUB_IMPORTER_DELETE = "GITHUB_IMPORTER_DELETE";
export const JIRA_IMPORTER_CREATE = "JIRA_IMPORTER_CREATE";
export const JIRA_IMPORTER_DELETE = "JIRA_IMPORTER_DELETE";
// Exporter Events
export const CSV_EXPORTER_CREATE = "CSV_EXPORTER_CREATE";
// Analytics Events
export const WORKSPACE_SCOPE_AND_DEMAND_ANALYTICS = "WORKSPACE_SCOPE_AND_DEMAND_ANALYTICS";
export const WORKSPACE_CUSTOM_ANALYTICS = "WORKSPACE_CUSTOM_ANALYTICS";
export const WORKSPACE_ANALYTICS_EXPORT = "WORKSPACE_ANALYTICS_EXPORT";
// Project Analytics
export const PROJECT_SCOPE_AND_DEMAND_ANALYTICS = "PROJECT_SCOPE_AND_DEMAND_ANALYTICS";
export const PROJECT_CUSTOM_ANALYTICS = "PROJECT_CUSTOM_ANALYTICS";
export const PROJECT_ANALYTICS_EXPORT = "PROJECT_ANALYTICS_EXPORT";
// Cycle Custom
export const CYCLE_SCOPE_AND_DEMAND_ANALYTICS = "CYCLE_SCOPE_AND_DEMAND_ANALYTICS";
export const CYCLE_CUSTOM_ANALYTICS = "CYCLE_CUSTOM_ANALYTICS";
export const CYCLE_ANALYTICS_EXPORT = "CYCLE_ANALYTICS_EXPORT";
// Module Custom
export const MODULE_SCOPE_AND_DEMAND_ANALYTICS = "MODULE_SCOPE_AND_DEMAND_ANALYTICS";
export const MODULE_CUSTOM_ANALYTICS = "MODULE_CUSTOM_ANALYTICS";
export const MODULE_ANALYTICS_EXPORT = "MODULE_ANALYTICS_EXPORT";
// Reaction Events
export const ISSUE_REACTION_CREATE = "ISSUE_REACTION_CREATE";
export const ISSUE_COMMENT_REACTION_CREATE = "ISSUE_COMMENT_REACTION_CREATE";
export const ISSUE_REACTION_DELETE = "ISSUE_REACTION_DELETE";
export const ISSUE_COMMENT_REACTION_DELETE = "ISSUE_COMMENT_REACTION_DELETE";
// Leave Project/Workspace
export const PROJECT_MEMBER_LEAVE = "PROJECT_MEMBER_LEAVE";
export const WORKSPACE_MEMBER_LEAVE = "WORKSPACE_MEMBER_LEAVE";
