# Generated by Django 4.2.30 on 2026-05-21 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecOpsTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('TO_DO', 'To Do'), ('DONE', 'Done'), ('PENDING', 'Pending'), ('ESCALATED', 'Escalated'), ('WAITING_FOR_SUPPORT', 'Waiting for Support'), ('WAITING_FOR_CUSTOMER', 'Waiting for Customer')], default='TO_DO', max_length=30)),
                ('plane_work_item_id', models.UUIDField(blank=True, null=True)),
                ('source_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secops_tickets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secops_tickets', to='db.workspace')),
            ],
            options={
                'verbose_name': 'SecOps Ticket',
                'verbose_name_plural': 'SecOps Tickets',
                'db_table': 'secops_tickets',
                'ordering': ('ticket_number',),
            },
        ),
    ]
