# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Research namespace routes.

All research endpoints live under ``/api/research/`` and are registered ahead
of the existing ``/api/`` include so the namespace can never be shadowed by an
upstream route (P0-COMPAT-02).
"""

from django.urls import path

from plane.research.views import (
    ResearchApprovalFlowDetailEndpoint,
    ResearchApprovalFlowListCreateEndpoint,
    ResearchApprovalRequestActionEndpoint,
    ResearchApprovalRequestDetailEndpoint,
    ResearchApprovalRequestHistoryEndpoint,
    ResearchApprovalRequestListCreateEndpoint,
    ResearchAuditEventListEndpoint,
    ResearchReportAttachmentDetailEndpoint,
    ResearchReportAttachmentListCreateEndpoint,
    ResearchReportAttachmentPresignEndpoint,
    ResearchReportMarkdownImportEndpoint,
    ResearchHealthEndpoint,
    ResearchIdentityMappingDetailEndpoint,
    ResearchIdentityMappingListCreateEndpoint,
    ResearchIdentityMeEndpoint,
    ResearchMentorBindingDetailEndpoint,
    ResearchMentorBindingListCreateEndpoint,
    ResearchOrgUnitDetailEndpoint,
    ResearchOrgUnitListCreateEndpoint,
    ResearchOrgUnitMemberDetailEndpoint,
    ResearchOrgUnitMemberListCreateEndpoint,
    ResearchOrgUnitPiTransferEndpoint,
    ResearchProjectArchiveEndpoint,
    ResearchProjectDetailEndpoint,
    ResearchProjectListCreateEndpoint,
    ResearchProjectRestoreEndpoint,
    ResearchReportAcceptEndpoint,
    ResearchReportAccessEndpoint,
    ResearchReportDetailEndpoint,
    ResearchReportHistoryEndpoint,
    ResearchReportListCreateEndpoint,
    ResearchReportReturnEndpoint,
    ResearchReportSubmitEndpoint,
    ResearchReportSummaryEndpoint,
    ResearchReportTemplateDetailEndpoint,
    ResearchReportTemplateListCreateEndpoint,
    ResearchSettingsEndpoint,
    ResearchProjectStageListCreateEndpoint,
    ResearchStageDetailEndpoint,
    ResearchStageEnterEndpoint,
    ResearchStageGateEndpoint,
    ResearchStageMaterialDetailEndpoint,
    ResearchStageMaterialListCreateEndpoint,
    ResearchStageMaterialSubmitEndpoint,
    ResearchStageMaterialVersionsEndpoint,
    ResearchStagePassEndpoint,
    ResearchStageReopenEndpoint,
    ResearchStageRequirementDetailEndpoint,
    ResearchStageRequirementEndpoint,
    ResearchStageReturnEndpoint,
    ResearchStageSubmitEndpoint,
    ResearchStageTransitionsEndpoint,
    ResearchReviewListEndpoint,
    ResearchStageReviewDetailEndpoint,
    ResearchStageReviewListCreateEndpoint,
    ResearchStageReviewerDetailEndpoint,
    ResearchStageReviewerListCreateEndpoint,
    ResearchStageReviewerRemindEndpoint,
    ResearchStageReviewRevisionEndpoint,
    ResearchStageReviewRevisionListEndpoint,
    ResearchStageReviewSummaryEndpoint,
    ResearchLiteratureDetailEndpoint,
    ResearchLiteratureImportEndpoint,
    ResearchLiteratureListCreateEndpoint,
    ResearchLiteraturePdfEndpoint,
    ResearchLiteratureStatusEndpoint,
    ResearchLiteratureThresholdEndpoint,
    ResearchExperimentAmendmentActionEndpoint,
    ResearchExperimentAmendmentDetailEndpoint,
    ResearchExperimentAmendmentListCreateEndpoint,
    ResearchExperimentArchiveEndpoint,
    ResearchExperimentAssetDetailEndpoint,
    ResearchExperimentAssetEndpoint,
    ResearchExperimentDetailEndpoint,
    ResearchExperimentListCreateEndpoint,
    ResearchExperimentStatusEndpoint,
    ResearchExperimentSubmitEndpoint,
    ResearchExperimentVersionsEndpoint,
    ResearchCodeArtifactDetailEndpoint,
    ResearchCodeArtifactListCreateEndpoint,
    ResearchCodeRepositoryDetailEndpoint,
    ResearchCodeRepositoryListCreateEndpoint,
    ResearchCodeRepositorySyncEndpoint,
    ResearchCodeSnapshotEndpoint,
    ResearchCodeSummaryEndpoint,
    ResearchStageMaterialOverrideEndpoint,
    ResearchProjectProgressEndpoint,
    ResearchChainExportEndpoint,
    ResearchOutcomeDetailEndpoint,
    ResearchOutcomeLinkEndpoint,
    ResearchOutcomeListCreateEndpoint,
    ResearchDeviceExecutionSearchEndpoint,
    ResearchExternalReferenceDetailEndpoint,
    ResearchExternalReferenceLinkEndpoint,
    ResearchExternalReferenceListCreateEndpoint,
    ResearchIntegrationCallLogEndpoint,
    ResearchIntegrationHealthEndpoint,
    ResearchIntegrationListEndpoint,
    ResearchIntegrationSearchEndpoint,
    ResearchKnowledgeSearchEndpoint,
    ResearchLabAssetSearchEndpoint,
    ResearchLabRunSearchEndpoint,
    ResearchRdAnalysisSearchEndpoint,
    ResearchRdProjectSearchEndpoint,
)

urlpatterns = [
    # availability probe (works even when the module switch is off)
    path("research/health/", ResearchHealthEndpoint.as_view(), name="research-health"),
    # ------------------------------------------------------------------
    # P1 stage workflow (§5.2) - additive, nothing below is renumbered
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/stages/",
        ResearchProjectStageListCreateEndpoint.as_view(),
        name="research-project-stages",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/",
        ResearchStageDetailEndpoint.as_view(),
        name="research-stage",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/enter/",
        ResearchStageEnterEndpoint.as_view(),
        name="research-stage-enter",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/submit/",
        ResearchStageSubmitEndpoint.as_view(),
        name="research-stage-submit",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/return/",
        ResearchStageReturnEndpoint.as_view(),
        name="research-stage-return",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/pass/",
        ResearchStagePassEndpoint.as_view(),
        name="research-stage-pass",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reopen/",
        ResearchStageReopenEndpoint.as_view(),
        name="research-stage-reopen",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/gate/",
        ResearchStageGateEndpoint.as_view(),
        name="research-stage-gate",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/transitions/",
        ResearchStageTransitionsEndpoint.as_view(),
        name="research-stage-transitions",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/materials/",
        ResearchStageMaterialListCreateEndpoint.as_view(),
        name="research-stage-materials",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/",
        ResearchStageMaterialDetailEndpoint.as_view(),
        name="research-stage-material",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/submit/",
        ResearchStageMaterialSubmitEndpoint.as_view(),
        name="research-stage-material-submit",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/versions/",
        ResearchStageMaterialVersionsEndpoint.as_view(),
        name="research-stage-material-versions",
    ),
    path(
        "research/workspaces/<str:slug>/stage-requirements/",
        ResearchStageRequirementEndpoint.as_view(),
        name="research-stage-requirements",
    ),
    path(
        "research/workspaces/<str:slug>/stage-requirements/<uuid:pk>/",
        ResearchStageRequirementDetailEndpoint.as_view(),
        name="research-stage-requirement",
    ),
    # ------------------------------------------------------------------
    # P1 multi reviewer review flow (§5.3)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reviewers/",
        ResearchStageReviewerListCreateEndpoint.as_view(),
        name="research-stage-reviewers",
    ),
    path(
        "research/workspaces/<str:slug>/reviewers/<uuid:assignment_id>/",
        ResearchStageReviewerDetailEndpoint.as_view(),
        name="research-stage-reviewer",
    ),
    path(
        "research/workspaces/<str:slug>/reviewers/<uuid:assignment_id>/remind/",
        ResearchStageReviewerRemindEndpoint.as_view(),
        name="research-stage-reviewer-remind",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reviews/",
        ResearchStageReviewListCreateEndpoint.as_view(),
        name="research-stage-reviews",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/review-summary/",
        ResearchStageReviewSummaryEndpoint.as_view(),
        name="research-stage-review-summary",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/",
        ResearchReviewListEndpoint.as_view(),
        name="research-reviews",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/",
        ResearchStageReviewDetailEndpoint.as_view(),
        name="research-stage-review",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/revise/",
        ResearchStageReviewRevisionEndpoint.as_view(),
        name="research-stage-review-revise",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/revisions/",
        ResearchStageReviewRevisionListEndpoint.as_view(),
        name="research-stage-review-revisions",
    ),
    # ------------------------------------------------------------------
    # P1 literature collection (§5.4)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/literature/",
        ResearchLiteratureListCreateEndpoint.as_view(),
        name="research-literature",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/literature/threshold/",
        ResearchLiteratureThresholdEndpoint.as_view(),
        name="research-literature-threshold",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/literature/import/",
        ResearchLiteratureImportEndpoint.as_view(),
        name="research-literature-import",
    ),
    path(
        "research/workspaces/<str:slug>/literature/<uuid:entry_id>/",
        ResearchLiteratureDetailEndpoint.as_view(),
        name="research-literature-entry",
    ),
    path(
        "research/workspaces/<str:slug>/literature/<uuid:entry_id>/status/",
        ResearchLiteratureStatusEndpoint.as_view(),
        name="research-literature-status",
    ),
    path(
        "research/workspaces/<str:slug>/literature/<uuid:entry_id>/pdf/",
        ResearchLiteraturePdfEndpoint.as_view(),
        name="research-literature-pdf",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/override/",
        ResearchStageMaterialOverrideEndpoint.as_view(),
        name="research-stage-material-override",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/progress/",
        ResearchProjectProgressEndpoint.as_view(),
        name="research-project-progress",
    ),
    # ------------------------------------------------------------------
    # P1 outcomes and the exported reference list (§5.8)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/outcomes/",
        ResearchOutcomeListCreateEndpoint.as_view(),
        name="research-outcomes",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/chain/export/",
        ResearchChainExportEndpoint.as_view(),
        name="research-chain-export",
    ),
    path(
        "research/workspaces/<str:slug>/outcomes/<uuid:outcome_id>/",
        ResearchOutcomeDetailEndpoint.as_view(),
        name="research-outcome",
    ),
    path(
        "research/workspaces/<str:slug>/outcomes/<uuid:outcome_id>/links/",
        ResearchOutcomeLinkEndpoint.as_view(),
        name="research-outcome-links",
    ),
    path(
        "research/workspaces/<str:slug>/outcomes/<uuid:outcome_id>/links/<uuid:link_id>/",
        ResearchOutcomeLinkEndpoint.as_view(),
        name="research-outcome-link",
    ),
    # ------------------------------------------------------------------
    # P1 integration base layer (§5.7)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/integrations/",
        ResearchIntegrationListEndpoint.as_view(),
        name="research-integrations",
    ),
    path(
        "research/workspaces/<str:slug>/integrations/health/",
        ResearchIntegrationHealthEndpoint.as_view(),
        name="research-integration-health",
    ),
    path(
        "research/workspaces/<str:slug>/integrations/call-logs/",
        ResearchIntegrationCallLogEndpoint.as_view(),
        name="research-integration-call-logs",
    ),
    path(
        "research/workspaces/<str:slug>/integrations/search/",
        ResearchIntegrationSearchEndpoint.as_view(),
        name="research-integration-search",
    ),
    path(
        "research/workspaces/<str:slug>/knowledge/entries/",
        ResearchKnowledgeSearchEndpoint.as_view(),
        name="research-knowledge-entries",
    ),
    path(
        "research/workspaces/<str:slug>/lab/runs/",
        ResearchLabRunSearchEndpoint.as_view(),
        name="research-lab-runs",
    ),
    path(
        "research/workspaces/<str:slug>/lab/assets/",
        ResearchLabAssetSearchEndpoint.as_view(),
        name="research-lab-assets",
    ),
    path(
        "research/workspaces/<str:slug>/lab/device-executions/",
        ResearchDeviceExecutionSearchEndpoint.as_view(),
        name="research-device-executions",
    ),
    path(
        "research/workspaces/<str:slug>/rd/projects/",
        ResearchRdProjectSearchEndpoint.as_view(),
        name="research-rd-projects",
    ),
    path(
        "research/workspaces/<str:slug>/rd/analyses/",
        ResearchRdAnalysisSearchEndpoint.as_view(),
        name="research-rd-analyses",
    ),
    path(
        "research/workspaces/<str:slug>/external-references/",
        ResearchExternalReferenceListCreateEndpoint.as_view(),
        name="research-external-references",
    ),
    path(
        "research/workspaces/<str:slug>/external-references/<uuid:reference_id>/",
        ResearchExternalReferenceDetailEndpoint.as_view(),
        name="research-external-reference",
    ),
    path(
        "research/workspaces/<str:slug>/external-references/<uuid:reference_id>/links/",
        ResearchExternalReferenceLinkEndpoint.as_view(),
        name="research-external-reference-links",
    ),
    path(
        "research/workspaces/<str:slug>/external-references/<uuid:reference_id>/links/<uuid:link_id>/",
        ResearchExternalReferenceLinkEndpoint.as_view(),
        name="research-external-reference-link",
    ),
    # ------------------------------------------------------------------
    # P1 experiment records and amendments (§5.5)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/experiments/",
        ResearchExperimentListCreateEndpoint.as_view(),
        name="research-experiments",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/",
        ResearchExperimentDetailEndpoint.as_view(),
        name="research-experiment",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/status/",
        ResearchExperimentStatusEndpoint.as_view(),
        name="research-experiment-status",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/submit/",
        ResearchExperimentSubmitEndpoint.as_view(),
        name="research-experiment-submit",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/archive/",
        ResearchExperimentArchiveEndpoint.as_view(),
        name="research-experiment-archive",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/versions/",
        ResearchExperimentVersionsEndpoint.as_view(),
        name="research-experiment-versions",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/assets/",
        ResearchExperimentAssetEndpoint.as_view(),
        name="research-experiment-assets",
    ),
    path(
        "research/workspaces/<str:slug>/experiments/<uuid:record_id>/amendments/",
        ResearchExperimentAmendmentListCreateEndpoint.as_view(),
        name="research-experiment-amendments",
    ),
    path(
        "research/workspaces/<str:slug>/experiment-assets/<uuid:link_id>/",
        ResearchExperimentAssetDetailEndpoint.as_view(),
        name="research-experiment-asset",
    ),
    path(
        "research/workspaces/<str:slug>/amendments/<uuid:amendment_id>/",
        ResearchExperimentAmendmentDetailEndpoint.as_view(),
        name="research-experiment-amendment",
    ),
    path(
        "research/workspaces/<str:slug>/amendments/<uuid:amendment_id>/<str:action>/",
        ResearchExperimentAmendmentActionEndpoint.as_view(),
        name="research-experiment-amendment-action",
    ),
    # ------------------------------------------------------------------
    # P1 code repositories and snapshots (§5.6)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/code-repositories/",
        ResearchCodeRepositoryListCreateEndpoint.as_view(),
        name="research-code-repositories",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/code-summary/",
        ResearchCodeSummaryEndpoint.as_view(),
        name="research-code-summary",
    ),
    path(
        "research/workspaces/<str:slug>/code-repositories/<uuid:repository_id>/",
        ResearchCodeRepositoryDetailEndpoint.as_view(),
        name="research-code-repository",
    ),
    path(
        "research/workspaces/<str:slug>/code-repositories/<uuid:repository_id>/sync/",
        ResearchCodeRepositorySyncEndpoint.as_view(),
        name="research-code-repository-sync",
    ),
    path(
        "research/workspaces/<str:slug>/code-repositories/<uuid:repository_id>/artifacts/",
        ResearchCodeArtifactListCreateEndpoint.as_view(),
        name="research-code-artifacts",
    ),
    path(
        "research/workspaces/<str:slug>/code-repositories/<uuid:repository_id>/snapshots/",
        ResearchCodeSnapshotEndpoint.as_view(),
        name="research-code-snapshots",
    ),
    path(
        "research/workspaces/<str:slug>/code-artifacts/<uuid:artifact_id>/",
        ResearchCodeArtifactDetailEndpoint.as_view(),
        name="research-code-artifact",
    ),
    # office approvals
    path(
        "research/workspaces/<str:slug>/approval-flows/",
        ResearchApprovalFlowListCreateEndpoint.as_view(),
        name="research-approval-flows",
    ),
    path(
        "research/workspaces/<str:slug>/approval-flows/<uuid:pk>/",
        ResearchApprovalFlowDetailEndpoint.as_view(),
        name="research-approval-flow",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/",
        ResearchApprovalRequestListCreateEndpoint.as_view(),
        name="research-approval-requests",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/",
        ResearchApprovalRequestDetailEndpoint.as_view(),
        name="research-approval-request",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/history/",
        ResearchApprovalRequestHistoryEndpoint.as_view(),
        name="research-approval-request-history",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/<str:action>/",
        ResearchApprovalRequestActionEndpoint.as_view(),
        name="research-approval-request-action",
    ),
    # identity
    path(
        "research/workspaces/<str:slug>/reports/",
        ResearchReportListCreateEndpoint.as_view(),
        name="research-reports",
    ),
    path(
        "research/workspaces/<str:slug>/reports/summary/",
        ResearchReportSummaryEndpoint.as_view(),
        name="research-report-summary",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/",
        ResearchReportDetailEndpoint.as_view(),
        name="research-report",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/submit/",
        ResearchReportSubmitEndpoint.as_view(),
        name="research-report-submit",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/return/",
        ResearchReportReturnEndpoint.as_view(),
        name="research-report-return",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/accept/",
        ResearchReportAcceptEndpoint.as_view(),
        name="research-report-accept",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/history/",
        ResearchReportHistoryEndpoint.as_view(),
        name="research-report-history",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/access/",
        ResearchReportAccessEndpoint.as_view(),
        name="research-report-access",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/",
        ResearchReportAttachmentListCreateEndpoint.as_view(),
        name="research-report-attachments",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/presign/",
        ResearchReportAttachmentPresignEndpoint.as_view(),
        name="research-report-attachment-presign",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/<uuid:attachment_id>/",
        ResearchReportAttachmentDetailEndpoint.as_view(),
        name="research-report-attachment",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/import-markdown/",
        ResearchReportMarkdownImportEndpoint.as_view(),
        name="research-report-import-markdown",
    ),
    path(
        "research/workspaces/<str:slug>/report-templates/",
        ResearchReportTemplateListCreateEndpoint.as_view(),
        name="research-report-templates",
    ),
    path(
        "research/workspaces/<str:slug>/report-templates/<uuid:pk>/",
        ResearchReportTemplateDetailEndpoint.as_view(),
        name="research-report-template",
    ),
    path(
        "research/workspaces/<str:slug>/audit-events/",
        ResearchAuditEventListEndpoint.as_view(),
        name="research-audit-events",
    ),
    path(
        "research/workspaces/<str:slug>/settings/",
        ResearchSettingsEndpoint.as_view(),
        name="research-settings",
    ),
    path(
        "research/workspaces/<str:slug>/identity/me/",
        ResearchIdentityMeEndpoint.as_view(),
        name="research-identity-me",
    ),
    path(
        "research/workspaces/<str:slug>/identity/mappings/",
        ResearchIdentityMappingListCreateEndpoint.as_view(),
        name="research-identity-mappings",
    ),
    path(
        "research/workspaces/<str:slug>/identity/mappings/<uuid:pk>/",
        ResearchIdentityMappingDetailEndpoint.as_view(),
        name="research-identity-mapping",
    ),
    # organisation tree
    path(
        "research/workspaces/<str:slug>/org-units/",
        ResearchOrgUnitListCreateEndpoint.as_view(),
        name="research-org-units",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/",
        ResearchOrgUnitDetailEndpoint.as_view(),
        name="research-org-unit",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/members/",
        ResearchOrgUnitMemberListCreateEndpoint.as_view(),
        name="research-org-unit-members",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/members/<uuid:member_id>/",
        ResearchOrgUnitMemberDetailEndpoint.as_view(),
        name="research-org-unit-member",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/pi/",
        ResearchOrgUnitPiTransferEndpoint.as_view(),
        name="research-org-unit-pi",
    ),
    # direct advisors
    path(
        "research/workspaces/<str:slug>/projects/",
        ResearchProjectListCreateEndpoint.as_view(),
        name="research-projects",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/",
        ResearchProjectDetailEndpoint.as_view(),
        name="research-project",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/archive/",
        ResearchProjectArchiveEndpoint.as_view(),
        name="research-project-archive",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/restore/",
        ResearchProjectRestoreEndpoint.as_view(),
        name="research-project-restore",
    ),
    path(
        "research/workspaces/<str:slug>/mentors/",
        ResearchMentorBindingListCreateEndpoint.as_view(),
        name="research-mentors",
    ),
    path(
        "research/workspaces/<str:slug>/mentors/<uuid:pk>/",
        ResearchMentorBindingDetailEndpoint.as_view(),
        name="research-mentor",
    ),
]
