# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Research namespace routes.

All research endpoints live under ``/api/research/`` and are registered ahead
of the existing ``/api/`` include so the namespace can never be shadowed by an
upstream route (P0-COMPAT-02).
"""

from django.urls import path

from plane.research.views import (
    ResearchApprovalFlowDetailEndpoint,
    ResearchApprovalFlowListCreateEndpoint,
    ResearchApprovalRequestActionEndpoint,
    ResearchApprovalRequestDetailEndpoint,
    ResearchApprovalRequestHistoryEndpoint,
    ResearchApprovalRequestListCreateEndpoint,
    ResearchAuditEventListEndpoint,
    ResearchReportAttachmentDetailEndpoint,
    ResearchReportAttachmentListCreateEndpoint,
    ResearchReportAttachmentPresignEndpoint,
    ResearchReportMarkdownImportEndpoint,
    ResearchHealthEndpoint,
    ResearchIdentityMappingDetailEndpoint,
    ResearchIdentityMappingListCreateEndpoint,
    ResearchIdentityMeEndpoint,
    ResearchMentorBindingDetailEndpoint,
    ResearchMentorBindingListCreateEndpoint,
    ResearchOrgUnitDetailEndpoint,
    ResearchOrgUnitListCreateEndpoint,
    ResearchOrgUnitMemberDetailEndpoint,
    ResearchOrgUnitMemberListCreateEndpoint,
    ResearchOrgUnitPiTransferEndpoint,
    ResearchProjectArchiveEndpoint,
    ResearchProjectDetailEndpoint,
    ResearchProjectListCreateEndpoint,
    ResearchProjectRestoreEndpoint,
    ResearchReportAcceptEndpoint,
    ResearchReportAccessEndpoint,
    ResearchReportDetailEndpoint,
    ResearchReportHistoryEndpoint,
    ResearchReportListCreateEndpoint,
    ResearchReportReturnEndpoint,
    ResearchReportSubmitEndpoint,
    ResearchReportSummaryEndpoint,
    ResearchReportTemplateDetailEndpoint,
    ResearchReportTemplateListCreateEndpoint,
    ResearchSettingsEndpoint,
    ResearchProjectStageListCreateEndpoint,
    ResearchStageDetailEndpoint,
    ResearchStageEnterEndpoint,
    ResearchStageGateEndpoint,
    ResearchStageMaterialDetailEndpoint,
    ResearchStageMaterialListCreateEndpoint,
    ResearchStageMaterialSubmitEndpoint,
    ResearchStageMaterialVersionsEndpoint,
    ResearchStagePassEndpoint,
    ResearchStageReopenEndpoint,
    ResearchStageRequirementDetailEndpoint,
    ResearchStageRequirementEndpoint,
    ResearchStageReturnEndpoint,
    ResearchStageSubmitEndpoint,
    ResearchStageTransitionsEndpoint,
    ResearchReviewListEndpoint,
    ResearchStageReviewDetailEndpoint,
    ResearchStageReviewListCreateEndpoint,
    ResearchStageReviewerDetailEndpoint,
    ResearchStageReviewerListCreateEndpoint,
    ResearchStageReviewerRemindEndpoint,
    ResearchStageReviewRevisionEndpoint,
    ResearchStageReviewRevisionListEndpoint,
    ResearchStageReviewSummaryEndpoint,
)

urlpatterns = [
    # availability probe (works even when the module switch is off)
    path("research/health/", ResearchHealthEndpoint.as_view(), name="research-health"),
    # ------------------------------------------------------------------
    # P1 stage workflow (§5.2) - additive, nothing below is renumbered
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/stages/",
        ResearchProjectStageListCreateEndpoint.as_view(),
        name="research-project-stages",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/",
        ResearchStageDetailEndpoint.as_view(),
        name="research-stage",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/enter/",
        ResearchStageEnterEndpoint.as_view(),
        name="research-stage-enter",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/submit/",
        ResearchStageSubmitEndpoint.as_view(),
        name="research-stage-submit",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/return/",
        ResearchStageReturnEndpoint.as_view(),
        name="research-stage-return",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/pass/",
        ResearchStagePassEndpoint.as_view(),
        name="research-stage-pass",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reopen/",
        ResearchStageReopenEndpoint.as_view(),
        name="research-stage-reopen",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/gate/",
        ResearchStageGateEndpoint.as_view(),
        name="research-stage-gate",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/transitions/",
        ResearchStageTransitionsEndpoint.as_view(),
        name="research-stage-transitions",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/materials/",
        ResearchStageMaterialListCreateEndpoint.as_view(),
        name="research-stage-materials",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/",
        ResearchStageMaterialDetailEndpoint.as_view(),
        name="research-stage-material",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/submit/",
        ResearchStageMaterialSubmitEndpoint.as_view(),
        name="research-stage-material-submit",
    ),
    path(
        "research/workspaces/<str:slug>/materials/<uuid:material_id>/versions/",
        ResearchStageMaterialVersionsEndpoint.as_view(),
        name="research-stage-material-versions",
    ),
    path(
        "research/workspaces/<str:slug>/stage-requirements/",
        ResearchStageRequirementEndpoint.as_view(),
        name="research-stage-requirements",
    ),
    path(
        "research/workspaces/<str:slug>/stage-requirements/<uuid:pk>/",
        ResearchStageRequirementDetailEndpoint.as_view(),
        name="research-stage-requirement",
    ),
    # ------------------------------------------------------------------
    # P1 multi reviewer review flow (§5.3)
    # ------------------------------------------------------------------
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reviewers/",
        ResearchStageReviewerListCreateEndpoint.as_view(),
        name="research-stage-reviewers",
    ),
    path(
        "research/workspaces/<str:slug>/reviewers/<uuid:assignment_id>/",
        ResearchStageReviewerDetailEndpoint.as_view(),
        name="research-stage-reviewer",
    ),
    path(
        "research/workspaces/<str:slug>/reviewers/<uuid:assignment_id>/remind/",
        ResearchStageReviewerRemindEndpoint.as_view(),
        name="research-stage-reviewer-remind",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/reviews/",
        ResearchStageReviewListCreateEndpoint.as_view(),
        name="research-stage-reviews",
    ),
    path(
        "research/workspaces/<str:slug>/stages/<uuid:stage_id>/review-summary/",
        ResearchStageReviewSummaryEndpoint.as_view(),
        name="research-stage-review-summary",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/",
        ResearchReviewListEndpoint.as_view(),
        name="research-reviews",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/",
        ResearchStageReviewDetailEndpoint.as_view(),
        name="research-stage-review",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/revise/",
        ResearchStageReviewRevisionEndpoint.as_view(),
        name="research-stage-review-revise",
    ),
    path(
        "research/workspaces/<str:slug>/reviews/<uuid:review_id>/revisions/",
        ResearchStageReviewRevisionListEndpoint.as_view(),
        name="research-stage-review-revisions",
    ),
    # office approvals
    path(
        "research/workspaces/<str:slug>/approval-flows/",
        ResearchApprovalFlowListCreateEndpoint.as_view(),
        name="research-approval-flows",
    ),
    path(
        "research/workspaces/<str:slug>/approval-flows/<uuid:pk>/",
        ResearchApprovalFlowDetailEndpoint.as_view(),
        name="research-approval-flow",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/",
        ResearchApprovalRequestListCreateEndpoint.as_view(),
        name="research-approval-requests",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/",
        ResearchApprovalRequestDetailEndpoint.as_view(),
        name="research-approval-request",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/history/",
        ResearchApprovalRequestHistoryEndpoint.as_view(),
        name="research-approval-request-history",
    ),
    path(
        "research/workspaces/<str:slug>/approval-requests/<uuid:pk>/<str:action>/",
        ResearchApprovalRequestActionEndpoint.as_view(),
        name="research-approval-request-action",
    ),
    # identity
    path(
        "research/workspaces/<str:slug>/reports/",
        ResearchReportListCreateEndpoint.as_view(),
        name="research-reports",
    ),
    path(
        "research/workspaces/<str:slug>/reports/summary/",
        ResearchReportSummaryEndpoint.as_view(),
        name="research-report-summary",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/",
        ResearchReportDetailEndpoint.as_view(),
        name="research-report",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/submit/",
        ResearchReportSubmitEndpoint.as_view(),
        name="research-report-submit",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/return/",
        ResearchReportReturnEndpoint.as_view(),
        name="research-report-return",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/accept/",
        ResearchReportAcceptEndpoint.as_view(),
        name="research-report-accept",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/history/",
        ResearchReportHistoryEndpoint.as_view(),
        name="research-report-history",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/access/",
        ResearchReportAccessEndpoint.as_view(),
        name="research-report-access",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/",
        ResearchReportAttachmentListCreateEndpoint.as_view(),
        name="research-report-attachments",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/presign/",
        ResearchReportAttachmentPresignEndpoint.as_view(),
        name="research-report-attachment-presign",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/attachments/<uuid:attachment_id>/",
        ResearchReportAttachmentDetailEndpoint.as_view(),
        name="research-report-attachment",
    ),
    path(
        "research/workspaces/<str:slug>/reports/<uuid:report_id>/import-markdown/",
        ResearchReportMarkdownImportEndpoint.as_view(),
        name="research-report-import-markdown",
    ),
    path(
        "research/workspaces/<str:slug>/report-templates/",
        ResearchReportTemplateListCreateEndpoint.as_view(),
        name="research-report-templates",
    ),
    path(
        "research/workspaces/<str:slug>/report-templates/<uuid:pk>/",
        ResearchReportTemplateDetailEndpoint.as_view(),
        name="research-report-template",
    ),
    path(
        "research/workspaces/<str:slug>/audit-events/",
        ResearchAuditEventListEndpoint.as_view(),
        name="research-audit-events",
    ),
    path(
        "research/workspaces/<str:slug>/settings/",
        ResearchSettingsEndpoint.as_view(),
        name="research-settings",
    ),
    path(
        "research/workspaces/<str:slug>/identity/me/",
        ResearchIdentityMeEndpoint.as_view(),
        name="research-identity-me",
    ),
    path(
        "research/workspaces/<str:slug>/identity/mappings/",
        ResearchIdentityMappingListCreateEndpoint.as_view(),
        name="research-identity-mappings",
    ),
    path(
        "research/workspaces/<str:slug>/identity/mappings/<uuid:pk>/",
        ResearchIdentityMappingDetailEndpoint.as_view(),
        name="research-identity-mapping",
    ),
    # organisation tree
    path(
        "research/workspaces/<str:slug>/org-units/",
        ResearchOrgUnitListCreateEndpoint.as_view(),
        name="research-org-units",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/",
        ResearchOrgUnitDetailEndpoint.as_view(),
        name="research-org-unit",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/members/",
        ResearchOrgUnitMemberListCreateEndpoint.as_view(),
        name="research-org-unit-members",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/members/<uuid:member_id>/",
        ResearchOrgUnitMemberDetailEndpoint.as_view(),
        name="research-org-unit-member",
    ),
    path(
        "research/workspaces/<str:slug>/org-units/<uuid:pk>/pi/",
        ResearchOrgUnitPiTransferEndpoint.as_view(),
        name="research-org-unit-pi",
    ),
    # direct advisors
    path(
        "research/workspaces/<str:slug>/projects/",
        ResearchProjectListCreateEndpoint.as_view(),
        name="research-projects",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/",
        ResearchProjectDetailEndpoint.as_view(),
        name="research-project",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/archive/",
        ResearchProjectArchiveEndpoint.as_view(),
        name="research-project-archive",
    ),
    path(
        "research/workspaces/<str:slug>/projects/<uuid:project_id>/restore/",
        ResearchProjectRestoreEndpoint.as_view(),
        name="research-project-restore",
    ),
    path(
        "research/workspaces/<str:slug>/mentors/",
        ResearchMentorBindingListCreateEndpoint.as_view(),
        name="research-mentors",
    ),
    path(
        "research/workspaces/<str:slug>/mentors/<uuid:pk>/",
        ResearchMentorBindingDetailEndpoint.as_view(),
        name="research-mentor",
    ),
]
