RESTRICTED_WORKSPACE_SLUGS = [
    "404",
    "accounts",
    "api",
    "create-workspace",
    "god-mode",
    "installations",
    "invitations",
    "onboarding",
    "profile",
    "spaces",
    "workspace-invitations",
    "password",
    "flags",
    "monitor",
    "monitoring",
    "ingest",
    "plane-pro",
    "plane-ultimate",
    "enterprise",
    "plane-enterprise",
    "disco",
    "silo",
    "chat",
    "calendar",
    "drive",
    "channels",
    "upgrade",
    "billing",
    "sign-in",
    "sign-up",
    "signin",
    "signup",
    "config",
]

ALLOWED_CUSTOM_PROPERTY_WORKSPACE_MAP = {
    "heineken": [
        "Stays (in days)",
        "Approved Cost (in BRL)",
        "Invoice",  
    ],
    "heineken-br1-dev": [
        "Stays (in days)",
        "Approved Cost (in BRL)",
        "Invoice",
    ],
    "heineken-br1-test": [
        "Stays (in days)",
        "Approved Cost (in BRL)",
        "Invoice",
    ],
    "heineken-br1": [
        "Stays (in days)",
        "Approved Cost (in BRL)",
        "Invoice",
    ]
}