RESTRICTED_WORKSPACE_SLUGS = [
    "404",
    "accounts",
    "api",
    "create-workspace",
    "god-mode",
    "installations",
    "invitations",
    "onboarding",
    "profile",
    "spaces",
    "workspace-invitations",
    "password",
    "flags",
    "monitor",
    "monitoring",
    "ingest",
    "plane-pro",
    "plane-ultimate",
    "enterprise",
    "plane-enterprise",
    "disco",
    "silo",
    "chat",
    "calendar",
    "drive",
    "channels",
    "upgrade",
    "billing",
    "sign-in",
    "sign-up",
    "signin",
    "signup",
    "config",
]

ALLOWED_CUSTOM_PROPERTY_WORKSPACE_MAP = {
    "heineken": [
        "Hub Code",
        "Customer Name",
        "Vendor Code",
        "Vendor Name",
        "Customer Code",
        "Consignment Number",
        "Trip Number",
        "Hub Name"
    ]
}