# Generated by Django 4.2.20 on 2025-04-25 11:13

from django.db import migrations
from django.conf import settings

def create_initial_apps(apps, schema_editor):
    # Getting the models from apps to avoid circular imports
    Application = apps.get_model("authentication", "Application")
    ApplicationSecret = apps.get_model("silo", "ApplicationSecret")
    User = apps.get_model("db", "User")
    InstanceAdmin = apps.get_model("license", "InstanceAdmin")
    
    # Importing the function directly here to avoid circular imports
    from plane.silo.services.generate_application import create_applications
    
    # Getting the first instance admin
    instance_admin = InstanceAdmin.objects.first()
    if instance_admin:
        create_applications(
            user_id=instance_admin.user.id,
            application_model=Application,
            application_secret_model=ApplicationSecret,
            user_model=User
        )

class Migration(migrations.Migration):
    dependencies = [
        ('silo', '0001_initial'),
        ('authentication', '0001_initial'),  # Add dependency to authentication app
        ('db', '0001_initial'),  # Add dependency to db app
        ('license', '0001_initial'),  # Add dependency to license app
    ]

    operations = [
        migrations.RunPython(
            create_initial_apps,
            reverse_code=migrations.RunPython.noop
        )
    ]