# Generated by Django 4.2.22 on 2025-06-23 15:11

from django.db import migrations

def create_sentry_app(apps, schema_editor):
    # Getting the models from apps to avoid circular imports
    Application = apps.get_model("authentication", "Application")
    ApplicationSecret = apps.get_model("silo", "ApplicationSecret")
    User = apps.get_model("db", "User")
    InstanceAdmin = apps.get_model("license", "InstanceAdmin")

    # Importing the function and constants directly here to avoid circular imports
    from plane.silo.services.generate_application import generate_application
    from plane.silo.utils.constants import APPLICATIONS

    # Getting the first instance admin
    instance_admin = InstanceAdmin.objects.first()
    if instance_admin:
        generate_application(
            user_id=instance_admin.user.id,
            app_key=APPLICATIONS["sentry"]["key"],
            application_model=Application,
            application_secret_model=ApplicationSecret,
            user_model=User,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0004_create_github_enterprise_app'),
    ]

    operations = [
        migrations.RunPython(create_sentry_app, reverse_code=migrations.RunPython.noop)
    ]
