# Generated by Django 4.2.22 on 2025-09-03 12:36

from django.db import migrations


def split_github_entity_connections_util(apps, schema_editor):
    WorkspaceEntityConnection = apps.get_model("ee.WorkspaceEntityConnection")
    
    from plane.silo.services import split_github_entity_connections
    split_github_entity_connections(WorkspaceEntityConnection)

class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0005_create_sentry_app'),
    ]

    operations = [
        migrations.RunPython(split_github_entity_connections_util, reverse_code=migrations.RunPython.noop),
    ]
