# SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
# SPDX-License-Identifier: LicenseRef-Plane-Commercial
#
# Licensed under the Plane Commercial License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# https://plane.so/legals/eula
#
# DO NOT remove or modify this notice.
# NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.

# Generated by Django 4.2.27 on 2026-01-21 18:16

from django.db import migrations

def create_runner_app(apps, schema_editor):
    # Getting the models from apps to avoid circular imports
    Application = apps.get_model("authentication", "Application")
    ApplicationSecret = apps.get_model("silo", "ApplicationSecret")
    User = apps.get_model("db", "User")
    InstanceAdmin = apps.get_model("license", "InstanceAdmin")

    # Importing the function and constants directly here to avoid circular imports
    from plane.silo.services.generate_application import generate_application
    from plane.silo.utils.constants import APPLICATIONS

    # Getting the first instance admin
    instance_admin = InstanceAdmin.objects.first()
    if instance_admin:
        generate_application(
            user_id=instance_admin.user.id,
            app_key=APPLICATIONS["runner"]["key"],
            application_model=Application,
            application_secret_model=ApplicationSecret,
            user_model=User
        )

class Migration(migrations.Migration):

    dependencies = [
        ("silo", "0010_create_plane_ai_app"),
    ]

    operations = [
        migrations.RunPython(create_runner_app, reverse_code=migrations.RunPython.noop),
    ]
