# Generated by Django 4.2.29 on 2026-03-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.silo.models.mcp
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_remove_webhook_version_webhook_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silo', '0013_create_bitbucket_dc_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=48, unique=True, validators=[plane.silo.models.mcp.mcp_slug_validator])),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=800)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('description_stripped', models.TextField(blank=True, null=True)),
                ('authorization_type', models.CharField(default='none', max_length=255)),
                ('status', models.CharField(default='inactive', max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(null=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_app_logo_asset', to='db.fileasset')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'MCP Application',
                'verbose_name_plural': 'MCP Applications',
                'db_table': 'mcp_applications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MCPConnectionCredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('auth_config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mcp_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_credentials', to='silo.mcpapplication')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_credentials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_credentials', to='db.workspace')),
            ],
            options={
                'verbose_name': 'MCP Connection Credentials',
                'verbose_name_plural': 'MCP Connection Credentials',
                'db_table': 'mcp_connection_credentials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MCPApplicationOwner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mcp_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_application_owners', to='silo.mcpapplication')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_application_owners', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_application_owners', to='db.workspace')),
            ],
            options={
                'verbose_name': 'MCP Application Owner',
                'verbose_name_plural': 'MCP Application Owners',
                'db_table': 'mcp_application_owners',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='mcpconnectioncredentials',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('mcp_application', 'user', 'workspace'), name='unique_mcp_credentials_per_user_workspace_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='mcpapplicationowner',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('mcp_application', 'workspace', 'user'), name='unique_mcp_application_owner_when_not_deleted'),
        ),
    ]
