# Generated by Django 4.2.5 on 2023-11-16 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instanceadmin',
            unique_together={('instance', 'user')},
        ),
    ]
