# Generated by Django 4.2.7 on 2023-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfiguration',
            name='category',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
