# Generated by Django 4.2.7 on 2024-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='version',
            new_name='current_version',
        ),
        migrations.AddField(
            model_name='instance',
            name='new_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
