# Generated by Django 4.2.7 on 2023-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instanceadmin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instanceconfiguration',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
