# Generated by Django 4.2.3 on 2023-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_instance_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_support_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='is_telemetry_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
