# Generated by Django 4.2.5 on 2023-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_instanceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfiguration',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
