# Generated by Django 4.2.7 on 2023-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_instanceconfiguration_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='user_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
