# Generated by Django 4.2.5 on 2023-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_instanceconfiguration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfiguration',
            name='value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
