# Generated by Django 4.2.3 on 2023-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='instance_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
