# Generated by Django 4.2.3 on 2023-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_license_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='check_frequency',
            field=models.CharField(null=True),
        ),
    ]
