indent-width = 4
preview = false
target-version = "py312"

# Exclude third-party code
exclude = []

lint.select = [
    "F",      # Pyflakes
    "W6",
    "E71",
    "E72",
    "E501",   # line-too-long
    "E702",   # multiple-statements-on-one-line-semicolon
    "E703",   # useless-semicolon
    "E731",   # lambda-assignment
    "W191",   # tab-indentation
    "W291",   # trailing-whitespace
    "W293",   # blank-line-with-whitespace
    "UP039",  # unnecessary-class-parentheses
    "C416",   # unnecessary-comprehension
    "RET506", # superfluous-else-raise
    "RET507", # superfluous-else-continue
    "A",      # builtin-variable-shadowing, builtin-argument-shadowing, builtin-attribute-shadowing
    "SIM105", # suppressible-exception
]

line-length = 150

[lint.isort]
force-single-line = true

[lint.per-file-ignores]
"docs/*" = ["ALL"]
"pi/agents/prd_writer/md2pdf/github_markdown.py" = ["ALL"]
"pi/core/vectordb/application.py" = ["E501"]