# Generated by Django 4.2.29 on 2026-03-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0133_estimate_external_id_estimate_external_source_and_more'),
        ('authentication', '0018_identityprovider_attribute_mapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTokenProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('issuer', models.CharField(max_length=512)),
                ('audience', models.JSONField(default=list)),
                ('jwks_url', models.TextField()),
                ('allowed_algorithms', models.JSONField(default=list)),
                ('user_claim', models.CharField(default='email', max_length=100)),
                ('jwks_cache_ttl', models.IntegerField(default=86400)),
                ('rate_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_token_providers', to='db.workspace')),
            ],
            options={
                'db_table': 'external_token_providers',
            },
        ),
        migrations.AddConstraint(
            model_name='externaltokenprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'issuer'), name='unique_workspace_issuer_when_not_deleted'),
        ),
    ]
