# Generated by Django 4.2.29 on 2026-03-26 08:00

from django.db import migrations


def create_oauth_bridge_app(apps, schema_editor):
    # Getting the models from apps to avoid circular imports
    Application = apps.get_model("authentication", "Application")
    ApplicationSecret = apps.get_model("silo", "ApplicationSecret")
    User = apps.get_model("db", "User")
    InstanceAdmin = apps.get_model("license", "InstanceAdmin")

    # Importing the function and constants directly here to avoid circular imports
    from plane.silo.services.generate_application import generate_application
    from plane.silo.utils.constants import APPLICATIONS

    # Getting the first instance admin
    instance_admin = InstanceAdmin.objects.first()
    if instance_admin:
        generate_application(
            user_id=instance_admin.user.id,
            app_key=APPLICATIONS["oauth-bridge"]["key"],
            application_model=Application,
            application_secret_model=ApplicationSecret,
            user_model=User,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('oauth_bridge', '0001_initial'),
        ('silo', '0013_create_bitbucket_dc_app'),
    ]

    operations = [
        migrations.RunPython(create_oauth_bridge_app, reverse_code=migrations.RunPython.noop),
    ]