# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_bridge', '0002_create_oauth_bridge_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaltokenprovider',
            old_name='user_claim',
            new_name='user_claims',
        ),
        migrations.AlterField(
            model_name='externaltokenprovider',
            name='user_claims',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
