name: Docker AIO build and smoke test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "preview"
    paths:
      - "apps/web/**"
      - "apps/space/**"
      - "apps/admin/**"
      - "apps/live/**"
      - "packages/**"
      - "turbo.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "Dockerfile.node"
      - "Dockerfile.api"
      - "Dockerfile.aio"
      - "docker-bake.hcl"
      - ".github/workflows/docker-smoke-aio.yml"
  push:
    branches:
      - "preview"
    paths:
      - "apps/web/**"
      - "apps/space/**"
      - "apps/admin/**"
      - "apps/live/**"
      - "packages/**"
      - "turbo.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "Dockerfile.node"
      - "Dockerfile.api"
      - "Dockerfile.aio"
      - "docker-bake.hcl"
      - ".github/workflows/docker-smoke-aio.yml"

concurrency:
  group: aio-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  determine-aio:
    name: Determine if AIO needed
    runs-on: ubuntu-latest
    outputs:
      aio_needed: ${{ steps.build-flag.outputs.aio_needed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            web:
              - 'apps/web/**'
            space:
              - 'apps/space/**'
            admin:
              - 'apps/admin/**'
            live:
              - 'apps/live/**'
            common:
              - 'packages/**'
              - 'turbo.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'Dockerfile.node'
              - 'Dockerfile.api'
              - 'Dockerfile.aio'
              - 'docker-bake.hcl'
              - '.github/workflows/docker-smoke-aio.yml'

      - name: Compute AIO flag
        id: build-flag
        uses: actions/github-script@v7
        with:
          script: |
            const anyCommon = '${{ steps.changes.outputs.common }}' === 'true';
            const changedWeb = '${{ steps.changes.outputs.web }}' === 'true';
            const changedSpace = '${{ steps.changes.outputs.space }}' === 'true';
            const changedAdmin = '${{ steps.changes.outputs.admin }}' === 'true';
            const changedLive = '${{ steps.changes.outputs.live }}' === 'true';
            const aioNeeded = anyCommon || changedWeb || changedSpace || changedAdmin || changedLive;
            core.setOutput('aio_needed', String(aioNeeded));

  aio_smoke:
    name: Build and smoke test AIO
    runs-on: ubuntu-latest
    needs: determine-aio
    if: ${{ needs.determine-aio.outputs.aio_needed == 'true' }}
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Docker version
        run: |
          docker version
          docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build AIO image with bake (load into local daemon)
        run: |
          docker buildx bake -f "./docker-bake.hcl" --load aio

      - name: Run AIO smoke script
        run: |
          chmod +x "scripts/smoke-aio.sh"
          "scripts/smoke-aio.sh"
