name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags:
      - '*'

jobs:
  build_push_frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Github Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: "registry.hub.docker.com"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker (Docker Hub)
        id: ghmeta
        uses: docker/metadata-action@v4.3.0
        with:
          images: makeplane/plane-frontend

      - name: Extract metadata (tags, labels) for Docker (Github)
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ghcr.io/${{ github.repository }}-frontend

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./apps/app/Dockerfile.web
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.ghmeta.outputs.tags }}
          labels: ${{ steps.ghmeta.outputs.labels }}
      
      - name: Build and Push to Docker Container Registry
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./apps/app/Dockerfile.web
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.dkrmeta.outputs.tags }}
          labels: ${{ steps.dkrmeta.outputs.labels }}

